### ISSUE TITLE
Delete note

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#10]
Need to allow owner to delete the note

**Comment by janniklorenz** [comment]
Related to #12

**Comment by Rory80Hz** [comment]
+1 for this, it would be great to be able to delete a note.

Example use case: I have something i want to be short-lived, and remove afterwards, for example on a self hosted instance, I may only want to explain an example quickly to a team member, then delete afterwards so it is not widely shared (info could be out of date / sensitive / incorrect)

**Comment by jackycute** [comment]
This feature will be available in the next release.

**Comment by jackycute** [comment]
Supported in 12d5ed43a7376e0ca361160698f07066218d6ed2

**Comment by thekyriarchy** [comment]
Are notes deleted after a certain duration of inactivity?

**Comment by SISheogorath** [comment]
No. They are only deleted when you use the button in the normal editor view.

**Comment by Sebi2020** [comment]
There is no button

**Comment by Perflyst** [comment]
I also see no button

**Comment by stezHH** [comment]
Same here. Will this issue be adressed? I can't find a way to delete a note or a part of the versions history for that matter - am I getting something wrong?

**Comment by jackycute** [comment]
> Same here. Will this issue be adressed? I can't find a way to delete a note or a part of the versions history for that matter - am I getting something wrong?
> 
> I'm talking about the demo version of CodiMD on demo.codimd.org

You can delete the note that you *owned* via the top right permission menu in the view pane.
Our demo instance is: https://codimd-app.herokuapp.com/

**Comment by Sogolumbo** [comment]
There should also be an option to delete guestnotes.
For example the user who opens the panel could be asked for an expiration date.
