### ISSUE TITLE
Embedd PDF

### ISSUE THREAD

**Issue by zuphilip** [hackmdio/hackmd#103]
I like the direct integration of slides from slideshare and speakerdesk and wondering whether the same could also be possible for PDFs. Can an online PDF be embedded directly in the page? For WordPress there is a similar plugin for that porpuse, see https://de.wordpress.org/plugins/pdf-embedder/, which uses a syntax like
```
[pdf-embedder url="https://mysite.com/wp-content/uploads/2015/01/Plan-Summary.pdf"]
```

**Comment by jackycute** [comment]
I think this can be done by https://github.com/pipwerks/PDFObject.
But the syntax, I might use `{%pdf https://pdfobject.com/pdf/sample-3pp.pdf %}` for consistency.
What do you think?

**Comment by zuphilip** [comment]
Wow, that sounds great! The syntax you suggested seems to be more in line with the other embeddings you already have. There seems to be different options for `PDFObject` but I haven't looked into that more closely.

**Comment by jackycute** [comment]
I still a bit curious about why you want to embed PDF in note?
Could you tell me some user scenario?

If you agreed with that package then we can schedule this feature in the roadmap.

**Comment by zuphilip** [comment]
My use case: I started with collection where we can collaboratively add add a link to our material we use for some software (Zotero): https://hackmd.io/s/SySI-f3x . Then I realized that it is actually possible to embedd the slideshare presentations as well as the webinar on YouTube directly. This makes the collection/presentation more interesting to look at and searching for some similar slides easier. However, some presentations are only linked and not embedded because the PDF is lying somewhere on the web. Thus, I opened this issue here.

In general: Such a feature allows to show a pdf and write some text around, i.e. one has not to switch to different pages or maybe switch from the browser to the pdf viewer. For normal A4 PDFs the text size may be too small to read, if embedded in a page.

I can't say much about the package, but it seems suitable for embedding PDFs in HTML pages.

**Comment by jackycute** [comment]
OK, sounds great!
Thanks for sharing your usage.

Then we'll see this feature soon.

**Comment by jackycute** [comment]
Supported in 3424cdd7713421d3fc88a501c1cd7606c943a05e

**Comment by jackycute** [comment]
Hmm, I don't see this happening in my environment.
Could you tell me more about yours? Browser version, PDF viewer version and OS please?

![image](https://cloud.githubusercontent.com/assets/2639151/16251595/ff5947b8-3859-11e6-9cc7-ddb8d14aca86.png)

**Comment by zuphilip** [comment]
Sure, I have: Windows 8, Firefox 47.0, Acrobat DC Version 2015.016.20045 with Plugin Version 15.16.20045.57024

**Comment by jackycute** [comment]
OK, I can reproduce that issue.
But that seems to be Adobe Reader's problem.
https://forums.adobe.com/thread/745905

If I need to fix this, that will be a workaround.
Could you turn off that plugin and use Firefox built-in PDF viewer? That's better.
https://support.mozilla.org/en-US/kb/view-pdf-files-firefox-without-downloading-them#w_using-the-built-in-pdf-viewer

**Comment by zuphilip** [comment]
Yes, I can use the Firefox built-in PDF Viewer. I use another extern PDF viewer anyway normally and for showing embedded PDFs it doesn't matter which viewer I choose. Thank you again!
