### ISSUE TITLE
增加google登入 / Support Google Signin

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#104]
登入的方式增加使用Google帳號登入的選項。

> Add "sign in via google" option on signin methods.

**Comment by jackycute** [comment]
Support in 6405bb505695a5592efe8aa8d5bde9e723fadfc0

<img width="542" alt="2016-05-21 10 35 57" src="https://cloud.githubusercontent.com/assets/2639151/15449101/cb464276-1fa6-11e6-969a-d49e50e92e7f.png">
