### ISSUE TITLE
"編輯權限"顯示的位置 / Change the position of permission type

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#105]
目前編輯權限顯示在文章右上方，是否可移置top bar

> The permission type show up on the top right corner of the view area.
> Can it move to top bar?
> It's hard to see and change the permission type on the edit mode

**Comment by SISheogorath** [comment]
I think not too many people are unhappy with its current position. We'll leave it there for now, maybe another day there will be a big redesign :)

Thanks for your suggestion!
