### ISSUE TITLE
使"檢視區塊"滑動時，"編輯區塊"也能跟著移動 / Also sync the progress bar from "view" pane to "edit" pane

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#106]
"檢視區塊"滑動的時候，"編輯區塊"也可以跟著滑動
或是設置開關也可以

> let "edit" pane also sync scroll progress from "view" pane.
> or maybe have a toggle for that

**Comment by jackycute** [comment]
Support in bf1dc237a993f53bbc4d90fd1c81e325d4517fcd
