### ISSUE TITLE
History should also track publish note browse record

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#111]
建議 在publish模式下閱讀過的文章也要加入歷史清單內，
今日發現，若是從google搜尋到的已發布文章，檢視之後不會顯示在歷史清單。

> Suggest also add the published note read record in history.
> Today I found that if read the published note which searched from google won't in the history.

**Comment by jackycute** [comment]
這個功能我沒有覺得很必要
因為 publish note 你可以從自己的瀏覽紀錄找到
這裡設計的 history 主要是為了紀錄想編輯的筆記
而且都放在一起看起來會更雜的

**Comment by TzuChin** [comment]
OK!
瞭解你的意思~
