### ISSUE TITLE
应用能支持其他语言么

### ISSUE THREAD

**Issue by 1740024005** [hackmdio/hackmd#112]
如果可以。请问怎么设置。
谢谢！

**Comment by jackycute** [comment]
您好，不是很懂你的意思
是可以設定筆記的語言？還是可以設定網站介面的語言？
如果是內容的話，什麼語言應該都可以輸入的

筆記的語言可以用 YAML metadata 設定
至於網站介面還沒有支援多國語言，只有英文可以用

**Comment by 1740024005** [comment]
谢谢，我想问的是网站界面语言！

**Comment by jackycute** [comment]
好的，那麼目前網站介面只支援英文，您可以貢獻或是用這個 issue 來等待支援多國語言

**Comment by jackycute** [comment]
Supported in b9c59c454d68e35708f64703a423930b99075cab
