### ISSUE TITLE
Embed videos in slide mode

### ISSUE THREAD

**Issue by zuphilip** [hackmdio/hackmd#113]
If you embed videos (youtube, vimeo) they will work for the normal `View` but not in `Slide Mode`. There you will see the unrendered markdown:

![videos-in-slides](https://cloud.githubusercontent.com/assets/5199995/14935317/208a3750-0ecd-11e6-97ec-6a563b8c7218.png)

**Comment by jackycute** [comment]
Yes, `slide mode` now is in beta.
Because it used different markdown rendering engine, will take time to make it have all the extra features.

You can leave this issue here to track updates.

**Comment by jackycute** [comment]
Supported in d39f1fc70084ad5b7c40a03657e5ff8d03cc7944

**Comment by zuphilip** [comment]
Cool, I tried it out and it seems to work in Chrome but not in Firefox 47 (Win 8). On this [example](https://hackmd.io/p/Skt8tds7#/1) the following errors are shown in the browser console:

* mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create	**markdown-it-imsize.js:592:4**
* String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead **string.min.js:1:1966**
* TypeError: asm.js type error: incompatible type for argument 5: (f64 here vs. i32 before)	**viz.js:15:243872**
* ReferenceError: event is not defined	**slide.js:61:5**

**Comment by jackycute** [comment]
Fixed in 3c7d39c52dccd7f87ee97c7f59bd2d86ed687bb8
Thanks for heads up.

**Comment by zuphilip** [comment]
Wow, that was incredibly fast! Thank you very much! The videos in slides works now also in Firefox. :tada:
