### ISSUE TITLE
介面稍微跑版

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#115]
![image](https://cloud.githubusercontent.com/assets/13016773/15071015/1dbb2c9e-13bb-11e6-97af-d7f29dc2ff95.png)

如上圖，
某些時候開啟時，
top bar會稍微跑版，
但是不是很常發生，
當下檢視沒有錯誤訊息

**Comment by jackycute** [comment]
摁，這我有發現，是需要修正一下沒錯

**Comment by jackycute** [comment]
實在是有點難重現這個跑版 QQ
只能等到下次跑版的時候，找到問題才能修了...

**Comment by jackycute** [comment]
Try fix in 8e8a5e1ecb37f1464b8d7c688a220e2d1436476f
Reopen if needed
