### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by Angristan** [hackmdio/hackmd#116]
When using the image upload feature, the markdown is `![](http://i.imgur.com/xxxxxx.jpg)` so the image is requested over http and not over https which give a mixed content warning in the browser.

I searched in the code but I don't see where it is.

**Comment by jackycute** [comment]
Oh, the image url is from imgur.
When you upload the image will send to hackmd server then transport to imgur, then imgur response the uploaded image url which is not starts with `https`.
I know this issue for a while, I'll look up some workarounds, thanks @Angristan !

**Comment by Angristan** [comment]
Oh that's what I feared :/ I don't know much of JS but maybe if you can only get that HTTPS URL, maybe you can transform it to HTTPS. Thanks for the answer :)

**Comment by jackycute** [comment]
Yeah, because the imgur api response with non-https image url.
I will workaround it soon :smile:

**Comment by jackycute** [comment]
Fixed in 3b5e74c9c4ac155a473f3284f0ca4180c834cabc

**Comment by Angristan** [comment]
So fast :o
