### ISSUE TITLE
Editor buggy (Firefox)

### ISSUE THREAD

**Issue by janniklorenz** [hackmdio/hackmd#127]
In Firefox, the editor has an offset between the cursor and the marked line, after someone else adds a new line above your cursor.

![screen1](https://cloud.githubusercontent.com/assets/1284753/15477324/366926a4-2114-11e6-9b72-6ed1c44bce14.png)

**Comment by jackycute** [comment]
Bug confirmed, working on it.

**Comment by jackycute** [comment]
Fixed in ee3c6b5485698e39c011a9aec546568e4e8b6f79
