### ISSUE TITLE
Support two-column editor mode

### ISSUE THREAD

**Issue by radare** [hackmdio/hackmd#128]
It will be nice to have a mode with two columns to edit at different scrolling positions. This way it will be better for editing and moving text back and forth without having to scroll or use different browser windows

**Comment by jackycute** [comment]
Hi @radare
I assume you know that we already have "two columns" mode which I call it both mode.
![image](https://cloud.githubusercontent.com/assets/2639151/15503569/222ffcc4-21ed-11e6-9572-9d08ef610932.png)


So do you mean it would be nice if you could have two columns that all are in edit mode? Or else?
Please clarify your needs, we would very glad to help :smile:

**Comment by radare** [comment]
i want this mode, but with editor in both sides instead of render vs markdown

**Comment by jackycute** [comment]
OK, I get it, will try to make it more flexible.
Thanks again.

**Comment by radare** [comment]
awesome feedback. thanks!

**Comment by ccoenen** [comment]
I would be curious what the benefit over two browser windows would be? Especially since it's already mentioned in the original post.

This sounds like a lot of work for a feature few people use, and which has a valid workaround.

**Comment by radare** [comment]
If code was properly organized it shouldnt be that hard to add a scrolling view panel with a specific renderer attached to it. Not all browsers or window managers permit having multiple instances or side by side windows of the same page. But if thats really an issue its ok for me to close that.

**Comment by ccoenen** [comment]
@radare I'm going to close this, I believe that it's out of scope for now.
