### ISSUE TITLE
Multiple Configs and Daemon Tools

### ISSUE THREAD

**Issue by janniklorenz** [hackmdio/hackmd#13]
The first thing I need to know when I set up an instance of HackMD, ist where the config is located. But it looks like there are many redundancies here. 

The `DATABASE_URL` and `MONGOLAB_URI` are located in the `config.js`, `processes.son` and `run.sh`. 

Why? And why we need those daemon tools at all? All my node projects I've done so far contains a single `config.js` file which is included everywhere I need to and do not contain daemon tools at all.

They sometimes may have advantages, but this should not be a part of the project. If some user decide to use it, he can set it up himself, but the server should be able to be started with a simple `node(js) app.js` command.

**Comment by jackycute** [comment]
You're right, I will make this clear in the next milestone.
These configs are for users who want to use daemon tools but it's not required to use those packages right now.
Maybe I can declare which env vars should be set in the docs instead providing the config files directly.

**Comment by jackycute** [comment]
Hey, I've updated the README for more infos, please check!

**Comment by jackycute** [comment]
Closed this issue now, you can re-open as needed
