### ISSUE TITLE
Remove login button

### ISSUE THREAD

**Issue by Lapin0t** [hackmdio/hackmd#130]
Hi, I can't say enough how much I love you guys! I was stuck with etherpad and clearly it sucks. And I love markdown, and mathjax, and ... you got it.

I don't need any login features (mostly I don't want external signups) so would it be possible to remove the _Sign In_ button when no signup method is enabled? It may be a simple and specific feature so I am probably going to do a little PR to fix that.

A more stable solution could be to provide internal signup or some sso protocols support.

**Comment by janniklorenz** [comment]
Hi,

I've got the same problem, mostly because of the external signup, and fixed it. It's already merged into master (https://github.com/hackmdio/hackmd/pull/101), but not released.

**Comment by jackycute** [comment]
@Lapin0t Thanks for loving this! For internal signup, please stay tune with #36

@janniklorenz Thanks for your PRs. I will try to release that soon, was busy on other issues.

**Comment by jackycute** [comment]
Release in 0.4.2 c439797efdadb5620198c82df7ac55a20e2fc925

**Comment by Lapin0t** [comment]
Nice guys! (indeed, the fix was 4 lines long!)
