### ISSUE TITLE
"this page need refresh" 持續重複出現

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#132]
![image](https://cloud.githubusercontent.com/assets/13016773/15723573/a0e4c66a-2875-11e6-92ce-7ecde513a0c1.png)

會一直重複出現此跳窗
1. click "refresh" ，無效
2. ctrl + F5 ，無效
3. 清除cookie，無效
4. 開啟Disable cache 後再檢視，無效
5. 重登帳號，無效
6. FB帳號 & google帳號 都會發生此問題，新檔案也是會有~

**Comment by jackycute** [comment]
這是因為客戶端版本跟伺服器版本不同所導致

昨天晚上 10 點左右的時候，伺服器更新至 0.4.2
請您再試試看，應該是沒有這個問題了～

**Comment by TzuChin** [comment]
使用的是線上版的 [hackmd](https://hackmd.io/)

經剛剛測試，
清除cache後，問題還是會存在，
但是**重啟瀏覽器**後就會正常了，
瀏覽器是
Google Chrome 50.0.2661.102 m (64-bit)
Google Chrome 53.0.2754.1 canary SyzyASan

**Comment by jackycute** [comment]
如果還有遇到類似的問題再 reopen 這個 issue
