### ISSUE TITLE
無法刪除歷史紀錄，js error

### ISSUE THREAD

**Issue by TzuChin** [hackmdio/hackmd#133]
![image](https://cloud.githubusercontent.com/assets/13016773/15723867/ebbe0498-2876-11e6-9015-14297da3899b.png)

兩行紅字，
上面那行在進入歷史紀錄清單時會出現；
下面那行在點擊刪除紀錄的"Yes, do it!"時出現

**Comment by jackycute** [comment]
請您重新整理頁面再試試看，我目前無法重現這個問題

**Comment by TzuChin** [comment]
使用的是線上版的 [hackmd](https://hackmd.io/)

經剛剛測試，
清除cache後，問題還是會存在，
但是重啟瀏覽器後就會正常了，
瀏覽器是
Google Chrome 50.0.2661.102 m (64-bit)
Google Chrome 53.0.2754.1 canary SyzyASan

**Comment by jackycute** [comment]
如果還有遇到類似的問題再 reopen 這個 issue
