### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by Lapin0t** [hackmdio/hackmd#134]
Hi, I can't find anything related to internationalization support. Did I miss it? If not it would be nice to use a i18n library so that people can translate HackMD.

**Comment by jackycute** [comment]
No, you didn't miss anything.
We haven't use any i18n library yet, but we should.
Do you recommend any?

**Comment by Lapin0t** [comment]
I have very little experience in javascript/node but [this page](https://gist.github.com/martinheidegger/89a29b9893433aba32d1) seems to list some possibilities (`i18n`, `i18next`, `node-gettext`, ...).

**Comment by jackycute** [comment]
Thanks! @Lapin0t 
I'm considering `i18n` or `i18next` (more popular), but don't know their pons/cons.

**Comment by jackycute** [comment]
Refer to #112

**Comment by jackycute** [comment]
Supported in b9c59c454d68e35708f64703a423930b99075cab
