### ISSUE TITLE
Support for exporting raw HTML

### ISSUE THREAD

**Issue by zeryx** [hackmdio/hackmd#135]
I'm a big fan of working with markdown and I love the hackmd.io online editor, as it's superior to most other markdown -> html editors on the web.

However I noticed when I exported my finished markdown doc to html I had a bunch of other "crud" baked into my perfect markdown doc which was painful to remove.

Would it be reasonable to support raw html exporting? [jbt.github.io/markdown-editor/](t.github.io/markdown-editor/) does a good job of it, however their editor is nowhere near as good and saving is.. iffy.

**Comment by jackycute** [comment]
Hi @zeryx 
I think it would reasonable to support raw HTML exporting.
But do understand the raw html will be nothing but just plain HTML (no javascript, no styles, no candies).

**Comment by zeryx** [comment]
Yeah purely raw HTML is what I'm looking for, I embed large html objects in script sanitized inputs that can't handle css or javascript, and throwing those in there just confuses everything. The output from https://github.com/hackmdio/hackmd/issues/t.github.io/markdown-editor/ on `ctrl+shift+s` and save as html is ideal for my needs.
 Thanks for the fast response, keep up the good work on a great app!

**Comment by jackycute** [comment]
Supported in cb1e00d1d149c7a331e9d37cc73927a6aa5c7cf6
