### ISSUE TITLE
external 功能可否支援 google analytics ?

### ISSUE THREAD

**Issue by fgtseng** [hackmdio/hackmd#136]
externet 功能可否支援 google analytics ?

**Comment by jackycute** [comment]
Could you explain more about why you need to use google analytics in here?
I think this might exceed our project scope a bit.
Thanks!

**Comment by fgtseng** [comment]
Just want to know more about profiles of viewers in slide mode. Anyway, thank you for your response.

**Comment by jackycute** [comment]
OK, I think somehow this sounds reasonable.
But I would support this feature in meta instead of externals.

**Comment by fgtseng** [comment]
Thank you.

**Comment by jackycute** [comment]
Supported in 558304ff62a648e604b03afe3372ef9566aea850

**Comment by fgtseng** [comment]
I tried it and could be worked well with YAML metadata. Thank you very much.
