### ISSUE TITLE
Link maintains focused after click

### ISSUE THREAD

**Issue by thug-gamer** [hackmdio/hackmd#139]
When you insert a link like this `[click here](http://mywebsite.org)` and click it, the link opens in a new tab. When you switch back to hackmd, the clicked link is still in focus.
Tested with Chrome 51, Windows 10 64 Bit

**Comment by jackycute** [comment]
Hi @thug-gamer 
That is the default behavior from browser that tell you than link have been visited.
And that visited style of links is origin from bootstap, I never modify it.
It helps on accessibility of the web to indicate what's you just visited until you focus on other things.

So I need to know why you don't prefer this behavior and this is not a bug.

**Comment by thug-gamer** [comment]
Oh, I might now have been clear about my statement. I am not talking about the visited link color after you click a link. When you mouseover a link its color changes and gets a underscore line. After a click, it maintains as if you are still mouseovering the link. When you click outside, the focus disappears.

**Comment by jackycute** [comment]
Yes, that is the normal and default behavior and that is named the visited link.
You can try bootstrap http://getbootstrap.com/css/ or normalize.css https://necolas.github.io/normalize.css/ even https://twitter.com/
They all acting the same.

But GitHub seems did adjustment for this, it will show the same style on visited links or normal links.

**Comment by thug-gamer** [comment]
I agree. This is the normal behaviour :+1:
