### ISSUE TITLE
Redirect URI for OAuth services?

### ISSUE THREAD

**Issue by elboletaire** [hackmdio/hackmd#140]
First off, very good work with hackmd. I've recently installed it on our office and will replace the tool we were using til now (just a php markdown parser).

But I'm trying to configure gitlab oauth service, so we can easily login in our office, without success. Every redirect URI I've tried fails with the `The redirect URI included is not valid.`.

What should i use as redirect URI? I've tried just the domain, and other combinations from other node.js apps (just in case you were using the same library):

- http://hackmd.example.com
- http://hackmd.example.com/
- http://hackmd.example.com/_oauth/gitlab

I'm sure is not related to the http because I've rocket.chat (under http) OAuth integration working without problems with Gitlab (under https).

Thanks in advance.

**Comment by jackycute** [comment]
Hi @elboletaire, thanks for choosing us.

Sorry about that, I didn't mention the oauth path clearly.
It's written here: https://github.com/hackmdio/hackmd/blob/master/lib/auth.js#L93
In other words: `http://hackmd.example.com//auth/gitlab/callback` will be your oauth callback url.

Hope this helps.

**Comment by elboletaire** [comment]
Yeah! It's working perfectly now. I close the issue but you should consider adding that information to the readme file :smiley:

**Comment by elboletaire** [comment]
Yup, I'm gonna open a new issue for you. The login works, but throws an internal server error. Reloading the page after the error I can see that I've logged in successfully.

**Comment by jackycute** [comment]
Great! I will add that to the readme, thanks for heads up.

Maybe that internal error happened because of the previous bad session.
Anyway, I would like to see the error logs.

**Comment by jackycute** [comment]
Information added in commit e3a31bc7323f919089286103bb9b93270db506f3

https://github.com/hackmdio/hackmd#third-party-integration-oauth-callback-urls

**Comment by elboletaire** [comment]
:+1:

**Comment by elboletaire** [comment]
After enabling the `debug` option in `common.json` I cannot see any log inside the `hackmd` folder. I've searched under `tmp` and I've even tried a recursive search for `*.log` files without success.

What am I missing? Should I also pass the ENV variable?

**Comment by jackycute** [comment]
OK, so the debug option in `common.js` is only for browser debug.
The server debug is in `config.json`, you need to add `"debug": true` below your settings or the environment variable `DEBUG` will works too.
The log location is depends on how you run it, if you didn't setup it and run with pure `node` command, the output from the terminal is the logs.

BTW, could you reproduce that internal server error with signin/signout several times?

**Comment by elboletaire** [comment]
Sorry, I said in `common.js` but I meant in `config.json`.

I'm running hackmd with docker, using rancher, which logs me the output in rancher itself, but I don't see anything :\

And yes, I can still reproduce the issue. Every time I login with gitlab returns an internal server error. Or every time I give my credentials from gitlab (which, I guess, redirects to the login).

**Comment by elboletaire** [comment]
Sorry, I was not seeing anything because the rancher logs are not working as expected xD

Now I've got an error, so I'm opening a new issue for it :)
