### ISSUE TITLE
css couldn't display correctly via Facebook messenger

### ISSUE THREAD

**Issue by ttcat** [hackmdio/hackmd#143]
CSS couldn't display correctly when open hackmd edit link via Facebook messenger (tested on IOS)

**Comment by ttcat** [comment]
![image](https://cloud.githubusercontent.com/assets/1935330/16714124/98ec55c8-46ec-11e6-8dc2-c1ecc5785fa2.jpeg)

**Comment by jackycute** [comment]
I can't reproduce this issue under iOS 9.3.2 and Messenger 78.0.

![13646862_10206883845162346_1918670161_o](https://cloud.githubusercontent.com/assets/2639151/16714503/c11caa74-46f7-11e6-8499-3a43e4ec2ef2.jpg)

Please terminate your Messenger App or Reboot your iOS to clear cache and see if it persist.
Thanks!

**Comment by ttcat** [comment]
I've tried Reboot and got the latest version same like you.
but I got the error again even from different hackmd url. 😂

**Comment by jackycute** [comment]
It's really hard to tell whether is the browser issue or our issue.
I need to reproduce or having the iPhone with that issue to inspect and solve.

BTW, is HackMD ok with Safari in your phone?

**Comment by jackycute** [comment]
Leave the links that you couldn't browse properly in facebook messenger.
Did you use and plugin or somehow could set messenger not loading css?
I tried many times but just can't reproduce this issue.

**Comment by ttcat** [comment]
I can try another two iPhone devices tonight and I will get back here.

Just simply: http://hackmd.io/features

Max Wu <notifications@github.com>於 2016年7月11日 週一，下午2:22寫道：

> Leave the links that you couldn't browse properly in facebook messenger.
> Did you use and plugin or somehow could set messenger not loading css?
> I tried many times but just can't reproduce this issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackmdio/hackmd/issues/143#issuecomment-231651260>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB2H4ok1RX6MwgChkAD7NOthWU8bhCcUks5qUeE7gaJpZM4JI173>
> .
>
-- 
吳銘軒 / Wu Min Hsuan
開放文化基金會 / 副執行長
+886 935 697 573

**Comment by ttcat** [comment]
Alright seems just my messenger somehow went crazy. Delet the app and re download can fix it!
