### ISSUE TITLE
全域設定 Slide-transition

### ISSUE THREAD

**Issue by opjlmi** [hackmdio/hackmd#144]
這不是bug，這是個feature

建議能有一次全域設定Slide-transition的功能
不然有時候想要所有切換動畫都相同
但是卻必須一一設定

**Comment by jackycute** [comment]
Ok sure, will make this available in yaml-metadata

**Comment by jackycute** [comment]
Supported in b367e110b639ab707e848d1d6de70bb094cd0edd

**Comment by jackycute** [comment]
Insert below in the beginning of your note

```
---
slideOptions:
  transition: fade
---
```
