### ISSUE TITLE
revealjs output slide display problem

### ISSUE THREAD

**Issue by aweimeow** [hackmdio/hackmd#145]
following is the markdown format I wrote, 
```
---
Index
----
1.1
----
1.2
---
2
```

When I press right arrow, page switch from 1.2 to 2, 
and I press left arrow to view 1.2, the slide is display as following:
![](http://i.imgur.com/vhH2var.jpg)
but it should be
![](http://i.imgur.com/X1esxck.jpg)

**Comment by jackycute** [comment]
Could you give a link or a full example of this issue?
I couldn't reproduce it according the format you provided.

And what's your browser version? also the OS?

Thanks.

**Comment by aweimeow** [comment]
Hello, This is the [Example Link](https://hackmd.io/MYFgpgHAjADAZgVgLQGYLySAJigbEgTkRCTgCMtgAmRKNXLIA===) and [Slide Mode Link](https://hackmd.io/p/HyVXSNjP#)

My borwser version is: Firfox 47.0
OS version is: Windows 10

Thanks !

**Comment by jackycute** [comment]
Seems like Firefox change some rendering path in version 47.
I was in Firefox version 43 but didn't have this issue until upgrade 47.
Try to solve now.

**Comment by jackycute** [comment]
I think here needs some workaround to force it redraw.
Will do it soon,.

**Comment by jackycute** [comment]
I also found out the overview on the Mac glitch even harder.
But I think it's firefox issue, not sure if I can workaround this.

<img width="1231" alt="2016-07-30 6 41 45" src="https://cloud.githubusercontent.com/assets/2639151/17269801/535e5f58-5685-11e6-8e86-074a31dcfd8e.png">

**Comment by jackycute** [comment]
Fix in eab984defff23e2bcf5edfd930714243653eafe2

**Comment by aweimeow** [comment]
辛苦了 ~

**Comment by jackycute** [comment]
I made a PR to reveal.js
https://github.com/hakimel/reveal.js/pull/1649
