### ISSUE TITLE
Move cursor to start/end of line is wrong for multi-line parragraphs

### ISSUE THREAD

**Issue by f3r** [hackmdio/hackmd#146]
Hi there,

First of all, thanks for a really good piece of software.. I'm enjoying a lot working with it!! 

Right now, the default behavior is that when text is longer than the container width, hackmd will soft-wrap. I like this a lot.

![image](https://cloud.githubusercontent.com/assets/970858/17231541/7ece7d38-551a-11e6-8a35-6709daafc9f5.png)

If your cursor is somewhere in the middle of line 2 and you want to go to the beginning of **Line2**, the standard behavior in modern text editors (subl/atom/...) is to just use CMD+LEFT / CMD+RIGHT or a combination of some sort.

In Hackmd, for some reason, trying to go to the beginning of the line moves the cursor to the beginning of the entire parragraph: **Line 1**, and trying to go to the end of the line will also move it to the end of **Line3**.

Would it make sense to move it to the end of the soft-wrapped line instead of the actual line?

Thanks so much!!!
/F3R

**Comment by jackycute** [comment]
Hi @f3r,
This totally possible and I agreed with you.
Will do this before next release.

**Comment by jackycute** [comment]
Wait a second, what keymap are you using?
I'm using sublime keymap (default), it behave like you said (shortcut key will move to wrap line start and end).

**Comment by f3r** [comment]
I'm using it on Chrome/Ubuntu, and I found somehow the behavior I wanted for long soft-wrapped lines today:
*  Fn + Left/Right: End of actual line (non-wrapped)
*  Cmd + Left/Right: End of soft-wrapped line

Closing the issue, thanks @jackycute!!

**Comment by f3r** [comment]
btw, I believe it was something related to `goLineLeft`... https://codemirror.net/doc/manual.html#command_goLineStartSmart ;)

**Comment by jackycute** [comment]
Yes, and it already set in here
https://github.com/hackmdio/hackmd/blob/master/public/js/index.js#L47
