### ISSUE TITLE
config.json "urladdport" setting (set to "false") not honored

### ISSUE THREAD

**Issue by purldator** [hackmdio/hackmd#147]
I used the [docker setup](https://github.com/hackmdio/docker-hackmd) to deploy an instance of hackmd + PostgreSQL.  My parent host's nginx-powered site blocks are set to serve hackmd via reverse proxy and under port 443/ssl (Let's Encrypt certificate installed and working).

My hackmd-container's config.json:

````
{
    "production": {
        "domain": "md.weavewordswith.me",
        "port": "3006",
        "protocolusessl": "true",
        "urladdport": "false",
        "db": {
            "username": "hackmd",
            "password": "hackmdpass",
            "database": "hackmd",
            "host": "hackmdPostgres",
            "port": "5432",
            "dialect": "postgres"
        }
    }
}
````
I had to use port 3006 since port 3000 is used by a rocket.chat instance.

The site is technically up: https://md.weavewordswith.me/
But all resource links still have `:3006` appended to the domain/hostname `md.weavewordswith.me`.

Was setting `urladdport` to `false` the correct action to remove the `:3006` references on all internal links?

**Comment by jackycute** [comment]
Hi @purldator,
Since the boolean in the json file DO NOT need a quote or it will consider as true value.
You might need to change it like below:

```json
{
    "production": {
        "domain": "md.weavewordswith.me",
        "port": "3006",
        "protocolusessl": true,
        "urladdport": false,
        "db": {
            "username": "hackmd",
            "password": "hackmdpass",
            "database": "hackmd",
            "host": "hackmdPostgres",
            "port": "5432",
            "dialect": "postgres"
        }
    }
}
```

Thanks!

**Comment by purldator** [comment]
@jackycute Thank you for that.  An error on my part due to ignorance of json's specific nuances.  

Learned something new, and got an instance of hackmd running.  

Much obliged! :pray:
