### ISSUE TITLE
Doesn't work Ctrl+C copy action in vim insertion mode

### ISSUE THREAD

**Issue by elliptic-shiho** [hackmdio/hackmd#148]
I'd like to use Ctrl+C to copy to system clipboard (because hackmd's yank function can't copy to it). I tried it, but only back to normal mode when push Ctrl+C in Insertion mode...

**Comment by jackycute** [comment]
Hi @elliptic-shiho 
Since we're using codemirror, I'm going to refer some related issues from it.
https://github.com/codemirror/CodeMirror/issues/3075
https://github.com/codemirror/CodeMirror/issues/3347

So I think the only way to rebind the copy key again, let me try.

**Comment by jackycute** [comment]
OK, I made workaround in f49fc192f64a7fb86baa8eae5717ea87de43c8e5
Refresh the page if you're using the online service and try.

**Comment by elliptic-shiho** [comment]
@jackycute I confirmed it. I tried Ctrl+C and It's worked normally! Thanks you for quick response.

**Comment by jackycute** [comment]
You're welcome.
