### ISSUE TITLE
可以使用mysql来代替PostgreSQL吗？

### ISSUE THREAD

**Issue by aiyuchen** [hackmdio/hackmd#15]
PostgreSQL没用过，不了解啊。另外这个程序有中文文档吗？

**Comment by jackycute** [comment]
PostgreSQL比較穩定啊，裝起來也很容易的
這個也能支援MySQL，不過要寫一點外掛之類的

目前沒有中文文檔，但是日後如果有需求就會補上
謝謝！

**Comment by ericdai** [comment]
postgresql 9.4 以后字段也可以支持JSON啊，似乎可以不要mongodb啊

**Comment by swhgoon** [comment]
"可以不要mongodb", support +1

**Comment by jackycute** [comment]
好的，目前會逐步改用其他RDB，例如PostgreSQL或是MySQL

**Comment by lealife** [comment]
+1 希望能支持 MySql

**Comment by jackycute** [comment]
或許用ORM能夠滿足需求？
Maybe we can use ORM to solve such problems?

**Comment by jackycute** [comment]
暫時會先採用 PostgreSQL，MongoDB 不會採用了

**Comment by jackycute** [comment]
Support PostgreSQL, MySQL, MariaDB, SQLite, MSSQL in version 0.4.0
