### ISSUE TITLE
feature request: support embedded base64-encoded images and objects

### ISSUE THREAD

**Issue by cyberic99** [hackmdio/hackmd#152]
It would be great if we could embed images without using imgur, directly in base64 form:
For instance:
![an example red dot](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)

**Comment by jackycute** [comment]
Will support this soon.

**Comment by jackycute** [comment]
Supported in ecd7218917184cdd755774aa779dfa72e95233c1

**Comment by cyberic99** [comment]
Thank you!
Is it possible to handle uploaded pictures this way, and embed them directly as base64? 
Thank you

**Comment by jackycute** [comment]
@cyberic99 Not recommended, string will be too long and it's a waste of db space (that's why we use image files sir).

**Comment by cyberic99** [comment]
you're right about the wasted space. but it worries me a bit to depend on an external and online service like imgur, to store pictures.
Another solution would be a static file in the same directory as the .md file

**Comment by jackycute** [comment]
Yeah, it's not the best to depend on external online service to store images.
But we're using database the store notes for now.
Will try to support filesystem in the future, see #90 

And I am considering to support local uploading images.
You could open another issue for that :smile:

**Comment by cyberic99** [comment]
I've opened an issue there:
https://github.com/hackmdio/hackmd/issues/156

Thank you for your work
