### ISSUE TITLE
Images behave strangely in slide mode

### ISSUE THREAD

**Issue by mixmix** [hackmdio/hackmd#153]
when you make a slide with an image in it, the whole slide fails to be rendered

e.g. 
https://hackmd.io/JwFgjAHATAZgpgYwLQBMAMAjFSQzQZiQEN8BWUpUiBANjhH3xCghiA==#

slide rendering : https://hackmd.io/p/Sya_Cydt#/
misses the second slide titled "Nice images"

**Comment by mixmix** [comment]
[EDIT] - the slides with images is there, it's just `slide 1.1` which is 'down' from the first slide .... I expected it to be slide number 2

**Comment by jackycute** [comment]
Hi @mixmix
We're using [reveal.js](https://github.com/hakimel/reveal.js) right here for the slide mode.
And the `1.2` slide number is the default behavior.

You can change that [slide number](https://github.com/hakimel/reveal.js#slide-number) option via the [yaml metadata](https://hackmd.io/yaml-metadata).
For example:

```
---
slideOptions:
  slideNumber: 'c/t'
---
```

Will show the slide number as `1/4`.

Hope this helps :smile:

**Comment by mixmix** [comment]
thanks for the quick reply
I'm less concerned about the numbering and more concerned with the _flow_  as in if I create 4 slides I want there the be 4 slides in my show, now 3 and one hidden off to the side.

Any idea why that is?

**Comment by mixmix** [comment]
Solved it, you need to demarcate the first slide with a page-break!?

```
----

# slide 1

---

# slide 2


```

**Comment by jackycute** [comment]
I don't get it.

```
---
slideOptions:
  slideNumber: 'c/t'
---

# slide 1

----

# sub slide 1

---

# slide 2

```

Should work as expected.

**Comment by mixmix** [comment]
@jackycute it probably does, but I don't want to include optional yaml setup - that's way more technical that most of my colleagues. 

So if we just know markdown, and we want to think about 'slicing the page into slides, we add `---` AND we also have to put a `---` right at the top of the file... which is counter-intuitive if you're thinking in terms of slicing. 

Maybe a 'fix' could be with slides mode, we check if there's a `---` at the top of the file, and if there isn't, we add it, so that the user gets a more intuitive result... 

Does that make more sense ?

**Comment by jackycute** [comment]
It's ok if you don't want use that option.
Just DON'T use `----` (four dashes) to divide your slides (this will give you vertical slide and sub slide number).
Only use `---` (three dashes) and you will be fine (this is normal horizontal slide and normal slide number).
So actually, there is no need to add a extra `---` at the beginning of your slides.

Additionally, it's not possible if you want to use vertical slides having flattened slide number without extra option setup.

**Comment by jackycute** [comment]
@mixmix How's going? Did above comment help?

**Comment by mixmix** [comment]
thanks for that @jackycute - yeah the `---` vs `----` was a surprise.
It does resolve my issue. I guess I'm used to horizontal rules in md being anything >=  three dashes.

Seems a little brittle, but seems outside th scope of hackmd. 
thanks for your clear support.
 
LOVE THIS PROJECT !  
keep up the awesome work    (ﾉ´ヮ´)ﾉ*:･ﾟ✧
