### ISSUE TITLE
feature request: TOC element

### ISSUE THREAD

**Issue by gonzaloserrano** [hackmdio/hackmd#154]
Hi,

I noticed that there is a Table Of Content (TOC) feature in form of a button on the bottom of the display page. When you click on it then pops an `<ul>` with the TOC content.

I'd love the TOC to be an element that you can insert in the document so i would for e.g put it just below the page title.

What do you think?

**Comment by jackycute** [comment]
Hi @gonzaloserrano 
We already have that feature but I didn't mention it in anywhere.
Use it like this `[TOC]`.

Will add to document soon.
Thanks for heads up.

**Comment by gonzaloserrano** [comment]
Awesomesauce!

**Comment by jackycute** [comment]
Added to document in 8124d6f2d66ca95a87419c1c78a2050e5deaaf4b

**Comment by RoyiAvital** [comment]
Any chance to customize it?

One feature which should be quite useful is choosing the header level to be included.
For instance `[TOC](2, 3, 4, 5)` means only headers of level `2, 3, 4, 5` will be included in the TOC.
