### ISSUE TITLE
support local filesystem for uploading images

### ISSUE THREAD

**Issue by cyberic99** [hackmdio/hackmd#156]
Using an external service is not always possible because of availability or privacy issues, and won't work for offline use.
It would be great to be able to upload images or files to the local filesystem, and embed them

**Comment by jackycute** [comment]
And should also support S3

**Comment by amlwwalker** [comment]
@jackycute  Any progress on s3?

**Comment by jackycute** [comment]
Not yet, we're focusing on user space for now.
I will list this issue to milestone.

**Comment by j6k4m8** [comment]
I'm also interested in this functionality, and would be happy to investigate implementing it. @jackycute, mind if we={ @jackycute @j6k4m8 @cyberic99 } use this comment-space to discuss best-practices for adding this to the codebase, or would you prefer gitter?

**Comment by jackycute** [comment]
@j6k4m8 It's totally ok to discuss develop related issue here. No worries.

**Comment by jackycute** [comment]
Supported in bd3d4958e43a8437e45113354059cf41dacda995
