### ISSUE TITLE
Need help for translation

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#157]
Since we support i18n, do anyone could help to translate the text to their language?
For the English texts, please refer to https://github.com/hackmdio/hackmd/blob/master/locales/en.json

And please tell me what's the language you using and what's your culture name.
See more here https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx

**Comment by Lapin0t** [comment]
Hey, I just made pull request #158 to support fr-FR.

**Comment by jackycute** [comment]
@a-r-g-v @193s Hello guys!
Would you like to help doing Japanese translation?
Much appreciated :smile:

**Comment by jackycute** [comment]
Could we have Korean translation?
If we have it, then CJK will all coverd.

**Comment by ivanorsolic** [comment]
Hey, I've just made a pull request (#193) for the Croatian translation. The language culture name for Croatian is hr-HR.

**Comment by bSzala** [comment]
I will add Polish translation

**Comment by Kietzmann** [comment]
Added Ukrainian translation
[link](https://github.com/hackmdio/hackmd/pull/197)

**Comment by paraschadha2052** [comment]
I will add Hindi translation.

**Comment by wolframtheta** [comment]
Can I translate it to Catalan?

**Comment by jackycute** [comment]
@wolframtheta Sure, just make a PR.

**Comment by wolframtheta** [comment]
@jackycute Do you grant me access to that repo?

**Comment by jackycute** [comment]
Actually, you need to fork this repo to you and send Pull Request back here.
The english text strings right here: https://github.com/hackmdio/hackmd/blob/master/locales/en.json
Please modify above file from your fork and make a PR and I will merge it.
Thanks!

**Comment by rafajaques** [comment]
Do you already have French? I can take this one.

**Comment by jackycute** [comment]
Hi @rafajaques !

We already have French (fr-FR) from @Lapin0t,
https://github.com/hackmdio/hackmd/blob/master/locales/fr.json
You could review it and make it better or if you have another French culture variety will also be taken.

Thanks for your attention!
