### ISSUE TITLE
Persistent connection problem

### ISSUE THREAD

**Issue by Em-Ant** [hackmdio/hackmd#160]
In the last two days the documents keep switching between connected and disconnected state. Editing documents is almost impossible. It's not a local problem. The same issue occurs to people which I'm collaborating with, across different countries.

I'm on Ubuntu 14.04LTS, the problem occurs with bot the latest Firefox and Chrome.

Thanks.

**Comment by jackycute** [comment]
Hey @Em-Ant 
Sorry about that, I made a bug in the production site and that cause this issue.
It's been fixed and cache also have been purged.
Please refresh the page and everything should be fine.

**Comment by Em-Ant** [comment]
sorry, but it worked for a while, then now is intermitting again

**Comment by jackycute** [comment]
huh, please wait for few hours, or maybe clean your cache and try again?
if this persist, I need you to open up the DevTools console to see what error you've got.

Thanks for your patience.
