### ISSUE TITLE
Dropbox Export Broken?

### ISSUE THREAD

**Issue by benbernard** [hackmdio/hackmd#161]
On all the notes I've made, I'm unable to export to dropbox.  I get the pop up from dropbox and pick a location and save, but the file never shows up, either in the Dropbox web interface or on my filesystem.

Thoughts?

Here is an example note that experiences the problem, but as I said, all notes have the same problem for me.

https://hackmd.io/OwZgTAnAjCEGwFoAcBjOUEBYCsKCGCeSmApghESCFHCHJnAEZA==#

Same thing is also affecting my coworker

**Comment by jackycute** [comment]
Hi @benbernard 
This happen because our server now is behind cloudflare and it is preventing POODLE attack (disable some SSL version).
And Dropbox server use inproper way to download our resource.

Let me see if there is any solution.
Thanks for reporting.

**Comment by jackycute** [comment]
I already sent issue to Dropbox, wait for response for now.

**Comment by jackycute** [comment]
I just received the response from Dropbox.
They are seeking a fix for that and will inform me if there is any further progress.

**Comment by jackycute** [comment]
We just left cloudflare.
