### ISSUE TITLE
UX adjustments (layout, style, flows, syntax, anything related...)

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#164]
Dear all,
Since we first develop this tool only for ourself (I mean developers).
To adapt for more users (not only for developers), we would like to hear your voice.
What's the point that you don't feel intuitive, easily get confused or have bad experience.
Please tell us, we're trying to improve this part.

Thank you!

**Comment by ccc-larc** [comment]
兩點想法：

1. 我第一次用的時候，研究了一陣子才找到編輯按鈕。
2. 有時候分享連結給別人時，會希望對方點進來就是編輯模式。有時候則希望點進來是閱讀模式。(編輯模式連結、閱讀模式連結)

**Comment by jackycute** [comment]
Hi @ccc-larc, thanks for giving suggestions.

1. will try to move edit button to top right position (which is kind of convention).
2. will add the mode to the url and shareable.

:smile:

**Comment by rschiang** [comment]
Just adopted HackMD few days ago ( @andy0130tw might be more experienced to give suggestion), so here's my two cents:

#### 1. The editor view is far too wide for reading

[Material Design Guideline](https://material.google.com/style/typography.html) suggests that "if a line of text is too long, the user’s eye will have a hard time focusing on the text”, and recommended wrapping around 60 characters per line. This could be implemented by restricting `max-width` like what the view mode does.

#### 2. Style headings in editor mode

CodeMirror has an [example](https://codemirror.net/demo/variableheight.html) on this. It could be easier for non-engineers to adopt HackMD, as it reflects the heading level.

#### 3. Keybindings interfering with browser

The Command+L key (Ctrl+L on PC) is overridden among with several browser shortcut keys. This make it impossible to navigate to location bar by keyboard. 

#### 4. Title bar does not respect Dark mode

This could probably be an enchancement. :)

---

Thanks again to @jackycute who developed the awesome project. Hope this helps! ( ´ ▽ ` )ﾉ

**Comment by leo424y** [comment]
The fax icon is cute, but I think the publish icon is like http://j.mp/2bzyRUs  or http://j.mp/2bzyBFc Thanks for your hard working. I really love hackmd!

**Comment by jackycute** [comment]
Appendix for some suggestions from other source:

Comment area wanted and it should be easy to put their name on.
Also it need to have different style from original blockquote or it might get confused.

**Comment by jackycute** [comment]
Hi @rschiang 

1 and 2: Both make good point! The editor now is more like a code editor, so the width should as wide as possible. The better solution for these problems will be making a new editor mode (like zen mode) to blend edit/view together and that could keep the readability at same time (as you've mentioned the various line height). But as different people might use this tool, all above modes will preserve.

3: Huh, because the key binding for the Control+L and Ctrl+L are used in editing shortcuts (select whole line). But I will consider drop these shortcuts in zen mode (mention above).

4. Gray is my favorite color (actually because it looks clean & clear in both dark and light theme).

Thank you again, please keep in touch and we could make a better tool together!

**Comment by jackycute** [comment]
Changed some icons in 3840308ab6cbda7a9a9aa57f1700165e7c95d250
@leo424y

**Comment by Lapin0t** [comment]
There is a weird thing when editing long documents with several people: the editor doesn't center on the the user's cursor when he is not typing. This is especially annoying when you type on the last line and someone hits <return>.

**Comment by jackycute** [comment]
Hey @Lapin0t, good to see you here.
I heard several same feedback of this situation.
Will look deeper when I have moment.

Thanks!
