### ISSUE TITLE
Exclamation marks in french VS image tag

### ISSUE THREAD

**Issue by raphaelbastide** [hackmdio/hackmd#165]
In french, exclamation marks are preceded by a blank space ` ` on the web. When I write in french, each time I end a sentence with a `!` and hit `enter` to jump one or many lines, it opens an image tag. Maybe the way suggestion validation have to be reviewed? Maybe `down arrow` then `enter` instead of just `enter` could solve this an many other issue? What do you think?

**Comment by jackycute** [comment]
Hi @raphaelbastide 
Sorry never thought in french writing.

I get it, you mean don't auto focus on the first autocomplete item when it show up.
But that might against the convention.
How about validate with more text? For example, like `![` would be great.
In the mean while, it also require more understanding about markdown.

Thanks for report!

**Comment by jackycute** [comment]
Sorry for delaying this issue, I was kinda busy.
So the solution here is: you need two spaces before activate the image tag text complete if it's not the line beginning.
Hope this helps and the commit will push in these days.

**Comment by raphaelbastide** [comment]
Great! Thank.you.

**Comment by jackycute** [comment]
Fixed in 9b5856fff0e089ef97a2b2f60c1b3a94b01852f3
