### ISSUE TITLE
DATABASE_URL这个是什么格式

### ISSUE THREAD

**Issue by sguzwf** [hackmdio/hackmd#17]
➜  hackmd git:(master) ✗ bash run.sh
error:   Forever cannot find process with id: hackmd

DATABASE_URL='change this' \
MONGOLAB_URI='change this' \

这两个是什么格式？

**Comment by jackycute** [comment]
哎呀，居然沒解釋清楚
0.3.3之後會補上文件

以下範例
```
"DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/hackmd",
"MONGOLAB_URI": "mongodb://localhost/hackmd",
```

**Comment by jackycute** [comment]
測試

**Comment by sguzwf** [comment]
谢谢

**Comment by jackycute** [comment]
Closed by commit 54e48d10ff9b3f685a06f5963db552bd778adb7a
