### ISSUE TITLE
Support zen (full writing) mode

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#176]
Sometimes we just want to focus on writing and hope it looks easy to use (normal user friendly).
So maybe can build a mode or theme called "Zen" (禪), help users to immerse into the writing world.

It will only use font-size, few font colors (4-6) and font-style, font-weight to layout the markdown.
No code folding, no line number, no split preview (consider itself a result).

Feel free to comment any ideas!

**Comment by jackycute** [comment]
Refer some screenshots from StackEdit

![image](https://cloud.githubusercontent.com/assets/2639151/18899220/fe21b346-8569-11e6-9f8f-60c90ace1e68.png)

![image](https://cloud.githubusercontent.com/assets/2639151/18899222/0122763e-856a-11e6-8952-508464922b42.png)

![image](https://cloud.githubusercontent.com/assets/2639151/18899225/03d2098a-856a-11e6-90bb-6f050b764cff.png)

![image](https://cloud.githubusercontent.com/assets/2639151/18899227/067624e6-856a-11e6-9f4c-2030e27ff2d6.png)

**Comment by jackycute** [comment]
Update: remove autocomplete and add Medium-like popover toolbar.
And keep split view in order to preview diagram or charts.
refer to #4

**Comment by jackycute** [comment]
A thought that pressing some kind of key (or combination) in this mode will fade in preview.

**Comment by jackycute** [comment]
https://facebook.github.io/draft-js/

**Comment by almereyda** [comment]
https://github.com/ianstormtaylor/slate

**Comment by jackycute** [comment]
Thanks @almereyda!
Both looks great! And SimpleMDE might even integrate now.

**Comment by almereyda** [comment]
Cool, glad you appreciate the contributions.

**Comment by jackycute** [comment]
@almereyda Hey, don't get me wrong, I always appreciate the contributions.
But please do understand that it won't make a good project/product if it includes every kinds of features.
We have to make choices, to polish and refine to be a better one.

**Comment by SISheogorath** [comment]
We have a full screen mode and you can use the fullscreen mode of your browser. Both should provide the needed Zen to write :)
