### ISSUE TITLE
支援GIF圖貼上

### ISSUE THREAD

**Issue by et84121** [hackmdio/hackmd#177]
目前似乎只會取其中一張圖以png格式上傳

**Comment by jackycute** [comment]
I tried an confirm it is good to me.
Could you please attach your example image?

我這裡測試正常，可以請你給範例圖片嗎？

**Comment by jackycute** [comment]
You can't use the Chrome built-in context menu to "Copy image" feature, because it will only copy a frame of it.
Please use "Save as" to download that image to disk then upload to HackMD.

你不能直接用 Chrome 圖片的右鍵選單 "複製圖片"，那樣會只複製一張圖片
請是用 "另存圖片" 先將圖片下載下來，再上傳到 HackMD

**Comment by et84121** [comment]
OK 我了解了
感謝你的解說
