### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by LauraNK** [hackmdio/hackmd#180]
Hey!
I noticed a few grammatical errors in the README. If you'd like, I'd be happy to correct them and submit a PR.

There was one in the placeholder text of the editor as well ("Start by enter title here" might be better as "Start by entering a title here").

**Comment by jackycute** [comment]
Hi @LauraNK 
I mean sure, more than welcome to improve README or any docs.
Even the wording in the UI or placeholder are really free to contribute.
Make them as friendly as possible.
If you found anything you don't know how to change, comment below and I will help you.
Thanks!

**Comment by jackycute** [comment]
One more PR for Hacktoberfest !

**Comment by jackycute** [comment]
Thank you @LauraNK !
PR and issue are welcomed if you find anything in the future.
