### ISSUE TITLE
Connection lost when multiple client delete at same place at the same time

### ISSUE THREAD

**Issue by jason8399** [hackmdio/hackmd#181]
Hi All,
We found a bug that will cause connection lost.
When 2 or more clients delete at the same place at the same time the connection will lose.

Reproduce:
1. Make cursor of two clients at the same place.
2. Delete 2-3 characters at the same time.
And...Online switch to Offline.

Thanks!

**Comment by jackycute** [comment]
This will be fix soon.

**Comment by jackycute** [comment]
Fixed in a090008d4ae7eb69d0403b2dec43605bc981b19a
