### ISSUE TITLE
loginned user private doc.

### ISSUE THREAD

**Issue by halid** [hackmdio/hackmd#185]
Hi all,

I have a one question. I installed hackmd on my server. Private docs opened only owner person. But i want to can view and edit all loginned users.

is it possible?

**Comment by jackycute** [comment]
Hi @halid !
Please change the permission to "Editable" then it can be edit and view by all signed in users.

**Comment by jackycute** [comment]
@halid did above comment meet your need?

**Comment by jackycute** [comment]
reopen if you have other question.
