### ISSUE TITLE
Bug: editor is confused of underscores + non-alphanumeric in MathJax notation

### ISSUE THREAD

**Issue by BarclayII** [hackmdio/hackmd#186]
Editor will render the following MathJax notation
```
$x_{t-1}$
```
in a wrong way, where the part after the underscore (that is, `{t-1}$`) is displayed in italic.

The bug does not occur when the underscore is followed by alpha-numeric characters (a-z, A-Z, 0-9).  Also, the viewer treats this notation correctly.

**Comment by BarclayII** [comment]
The bug also occur when the underscore is preceded with a non-alphanumeric character.

**Comment by jackycute** [comment]
Hi @BarclayII !
I just tested what you said on above in https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html
It resulted same as in HackMD note.
Actually we use the official MathJax package to render any latex syntax.
Could you explain what's the expected output?

**Comment by BarclayII** [comment]
The output in the viewer is correct.  It's the *editor* that renders the text ugly.

See https://hackmd.io/EYQwLMBMAmAcBmBaADPAxtRYCMzaOGHgFMV4B2ANmgGYbZYbiwg=?both for a demonstration.

**Comment by jackycute** [comment]
Oh I see, hmmm this might not be easy to work with since we use CodeMirror here to highlight text in editor.
Need to open an issue there then.

**Comment by BarclayII** [comment]
It seems that CodeMirror itself does not support Markdown + MathJax officially:
https://github.com/codemirror/CodeMirror/issues/2942

**Comment by jackycute** [comment]
But I also see a patch in the issue you posted.
Let me try it.

**Comment by jackycute** [comment]
I tried that patch and it works.
But unfortunately it also affect other syntax like `$('div').html()` which in html tags or code blocks.
So need further research on how to do that correctly.

**Comment by jackycute** [comment]
That's be copy cat from https://github.com/Moeditor/Moeditor/commit/ce4c6cf552c2c3f81d6b0eff5a763e777cff6e54

**Comment by BarclayII** [comment]
Yes, I tried Moeditor and it worked as expected.

**Comment by jackycute** [comment]
Already fixed in official service.
Wait for commits to close this issue.

**Comment by jackycute** [comment]
Fixed in f6f469d0fe6082b046cf156a760324c53fcd72e5
