### ISSUE TITLE
Either choose PostgreSQL or MongoDB

### ISSUE THREAD

**Issue by bechtoldt** [hackmdio/hackmd#19]
First of all, thank you for open source this software!

I only have one issue with it: It uses two full-tiered databases. As far as I can see there is only one table in the PostgreSQL database. That looks like is a huge overhead. Could you please reduce the number of database systems to 1?
I plan to use hackmd for ad-hoc documentation running in a vagrant box. It would be great to reduce the footprint of hackmd in this box. :)

**Comment by jackycute** [comment]
Thanks for using!

Yes, I would like to reduce the database to only one.
But it takes some time to migrate two dbs.
As you can see, the PostgreSQL is only used for note saving.
And MongoDB is used on the other data.

Last, I would prefer PostgreSQL as far I can tell.

**Comment by amigrave** [comment]
> Last, I would prefer PostgreSQL as far as I can tell.

+1 for Postgres

**Comment by viderizer** [comment]
This is important and should be implemented soon in my opinion. Two full-fledged databases are just not needed and PostgreSQL should do the job.

**Comment by XVilka** [comment]
:+1: Since PostgreSQL has both BLOB and JSON data, no need for MongoDB here. See positive result of moving from MongoDB to PostgreSQL http://developer.olery.com/blog/goodbye-mongodb-hello-postgresql/

**Comment by jackycute** [comment]
Drop MongoDB and support PostgreSQL, MySQL, MariaDB, SQLite, MSSQL in version 0.4.0
