### ISSUE TITLE
Paid subscription of hackmd.io

### ISSUE THREAD

**Issue by qiuwch** [hackmdio/hackmd#199]
Hi

I really love hackmd and am thinking about moving all my notes to hackmd.io. But I sometimes notice the server is not stable and not reachable. As a developer, I know how expensive to maintain servers, etc. 

Do you consider providing a paid subscription to users? I am willing to pay about $5/month given the service is stable and reliable.

**Comment by jackycute** [comment]
Hi @qiuwch!
It's our honor to be praised by your words.

We currently running in low resources (both machine and human) and thus sometimes cause instability of server not been eliminated right away.
But we've put as much effort as we can to improve that, hope will be better now.

We do have a plan to provide paid subscription to users and that would announce before September of next year.

❤️

**Comment by jackycute** [comment]
reopen if you have any further question 😄

**Comment by qiuwch** [comment]
Thanks for quick reply. I just made a donation and hope it go through well.

I think current features are almost rich enough to be a competitor with any online editor in the market. I am a heavy user of note-taking solution. The online solutions I tried include, evernote, simplenote, stackedit, gist, onenote, icloud notes, sharelatex, google keep, google docs, dropbox paper, jekyll, wordpress. I can not say hackmd is the best for everyone, but it is certainly the best option for me. I might try to write a blog post comparing it with other solutions if I have time. Please keep it stable and secure, I believe it will be very popular and widely used.
