### ISSUE TITLE
loading css (for Chinese, on slide)

### ISSUE THREAD

**Issue by a-tsioh** [hackmdio/hackmd#203]
I'm trying hackmd on  slides I have to do, partly using Chinese script.

I have troubles with typography, such as titles being bold, which is considered a bad practice in Chinese typography.

Simply adding the css from https://cdnjs.com/libraries/Han yield a much better output, but I don't see how to add such css properly (I tried 'lang: zh' in the YAML but it didn't help). So I just tried with the debugging tools of my browsers.

Is there any way to add css in the markup ? or could han.css be loaded when lang=zh ?

thanks for this great tool !

**Comment by jackycute** [comment]
Hi @a-tsioh !
Though I use Chinese, I don't know that bold in title is a bad practice, good to know that.
External scripts and styles are not allow to add into note, but it's ok to write pure `<style>` inside.

Anyway, will definitely add that Han lib to our note & slide, seems eligible to Chinese and Japanese.
Thanks for caring about typography! Which makes web looks beautiful.

**Comment by a-tsioh** [comment]
when too bold, strokes end up  touching each others and characters becomes hard to read.
more details at https://css.hanzi.co/
(and kudos should go to @ethantw )
I gonna try with <style>, thanks !

**Comment by jackycute** [comment]
Based on this test page: http://ethantw.github.io/Han/latest/test.html
I think heading should still be bold style, because it didn't to overwrite it.
Or could you please indicate where it docs specifying the heading styles?

**Comment by jackycute** [comment]
Hey @a-tsioh please read above comment and tell us your opinion.

**Comment by a-tsioh** [comment]
Yes it seems fine with Ethan's CSS. 
I guess it's a matter of carefull font-family and font-weight selection.
Currently the rendering of <h1>點</h1>(for example) on Hackmd and with hancss are quite different. hancss allows for a better "bold-like" rendering. (at least on my Firefox)

**Comment by jackycute** [comment]
So basically this is a problem of font family.
Could you please tell me your OS, browsers version and a example please?
I still like to give a better experience on anything.

**Comment by a-tsioh** [comment]
Hi !
Here are screenshots to compare hackmd output with hancss  output on Firefox (on a Linux with plenty of fonts available)
When I try with Chrome, the headings are not bold, just larger.

https://hackmd.io/s/S1lY7Evzx#

In the css nothing seems to be said about chinese font families.

**Comment by jackycute** [comment]
OK, I will perform a test about the heading styles on Firefox in Ubuntu.

**Comment by jackycute** [comment]
It seems we need to specify some css styles for Firefox to prevent the heading gets too bold.

**Comment by jackycute** [comment]
After few inspection,
I found this related to Firefox default fallback for sans-serif font on preferences.
I'm not sure about what you're using, please check the steps here.
https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use

So it's more on the font that you chosen or the fallback font weight is too heavy on bold style.
Not what we should do any specific workaround, remove from milestone.

**Comment by jackycute** [comment]
Hey @a-tsioh did you see my comment?

**Comment by a-tsioh** [comment]
Sorry I didn't notice it !
Yes it does work when changing Firefox defaults. However if I want to change Firefox's language-specific defaults, Japanese seems to be the one detected for some reason...

**Comment by jackycute** [comment]
I think that must be your os or browser default language.

However you can specify your note lang by yaml-metadata like below:
```
---
lang: zh-tw
---
```
Put above code at the very beginning of your note.

**Comment by a-tsioh** [comment]
oh, now defaults seems better when playing with 'lang' values (closer too Chrome's output), and the font changes realtime when changing the value but I'm not quite sure about what valid language tags are interpreted by Firefox...

**Comment by jackycute** [comment]
It's here
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
http://www.w3schools.com/tags/ref_language_codes.asp

For chinese, I personally still prefer `zh-tw` and `zh-cn`.

**Comment by jackycute** [comment]
I going to close this issue.
You can reopen if you got any further questions.

**Comment by a-tsioh** [comment]
Sure ！ now it's only a matter of browser config .
Thanks !

**Comment by sagarmunjal** [comment]
external script loading allowed in hackmd?

**Comment by sagarmunjal** [comment]
can we embed codepen snippets in hackmd?

**Comment by SISheogorath** [comment]
You can embed them using the iframe method. In HackMD you currently can't embed scripts directly for security reasons.
