### ISSUE TITLE
Order list support multiple level

### ISSUE THREAD

**Issue by grapherd** [hackmdio/hackmd#209]
Order list now can only support 2 level, for example

```
5. A Concrete Design
5.1. Performance Objective
5.2. Architectureal Level
```

But can't support this

```
5. A Concrete Design
5.1. Performance Objective
5.2. Architectureal Level
5.2.1 System Calls
5.2.2 Messages
```

I think we can add this for another feature.

Thanks.

**Comment by jackycute** [comment]
Hi @grapherd !
Thanks for your idea, but we are following CommonMark here.
http://spec.commonmark.org/0.26/#ordered-list

I'm not sure if it's ok to support more than 2 level ordered list.
Maybe check the CommonMark forum
https://talk.commonmark.org/search?q=ordered%20list

**Comment by jackycute** [comment]
I found this can be achieved by CSS from here: http://stackoverflow.com/questions/4098195/can-ordered-list-produce-result-that-looks-like-1-1-1-2-1-3-instead-of-just-1
So below is the working example:
```
ordered list test
===

1. first
    1. asdasdf
    2. asd
2. second
3. third
4. fourth
5. fifth

<style>
ol {
  list-style-type: none;
  counter-reset: item;
  margin: 0;
  padding: 0;
}

ol > li {
  display: table;
  counter-increment: item;
  margin-bottom: 0.6em;
}

ol > li:before {
  content: counters(item, ".") ". ";
  display: table-cell;
  padding-right: 0.6em;    
}

li ol > li {
  margin: 0;
}

li ol > li:before {
  content: counters(item, ".") " ";
}
</style>
```
https://hackmd.io/KwQwLAjATAnAHAEwLQDMLGWBBmGSBGIE+SY2UCAbAMb5xQQCmIQA

**Comment by jackycute** [comment]
Reopen if above couldn't fulfill your need @grapherd

**Comment by Wolvereness** [comment]
@jackycute Can this be reopened? The provided example appears to be completely non-functioning, apparently due to the &gt; symbol being escaped in the css.

**Comment by jackycute** [comment]
@Wolvereness thanks for reporting.
but seems the > symbol been escaped in CSS is another issue (caused by security fix).
So please raise another issue, we'd love to fix that.
