### ISSUE TITLE
Setup Problems

### ISSUE THREAD

**Issue by janniklorenz** [hackmdio/hackmd#21]
I tried to set up a development instance yesterday, and I can't get it running. The redirect form /new to /:id works, then the page loads and stucks with the loading indicator. I think it could be a socket.io problem, but I haven't debugged it further (no client JS errors are shown).

Are your familiar with this issue or have an advice?

**Comment by jackycute** [comment]
hmm, did you see the logs?
and setup the configs right?

and I might build up a vagrant box or docker for deploy in few days

**Comment by janniklorenz** [comment]
I could not find any errors on the server side.

testport: 3000, 
domain: "localhost",
mongodbstring & postgresqlstring

I did not set any auth key like Facebook etc, could that be a reason?

Yes vagrant would be very useful.

**Comment by jackycute** [comment]
Can you go the page you stuck in, and open the console.
Take a screenshot for me (do not crop), and I might able to debug.
Thx.

**Comment by jackycute** [comment]
Hey, you might want to check this out:
https://github.com/greyia/docker-hackmd

**Comment by janniklorenz** [comment]
Thanks for this link, it helped me to debug this issue. I still wasn't able to fix it on my machine (OS X 10.11, node 0.10/ 4.0.0), but now I have a running instance to test.

On which operating system do you develop?

I found this `libkrb5-dev` package, which get's installed on the docker image, and probably is responsible for my issue on OS X. If I remove it on the docker machine, I get the same problems.

`libkrb5-dev` is probably used by a dependency of `connect-mongo`:
```
+-- connect-mongo@0.8.2 
| `-- mongodb@2.0.43 
| +-- es6-promise@2.1.1 
| +-- mongodb-core@1.2.12 
| | `-- kerberos@0.0.14 
```

**Comment by jackycute** [comment]
I'm using OS X 10.10.5, node 0.12.7 to develop.

But I found I forget something in the README.md.
You should type `npm install` in the clone directory before running the server, that will install all the dependencies.
I hope this will solve your problem.

**Comment by amigrave** [comment]
I have exactly the same issue on Linux ubuntu 14.04 (node 0.12.7).
When clicking on the new note button, I have the interface loaded but the spinner is spinning forever.
No errors are shown in the browser's console neither in the server's terminal.
The default note has successfully been recorded in the database and I can see it in a new tab if I click "Publish"

```
$ dpkg -l 'libkrb5*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
pi  libkrb5-26-heimdal:amd64    1.6~git20131207+df amd64              Heimdal Kerberos - libraries
pi  libkrb5-3:amd64             1.12+dfsg-2ubuntu5 amd64              MIT Kerberos runtime libraries
un  libkrb5-dev                 <none>             <none>             (no description available)
pi  libkrb5support0:amd64       1.12+dfsg-2ubuntu5 amd64              MIT Kerberos runtime libraries - Support library
```

So I installed `libkrb5-dev` but it didn't helped.


I just tried to to install hackmd on OSX (node 0.12.4) but `npm install` ends with this in the tail of `npm-debug,log`:

```
160 error Darwin 14.4.0
161 error argv "node" "/usr/local/bin/npm" "install" "--verbose"
162 error node v0.12.4
163 error npm  v2.10.1
164 error code EPEERINVALID
165 error peerinvalid The package passport does not satisfy its siblings' peerDependencies requirements!
165 error peerinvalid Peer passport.socketio@3.6.1 wants passport@~0.3.0
166 verbose exit [ 1, true ]
```

**Comment by jackycute** [comment]
Thanks for above reports.
I will see what might happened.

And to avoid so mush environment instability, we made a docker repository.
https://github.com/hackmdio/docker-hackmd

It should be quite easy if you are using a UNIX-like OS.
Report to there if you got any problem.

Have fun!

**Comment by jackycute** [comment]
I've updated the dependency versions in 4e0f1577396eeae23ab2ed76da1422526b234712
Please try again in OSX, thx.

**Comment by amigrave** [comment]
Thanks !

I will try on OSX this evening.
Meanwhile, here's what I get under linux when activating socket.io logging in the browser: http://pastebin.com/YnxrfCi9

Seems like it fallback to polling. I tried with google chrome, chromium and firefox recent versions.

Does it ring a bell to you ?

**Comment by jackycute** [comment]
Unfortunately, it's not remind me any could help.
But you can try set debug option in the config.js on server-side.

**Comment by amigrave** [comment]
Please note that under Linux I changed `package.json` and set the version to `"*"` for all packages, then I removed `node_modules` and reinstalled, this solved the forever spinning bug.

I'll try to identify which pinned version package(s) was/were causing the trouble as soon as I can, so we can close this issue.

**Comment by jackycute** [comment]
Oh cool, that's really a good news.
I just can't figure out which part of my code can cause this.

Thank you.

**Comment by amigrave** [comment]
Ok, I finally found the culprit, it was `cookie-parser`.

**Comment by jackycute** [comment]
Many thanks!
Merge it right now, yeah!

**Comment by janniklorenz** [comment]
Thanks guys, this fixes it for me too.
