### ISSUE TITLE
Feature Proposal: turn [ ]  into check boxes

### ISSUE THREAD

**Issue by ccoenen** [hackmdio/hackmd#211]
This is a neat feature i know from hackpad. And GitHub. Bot turn `[ ]` and `[x]` into clickable check boxes, like this:

- [ ] I need to do this
- [x] Oh, heat, i already did this

I'd like to have something similar in hackmd.

**Comment by ccoenen** [comment]
nevermind. I just found out that you just need to prefix them with a dash (like in lists).

**Comment by jackycute** [comment]
Yes it is. Also it's checkable from the view side. ㊙️
