### ISSUE TITLE
清單項目下的 syntax highlighting / syntax highlighting under list items

### ISSUE THREAD

**Issue by tri613** [hackmdio/hackmd#215]
Hi, 

如果我想要在某個清單項目下面加上 code block，
它會失去syntax highlighting的功能，
想請問這樣子是正常的嗎？(還是其實沒有人在這樣用XD) 謝謝~

(截圖是從 hackmd playground 上面截下來的!)

![2016-10-17_18-14-04](https://cloud.githubusercontent.com/assets/10163715/19434006/b87d5a3a-9495-11e6-8f39-6404151dbfe8.png)

**Comment by jackycute** [comment]
嗨！ @tri613 
這算是一個小小的 parser issue
請將 code block 縮排改用 spaces 取代 tabs，這樣就正常了

從 550746b70edb13fdd6eafecfe48af5c5b57db2ee 之後，編輯器預設縮排都改用 spaces
https://github.com/mivok/markdownlint/blob/master/docs/RULES.md
也有 rules 是 使用 spaces 而非 tabs 縮排 (雖然 parser 可以運作)

**Comment by tri613** [comment]
嗨！謝謝答覆，不過我改用了4個spaces以後還是沒有syntax highlighting耶，是我哪裡誤會了嗎？

<img width="1279" alt="2016-10-17 11 31 35" src="https://cloud.githubusercontent.com/assets/10163715/19444176/f8328548-94c1-11e6-8370-7827817dbfb7.png">

**Comment by jackycute** [comment]
你 list item 上面是不是還有東西，請多空一行再列清單
Markdown 語法來說的話，請把不同區塊用空行區分

**Comment by tri613** [comment]
原本是有的，現在我把它拿掉，還是沒有改變耶...

<img width="1280" alt="2016-10-18 12 13 49" src="https://cloud.githubusercontent.com/assets/10163715/19445659/da6c3bf2-94c7-11e6-948a-f11f0ab4cb94.png">

然後這邊是我在 playground 上試的地方：
https://hackmd.io/CwDgDAZgTFCcCmBaAhvAJgVkceA2AzIgEYDGIJiIGIU8GYRYJA7PkA==?both#syntax-highlight

真是不好意思，再麻煩了QQ

**Comment by jackycute** [comment]
阿，原來你是說這個，剛剛我看你使用 Playground 也發現了 (我一直看錯地方QQ)
這個剛剛在 e311a1f6202d02e0bb869d8141b67ee04fec8ab4 被我修掉了
等等會推上伺服器

**Comment by jackycute** [comment]
@tri613 
真是不好意思，這個問題單純就是有 bug 而已，跟語法沒有太大關係
目前已經上線了，請您重新整理頁面就正常了！

😄

**Comment by tri613** [comment]
已經可以正常運作了！謝謝，辛苦了~~~:laughing:
