### ISSUE TITLE
Emoji inside parens are not working

### ISSUE THREAD

**Issue by revolter** [hackmdio/hackmd#217]
Having `(:smile:)` [does not render it as an emoji][1], but `( :smile:)` works. Are you parsing it manually or using a Markdown parsed library?

  [1]: https://hackmd.io/KwNgZgzAnAHALARgLQCYAMwDGS5oKYpIzAphIBGAJiGmjDGGlCgOxA==

**Comment by jackycute** [comment]
We use [emojify.js](https://github.com/Ranks/emojify.js) to render emoji after the markdown rendering.
Seems like the emoji don't work with parens surrounded is because this `:)` kind of emoticons are not supported.

Maybe https://github.com/markdown-it/markdown-it-emoji handle this better.

**Comment by jackycute** [comment]
I tried markdown-it-emoji, it handle emoji better.
Will replace emojify.js to it.

**Comment by revolter** [comment]
Well, knowing  that `( :smile:)` works, where there is `:)`, I don't think that's the problem. That problem would be if `(:smile: )` worked.

**Comment by revolter** [comment]
Ok, let me know when it's live in order to test this again and close the issue.

**Comment by jackycute** [comment]
It's now up and running, please refresh and check 😄

**Comment by revolter** [comment]
Yep, works like a charm, thanks a bunch!

**Comment by revolter** [comment]
Hmm, did it have autocompletion? Also, `:rolling_eyes:` doesn't work :(

**Comment by jackycute** [comment]
OK, will try to support more emojis and support textcomplete in parens.
