### ISSUE TITLE
External Server Requests

### ISSUE THREAD

**Issue by ccoenen** [hackmdio/hackmd#219]
Right now, If I request one of the pads from my own installation, there's three things that get downloaded from somewhere else:
- A CSS from fonts.googleapis.com
- A font from fonts.gstatic.com (Source Sans Pro)
- A JavaScript from cdn.mathjax.org

I would like to propose adding them to the repository (where allowed by the licenses) or disabling them via an option.

**Comment by jackycute** [comment]
Hey @ccoenen !

I understand your need and already know about the google font but wondering about the mathjax.
Will check that out later.

Thanks for heads up 😄

**Comment by jackycute** [comment]
There is a extra JS from cdn.mathjax.org that is `accessibility-menu.js` which just an enhancement of mathjax, so it doesn't really matter.

I think this issue solved after efd62bd1ca5550080ccf1254ecb95c5cb6afd983 and #243 
Reopen if you found anything else 😄

**Comment by ccoenen** [comment]
@jackycute testing 0.4.6 release right now, I can configure `usecdn` to be false. That works great for everything except the mathcdn-`accessibility-menu.js`. Is there any way to get rid of that one, too? Otherwise it looks awesome.

**Comment by jackycute** [comment]
I tried to find out how to include that in our packing.
But it turned out that MathJax haven't support webpack.
https://github.com/mathjax/MathJax/issues/1629

So we can only turn off accessibility option to shut it up.
But actually MathJax still working even fail to load that file.
