### ISSUE TITLE
警告區塊自訂色彩 / Custom alert area color

### ISSUE THREAD

**Issue by bestpika** [hackmdio/hackmd#221]
目前 HackMD 在引用區塊可以自訂色彩
想請問警告區塊是不是也能夠增加自訂色彩的功能

謝謝

---

Currently HackMD could customize blockquote color.
Could alert area be able to custom its color, too?

Thanks.

**Comment by jackycute** [comment]
Hi @bestpika !
I'm not pretty sure about this.
We already support `sucess`, `info`, `warning`, `danger` these four color styles.
Might need to ask if any other people need this.

**Comment by ccoenen** [comment]
You can always add your own HTML-Code, too!

So this should give you a very customized box:

```
<div style="background-color: fuchsia; color: lime; border: 2px solid red; border-radius: 3px; padding: 5px; ">
    I hope this is a very important message
</div>
```

(sorry for the colours 😄)

**Comment by bestpika** [comment]
Sounds good.

**Comment by Yukaii** [comment]
Repen it if anyone needed 😄 , close this.
