### ISSUE TITLE
字型替換擴充

### ISSUE THREAD

**Issue by bestpika** [hackmdio/hackmd#223]
希望可以增加以下的字型替換
(還是說其實這幾個已經有了只是我不會 key?)

運算符號
≒
≦
≧
≠

分數
½...etc

雖然分數可以用類似
^1^/~2~ 的方式輸入，可是總覺得哪裡怪怪的...

**Comment by jackycute** [comment]
嗨！
你這裡打得出來，應該就可以直接使用
那些符號我也不知道怎麼輸入，而且他們會因為系統與瀏覽器甚至字型不同而可能無法顯示
https://en.wikipedia.org/wiki/List_of_mathematical_symbols

但是你可以使用 MathJax 來表達這些符號，就沒有這些疑慮
https://www.mathjax.org/

**Comment by bestpika** [comment]
其實前面我只是希望像 +- 一樣會自動轉換而已
ex. := -> ≒ 之類的

**Comment by jackycute** [comment]
這個被稱作 Typographic replacements
目前是由我們所使用的渲染器 markdown-it 所提供，只能算是一個便利的用法，並沒有在規範裡面
https://github.com/markdown-it/markdown-it/blob/e6f19eab4204122e85e4a342e0c1c8486ff40c2d/lib/rules_core/replacements.js
所以如果想要其他的轉換，可以到他那邊開 issue

謝謝！

**Comment by jackycute** [comment]
說來這樣的自動轉換，不知道會不會給不想這樣使用的人麻煩
因為目前看它的實作是沒辦法在語法中使用跳脫來避免自動轉換
這樣會需要提供選項把這項自動轉換功能關閉

**Comment by bestpika** [comment]
原來是掛那個的，那我過去那邊看看
謝謝
