### ISSUE TITLE
Hackmd files and folders as authority for derived code and descriptions

### ISSUE THREAD

**Issue by jessmillar** [hackmdio/hackmd#227]
As one concrete request (which may exist already ... have just used Hackmd for a couple days so far): would be great if teams could get hackmd subdomains/subsubdomains so that we could organize stuff in tree-like fashion?

My team is experimenting, with the help of EJ Alexandra (eejai42) and his soon-to-be-released initial codieverse with taking collaborative notes while brainstorming and designing, and turning them into structured authoritative information  capturing underlying language and axioms (in a model-theoretic sense. along the lines of what domain driven design folks focus on in bounded contexts) that creates SDKs and derived code that inherits those models - and thus can be changed at a high level in the original descriptions in a way that flows through SDKs, code, wiki's etc.

EJ has initially set us up  using google docs and gsheets. But we want to use collaborative markdown. 
Max - I've just invited you to a repo at VCharge to explore what I mean by this request. Feel free to close this issue until it turns into something more concrete.

**Comment by jackycute** [comment]
Hi @jessmillar ,
Thank you guys invite me to your org.
I would like to help you but I'll be very busy in the next 2 weeks.
So keep in touch.

**Comment by jackycute** [comment]
Let's turn to email.
