### ISSUE TITLE
Python's Syntax Highlight doesn't work

### ISSUE THREAD

**Issue by aweimeow** [hackmdio/hackmd#228]
Hello, 

When I wrote code block in hackmd, and use ```python
but I paste code in code block, syntax highlight doesn't appear.

![_001](https://cloud.githubusercontent.com/assets/5120010/19623782/99f3418a-990c-11e6-80de-defb3c84d6f7.png)

This snapshot contains 2 code blocks, the first code block is what I paste code directly into it, and second code block is I trying key-in code by myself.

I couldn't figure out what happened, do you have any ideas ?

Thank you :)

**Comment by jackycute** [comment]
Hi @aweimeow ,
That's weird, would you might to refresh your page and see if it's fixed?
If this issue persist, please give me an example note which contains above code blocks.

**Comment by aweimeow** [comment]
@jackycute 
I tried refresh page, but it doesn't fixed.
and [this page](https://hackmd.io/s/ry9yLoFJg) is the example page contains this issue.

Thanks !

**Comment by jackycute** [comment]
OK, I found the problem is that some syntax in the block break the highlighting.
If you remove the `class` keyword and everything will be fine.
Let me check who made that issue.

```python
>>> import numpy as np
>>> x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
>>> type(x)
<class 'numpy.ndarray'>
>>> x.shape
(2, 3)
>>> x.dtype
dtype('int32')
```

**Comment by aweimeow** [comment]
Wow, that is why issue happened, 
I thought it is because in Python's semantics, begin with class will always end by colon (:)

Thank you :+1:
