### ISSUE TITLE
Error - Deploy Heroku

### ISSUE THREAD

**Issue by gladson** [hackmdio/hackmd#233]
-----> Node.js app detected

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NPM_CONFIG_PRODUCTION=true

       NODE_ENV=production

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  >=4.x

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version >=4.x via semver.io...

       Downloading and installing node 5.11.1...

       Using default npm version: 3.8.6

-----> Restoring cache

       Skipping cache restore (new runtime signature)

-----> Building dependencies

       Installing node modules (package.json)

       

       > typechecker@2.0.8 preinstall /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/.staging/typechecker-7d0a7029

       > node ./cyclic.js

       

       

       > typechecker@2.0.8 preinstall /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/.staging/typechecker-7c46d261

       > node ./cyclic.js

       

       

       > bufferutil@1.2.1 install /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/bufferutil

       > node-gyp rebuild

       

       make: Entering directory `/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/bufferutil/build'

       CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

       SOLINK_MODULE(target) Release/obj.target/bufferutil.node

       COPY Release/bufferutil.node

       make: Leaving directory `/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/bufferutil/build'

       

       > utf-8-validate@1.2.1 install /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/utf-8-validate

       > node-gyp rebuild

       

       make: Entering directory `/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/utf-8-validate/build'

       CXX(target) Release/obj.target/validation/src/validation.o

       SOLINK_MODULE(target) Release/obj.target/validation.node

       COPY Release/validation.node

       make: Leaving directory `/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/utf-8-validate/build'

       

       > phantomjs-prebuilt@2.1.13 install /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/phantomjs-prebuilt

       > node install.js

       

       PhantomJS not found on PATH

       Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2

       Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

       Receiving...

       

       Received 22866K total.

       Extracting tar contents (via spawned process)

       Removing /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/phantomjs-prebuilt/lib/phantom

       Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1477286596620/phantomjs-2.1.1-linux-x86_64 -> /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/phantomjs-prebuilt/lib/phantom

       Writing location.js file

       Done. Phantomjs binary available at /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

       

       > sqlite3@3.1.6 install /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/sqlite3

       > node-pre-gyp install --fallback-to-build

       

       [sqlite3] Success: "/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node" is installed via remote

       

       > hackmd@0.4.5 postinstall /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161

       > bin/heroku

       

       

       > hackmd@0.4.5 postinstall /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161

       > bin/heroku

       

       

       > hackmd@0.4.5 assets:install /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161

       > bower install

       

       sh: 1: bower: not found

       

       npm ERR! Linux 3.13.0-100-generic

       npm ERR! argv "/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/.heroku/node/bin/node" "/tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/.heroku/node/bin/npm" "run" "assets:install"

       npm ERR! node v5.11.1

       npm ERR! npm  v3.8.6

       npm ERR! file sh

       npm ERR! code ELIFECYCLE

       npm ERR! errno ENOENT

       npm ERR! syscall spawn

       npm ERR! hackmd@0.4.5 assets:install: `bower install`

       npm ERR! spawn ENOENT

       npm ERR!

       npm ERR! Failed at the hackmd@0.4.5 assets:install script 'bower install'.

       npm ERR! Make sure you have the latest version of node.js and npm installed.

       npm ERR! If you do, this is most likely a problem with the hackmd package,

       npm ERR! not with npm itself.

       npm ERR! Tell the author that this fails on your system:

       npm ERR!     bower install

       npm ERR! You can get information on how to open an issue for this project with:

       npm ERR!     npm bugs hackmd

       npm ERR! Or if that isn't available, you can get their info via:

       npm ERR!     npm owner ls hackmd

       npm ERR! There is likely additional logging output above.

       

       npm ERR! Please include the following file with any support request:

       npm ERR!     /tmp/build_cf36c3f128894be5c2469c37fc7c062f/hackmdio-hackmd-9710161/npm-debug.log

       

       

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Dangerous semver range (>) in engines.node

       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       - Bower may not be tracked in package.json

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies

       Love,

       Heroku

 !     Push rejected, failed to compile Node.js app.

 !     Push failed

**Comment by Yukaii** [comment]
Hi @gladson, we should keep `NPM_CONFIG_PRODUCTION` value to be `false`, because this makes  build tools in `devDependencies`(webpack, bower) be installed on heroku machine.

We missed some explanation about these variables, thank you for pointing it out!

**Comment by jackycute** [comment]
@gladson could you please try above comment solution?

**Comment by gladson** [comment]
Thanks, problem solved!
:smile:
