### ISSUE TITLE
Client for Desktop

### ISSUE THREAD

**Issue by chuchuhao** [hackmdio/hackmd#235]
Hi, is there any desktop client? if not, I would like to raise one :P

**Comment by jackycute** [comment]
Hi @chuchuhao,
We don't have extra resources to dev and maintain desktop version for now.
But we have an issue there #31 , it would be awesome if you like to help!

**Comment by ccoenen** [comment]
@chuchuhao Could you describe what a desktop client would do different from the browser-version?

**Comment by SISheogorath** [comment]
As an alternative to a real desktop version it's possible to run HackMD using docker on a local maschine.

clone https://github.com/hackmdio/docker-hackmd and use `docker-compose up`.

Works very nice. It's not the same as a real local version but for offline work it's okay. In case you want to avoid to run a postgres instance on the local machine you can also edit the config to run with sqlite.

**Comment by jackycute** [comment]
Please refer to #31
