### ISSUE TITLE
expand error

### ISSUE THREAD

**Issue by rogermylife** [hackmdio/hackmd#236]
https://hackmd.io/s/SyozI06Jl

這是我的清單

在點選"冰"的時候

無法正常expand出兩個子項目

點選expand all 正常

**Comment by jackycute** [comment]
嗨 @rogermylife 
"冰" 沒有辦法顯示出來，是因為剛好遇到網頁底端
所以會直接 expand 最後一項
是正常的行為喔 XD

**Comment by rogermylife** [comment]
嗨嗨 您好：

喔喔 好唷xD

雖然有點超出預期，不過是正常的就好~

謝謝！

2016年10月26日 下午3:56，"Max Wu" <notifications@github.com>寫道：

**Comment by jackycute** [comment]
摁摁
因為其實目錄的標記是看捲動進度決定
所以當捲到頁尾如果有同時有很多標題
就只能標起最後一項了

**Comment by jackycute** [comment]
reopen if needed.
