### ISSUE TITLE
Disable guest notes / require authentication

### ISSUE THREAD

**Issue by FlorianRhiem** [hackmdio/hackmd#237]
Hi,
is there a way to disable guest notes and remove the 'Freely' permission? Basically, I want to require user authentication for any persistent editting, as the anonymous access seems like something that could be abused.
Thank you!

**Comment by jackycute** [comment]
Hi @FlorianRhiem,
There is no way to disable guest notes and prohibit "freely" permission.
But this makes a good point, so will make a "allowanonmyous" options for this occasion.

Thanks!

**Comment by Joe136** [comment]
> prohibit "freely" permission
It would be nice to have an user administration, meaning only the admin can manage the users
- create new users; this can include the social-auth methods (e.g. confirm account). 
- delete users
- block users (only disable login)

I need these abilities to setup an self-hosted instance for a closed group of users.

**Comment by jackycute** [comment]
Hi @Joe136,
Please open another new issue for your requests, it's not directly related to this issue.
We currently are not focusing on enhance administration abilities.
So PRs are welcomed 😄

**Comment by neopostmodern** [comment]
Is someone working on this atm? @jackycute?

We can't adopt this with guest accounts enabled so - if I find the time - I'd try to file a PR if nobody else is working on this yet.

**Comment by jackycute** [comment]
@neopostmodern Yes, I'm working on it.
This feature will ship with 0.4.6.
And we hoping to release 0.4.6 in next week.

**Comment by jackycute** [comment]
Supported in 124c175b0d5777717d718768d8e5045a458909d3
