### ISSUE TITLE
combination of HTML tag <details> and <summary>

### ISSUE THREAD

**Issue by porkallen** [hackmdio/hackmd#238]
The summary tag should be able to define the visible heading of details tag. However, it seems to be always shown "詳細資訊" with ignoring the setting from summary. For instance,
<details>
<summary>Open me</summary>
</details>

The "Open me" was ignored.

**Comment by jackycute** [comment]
@porkallen 
I don't even know there are details and summary tags there.
Seems a good way to fold some spoiler messages.

Thanks for reporting this.

Fixed in ba2bfa2188afe7518eb394af02499069f6d997fb
