### ISSUE TITLE
Authorship highlight

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#24]
Currently we support extra tags in blockquote and todo list.
But it should be done in other ways like encode.
like below:

```
    <!--meta(paragraph_by: ..., line_segment_by: [{foo: , bar: }])   -->
```

**Comment by jackycute** [comment]
How about this?
http://criticmarkup.com/
Seems very firm.

**Comment by jackycute** [comment]
Supported in a14e7953b5a2196eda001229d44ebb2e9c18fe7c

**Comment by RoyiAvital** [comment]
Do you mean there is a full support for [CriticMarkup](http://criticmarkup.com/)?

I'm looking for a way to have a workflow in HackMD with multiple writers.
Something like Track Changes in Word.
