### ISSUE TITLE
投影片輸出PDF排版錯誤 (Export slides to PDF)

### ISSUE THREAD

**Issue by hermanliang** [hackmdio/hackmd#240]
參考作法: https://github.com/hakimel/reveal.js/#pdf-export
使用 `?pdf-print` query string後，所有投影片會疊成一頁

錯誤輸出的狀況
> Presentation: https://hackmd.io/p/slide-example
> PDF Export會全部疊成一頁: https://hackmd.io/p/slide-example?print-pdf

正確的狀況應該是
> Presentation: http://artificer.jboss.org/slides/general/opensource-getting-involved.html
> PDF Export: http://artificer.jboss.org/slides/general/opensource-getting-involved.html?print-pdf

reveal.js的輸出範例: http://lab.hakim.se/reveal-js?print-pdf

> 有無可能整合 [DeckTape](https://github.com/astefanutti/decktape)，直接產生PDF檔案下載

**Comment by jackycute** [comment]
剛剛有試著解決這個問題，明天就會推 commit
DeckTape 一樣會花上伺服器資源來產生 pdf 
可能暫時請您使用 chrome 的 輸出 pdf 功能

謝謝！

**Comment by jackycute** [comment]
修正已經上線到伺服器，請您重新整理再試用看看
如果很希望要支援 DeckTape，請再幫忙開另個 issue

謝謝 @hermanliang 

Fixed in 70d2fa388ec2b035102c8a2218cdaab69f6babdb

**Comment by hermanliang** [comment]
雖然網頁的排版還是有點怪怪的，不過至少用Chrome輸出PDF時是正常的，Thanks!
支援DeckTape的Issue已開 #241

**Comment by jackycute** [comment]
列印頁面怪怪的是因為 reveal.js 這部分的修正還沒 release
http://lab.hakim.se/reveal-js/js/reveal.js 找 `pdf-page`
在 reveal.js 的 repo 上還沒有這段 code
