### ISSUE TITLE
執行./setup 開頭有錯

### ISSUE THREAD

**Issue by kay54068** [hackmdio/hackmd#247]
請問我執行 ./setup 開頭有以下錯誤，可以忽略嗎?

copy config files
cp: cannot stat 'config.json.example': No such file or directory
cp: cannot stat 'public/js/config.js.example': No such file or directory
cp: cannot stat '.sequelizerc.example': No such file or directory

**Comment by jackycute** [comment]
@kay54068 

這些錯誤不能忽略，那些步驟是在複製設定檔案
您應該是在錯誤的目錄執行這個 scipt
您應該要在外層執行 `bin/setup` 而非在 `bin` 裡面執行 `./setup`

謝謝！

**Comment by kay54068** [comment]
謝謝您的解說.. 

請問一下以下以下warning 可以忽略嗎?

npm WARN lifecycle hackmd@0.4.5~postinstall: cannot run in wd %s %s (wd=%s) hackmd@0.4.5 bin/heroku /home/tscfw/hackmd
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN grunt-contrib-jshint@1.0.0 requires a peer of grunt@>=0.4.0 but none was installed.

**Comment by jackycute** [comment]
這些是安裝相依的 packages 的 WARN
可以忽略沒關係

**Comment by kay54068** [comment]
謝謝您，已可以運作...
請問一下hackmd 內部有帳號管理系統嗎?
若要使用google / gitlab 登入 要如何設置呢?

**Comment by jackycute** [comment]
目前都是透過第三方登入，使用 email 登入請見 #36 
請仔細閱讀 README.md
然後按照 https://github.com/hackmdio/hackmd/blob/master/config.json.example
修改 `config.json` 加入 api key (要去相對應的服務平台申請)
就可以使用了 😄

**Comment by kay54068** [comment]
謝謝您，
使用 email 登入，我不太會操作，請問您方便用 step by step 說明嗎??

**Comment by jackycute** [comment]
我的意思是 email 與本機登入功能還在開發中，請追蹤 #36 的進度

**Comment by kay54068** [comment]
了解，希望能有local login 的功能，謝謝您~

剛剛google 有看到相關的範例...

http://mherman.org/blog/2013/11/11/user-authentication-with-passport-dot-js/#.WCVnYS197IU

**Comment by kay54068** [comment]
請問一下hackmd如何使用發表以及簡報模式 (我開啟都是blank web page)??

**Comment by jackycute** [comment]
就按下發表或是簡報模式，如果是空白頁就是您有設定不正確的地方
您可以開啟瀏覽器 DevTools 來看網頁有什麼錯誤訊息，然後貼上來

**Comment by jackycute** [comment]
@kay54068 請問有看到上面的留言嗎?

**Comment by jackycute** [comment]
如果還有其他問題請再 Reopen 這個 issue
