### ISSUE TITLE
Loosen Imgur dependency / plug-ins

### ISSUE THREAD

**Issue by neopostmodern** [hackmdio/hackmd#253]
We're considering to use this project at our art school but we're reluctant to depend on external service providers / storying anything on anybody else's server.

I've seen that the upload code is server-side ([app.js#L407](https://github.com/hackmdio/hackmd/blob/master/app.js#L407)) and wondered if it would be possible to make this either
- configurable
- or plug-in based (and still configured)

to enable other upload targets (such as local FS or - for other use cases - the usual S3 etc)

This would make it much easier for custom deploys to keep up with the upstream version. I haven't seen a generic plug-in system yet, is that on the roadmap or do you have a different approach? 

Now that I think of it, plug-ins for oAuth would be sweet too.

**Comment by Yukaii** [comment]
@neopostmodern 

We're working on filesystem/s3 Image uploading now. You can track this in PR #248  😸  

related issue: #156

**Comment by neopostmodern** [comment]
That's great to hear! Couldn't find those issues before, sorry.

Any word about a general plugin-oriented architecture? Especially concerning oAuth?

**Comment by jackycute** [comment]
Hi @neopostmodern 
We use passport.js to auth users, so it's already a module and plug-in.

**Comment by jackycute** [comment]
Supported in bd3d4958e43a8437e45113354059cf41dacda995
