### ISSUE TITLE
Simple chat functionality

### ISSUE THREAD

**Issue by tomwyckhuys** [hackmdio/hackmd#254]
Hi!

It would be nice if you could chat with your contributors through a simple chat window.
I think it improves to collaboration process and it makes it a lot easier to discuss the document you're working on

Thank you for this amazing tool! I use it on a day to day basis now :+1: :+1: :+1: 

Kind regards

**Comment by jackycute** [comment]
Hey @tomwyckhuys 
I think chat or discuss definitely helps!
But this might a bit out of our focus right now.
We have a similar issue #6 

Thanks for choosing us 😃

**Comment by ccoenen** [comment]
I would vote to close this in favor of #6 - it's more or less the same feature request, and two open tickets will only make the discussion more complicated.

**Comment by jackycute** [comment]
duplicated #6
