### ISSUE TITLE
Cmd+L overwritten by codemirror

### ISSUE THREAD

**Issue by RichardLitt** [hackmdio/hackmd#255]
I use the `cmd+L` shortcut often; in Chrome on a Mac, it jumps to the address bar. This helps me swiftly copy the URL of the current page, so that I can share it with others. With HackMD, this command is overwritten, which breaks my workflow quite a bit and leaves me confused for a few seconds each time. 

I looked into codemirror to see if I could fix it, but I'm not sure where exactly it is being overridden in the code. Can someone help me patch this?

**Comment by jackycute** [comment]
Hi @RichardLitt 
The `Cmd-L` is overwritten for sublime `selectLine` keyMap.
I know few ppl like you need the shortcut to jump back to address bar.

So here is the patch:
Paste below code to the line after this line [index.js#L620](https://github.com/hackmdio/hackmd/blob/master/public/js/index.js#L620)
```js
delete CodeMirror.keyMap[keymap]["Cmd-L"];
```
Change the `Cmd-L` to `Ctrl-L` if you are on Windows.

**Comment by RichardLitt** [comment]
Thanks @jackycute. That's great to have it identified so quickly. 

Is there any chance that this could be integrated into the hackmd.io website version? I'm not running it locally, so I won't be able to edit the javascript meaningfully on my end.

**Comment by jackycute** [comment]
It's possible to make it as an option to it.
But it's more like a preferences to me.

You know if we enable this by default then other keymap won't work as default too.
So is that acceiptable that `keep address bar shortcut` being an option and default won't be enabled?

**Comment by RichardLitt** [comment]
It's a break from how most browsers work (just checked: it's the same for Safari and Firefox, at least on OSX). I'm not sure that is a preference. 

Is there a way to only rollback this overwrite, and not other keymaps?

**Comment by ccoenen** [comment]
It breaks <kbd>Ctrl+L</kbd> on windows, too. Just tested it in Firefox and Chrome.

I think, browser shortcuts should not be overwritten without a very good reason. <kbd>Ctrl+F</kbd> is another example, but at least it does more or less what you would expect from the browser's own search. "Select line" is not an important shortcut, for me at least.

**Comment by jackycute** [comment]
good points.
So maybe we make `Ctrl+L` can be overwritten as option instead.

Because the search from the browser can't search the content in the editor so we overwrite it.
But it you use `Ctrl+F` out of the focus of editor and it will trigger browser search function.

**Comment by RichardLitt** [comment]
> So maybe we make Ctrl+L can be overwritten as option instead.

This makes sense to me. I've seen a lot of websites override `CTRL+F`, so I am used to that. 

Are there any other overrides we should check before implementing a `Don't override Browser keymappings` option, or should we limit it to `CTRL+L`? I don't think so - given the huge amount of [keyboard shortcuts across browsers](http://dmcritchie.mvps.org/firefox/keyboard.htm), we can simply add options if other people raise issues. For now, I think implementing just `CTRL+L` should be fine.

**Comment by ccoenen** [comment]
Thanks for the focus-suggestion.

Nextcloud does an interesting thing, here: they override <kbd>Ctrl+F</kbd> as well, but if you hit it a _second_ time, you get the browsers actual search function. For <kbd>Ctrl+F</kbd>, this is a nice addition. For <kbd>Ctrl+L</kbd> it wouldn't make any sense (as the shortcut is designed to be called many times in a row to select many lines).

I know, I'm taking this a little off-topic here, but I think the underlying question "are browser shortcuts more important" is a very valid concern. As you pointed out, there's tons of them out there. Here's my personal list (yes, just my point of view, very open for discussion and not at all meant as a cookie cutter for every project) which I would not override:

* Ctrl+R -> reload
* Ctrl+T -> new tab
* Ctrl+Shift+T -> reopen closed tab
* Ctrl+N -> new window
* Ctrl+L -> focus address bar
* Backspace -> go back to the previous page, obviously only applies outside of text input/editor fields.
* Alt-left / Alt-right -> browser history, obviously only applies outside of text input/editor fields.

and here are some less used things that _I_ can totally live with if they are not browser default:
* Ctrl+D -> set bookmark, In general, use this often, but obviously only once per page at the most. I can live with having to click something that one time.
* Ctrl+S -> My compulsory "I need to save the file" finger hits this every once in a while, and i am actually **glad** that it does not bring up the browser's save dialog. :-)
* Ctrl+Tab -> Switch Tabs
* Ctrl+<number> Switch to tab <number>
* Ctrl+Shift+Del -> delete history, which I only use during development

Again: this is just a personal opinion and not meant as a "go and change this" request on my part. Your (anyone's) browser use is probably very different.

It should also be noted, that some browsers won't let you override all shortcuts. I think you can't override Ctrl+R in either firefox or chrome (I tried to do this once, and one of them worked and the other one did not, I can't remember which one).

**Comment by jackycute** [comment]
Added in da46a3696bfe4b7f7194888fbd9627514bbda3a4

Click the small wrench at the bottom right of the editor status bar to change preferences.
<img width="360" alt="2016-12-04 12 59 06" src="https://cloud.githubusercontent.com/assets/2639151/20860848/e82eed9c-b9bc-11e6-845a-b402b0b94688.png">

**Comment by RichardLitt** [comment]
Thank you @jackycute!
