### ISSUE TITLE
影片支援：從特定時間開始播放

### ISSUE THREAD

**Issue by JIElite** [hackmdio/hackmd#256]
您好，

目前嵌入 Youtube 影片的方式是利用 ID 的方式
在這種方式下，能夠讓他從特定秒數開始播放嗎？因為在使用說明沒有看到
一般不使用 ID 而是用 url 的話，可以利用&t=1m40s

謝謝！

**Comment by jackycute** [comment]
嗨 @JIElite 
其實現在有支援 iframe 語法喔！
可以試著直接從 youtube 貼過來，應該有用

**Comment by JIElite** [comment]
ok, 謝謝

like this:
`<iframe width="600" height="480"  src="https://www.youtube.com/embed/7PJE-K01MTg?start=200" frameborder="0" allowfullscreen></iframe>`

**Comment by jackycute** [comment]
Yes 就是這樣 👍 
如果你還有其他問題請再 Reopen issue
