### ISSUE TITLE
TOC shows css styling when using LaTeX in a subheader

### ISSUE THREAD

**Issue by tomwyckhuys** [hackmdio/hackmd#257]
When I generate a TOC while using a LaTeX expression in a subheader, the css of the header is shown in the TOC. A screenshot that I made:

![Screenshot](https://cloud.githubusercontent.com/assets/2878432/20541653/740cea84-b0fe-11e6-9899-c095531f6ac4.PNG)

Thanks for continuing this project!

Kind regards 👍

**Comment by jackycute** [comment]
@tomwyckhuys Thanks for heads up!

**Comment by jackycute** [comment]
Fixed in ead48e45e0977e6376640b89f842f238ab382f94
