### ISSUE TITLE
Suggestion: support TypeScript syntax highlight

### ISSUE THREAD

**Issue by twoeo** [hackmdio/hackmd#258]
TypeScript syntax is similar with JavaScript,
only need highlight  a few other keywords.

e.g `interface` `class` .

**Comment by jackycute** [comment]
Hi @twoeo 
It's not few other keywords that easy.
But for sure will support TypeScript syntax highlighting.

Thanks 😄

**Comment by jackycute** [comment]
Supported in de2067f7e898f3557323782d28e8f7530ffb539f
