### ISSUE TITLE
No account support for docker-compose version ?

### ISSUE THREAD

**Issue by twoeo** [hackmdio/hackmd#260]
Just deploy a hackmd from docker-compose (https://github.com/hackmdio/docker-hackmd)
 
It works, but seems can only create guest note, how can I enable user login ?

From docker-compose:
![](http://p1.bqimg.com/567571/9c28c7edb24f5bef.png)

Official site:
![](http://p1.bqimg.com/567571/87402adf5966b04f.png)

**Comment by twoeo** [comment]
Seems like need to set github client id...

**Comment by jackycute** [comment]
Please refer to docker-compose custom build here https://github.com/hackmdio/docker-hackmd#custom-build
