### ISSUE TITLE
HTML entities in drop down tag selector

### ISSUE THREAD

**Issue by Someniak** [hackmdio/hackmd#265]
It seems something is not rendered correctly in the dropdown menu.
This should display `Linux & Server security`, but now it renders this...

![image](https://cloud.githubusercontent.com/assets/9357656/20711038/d72c2cc6-b63d-11e6-88b4-390975b19c21.png)

**Comment by jackycute** [comment]
@Someniak Thanks for tell us this!

Fixed in 52772829ce8ccc7eac1fe1df9ace65d90ef36a2c
Official service will updated few hours later.
