### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by ccgshsiri** [hackmdio/hackmd#266]
各種可以登的管道都按了可是按下去就會一片空白

**Comment by jackycute** [comment]
我試試看

**Comment by jackycute** [comment]
我測試是正常的耶，伺服器目前也正常運作中
可以請你換瀏覽器或是電腦試試看嗎?

**Comment by ccgshsiri** [comment]
換瀏覽器就好了 謝謝你:)

2016-12-02 23:32 GMT+08:00 Max Wu <notifications@github.com>:
