### ISSUE TITLE
Page two of history - links are not working

### ISSUE THREAD

**Issue by tomwyckhuys** [hackmdio/hackmd#270]
Hi! 

I noticed that when I try to open a note that sits at page two of my history page, the links of the notes are converted to "#".  Also, the bottom tag fields are wrongly parsed.

screenshot:

![image](https://cloud.githubusercontent.com/assets/2878432/20965016/3fc1d3d0-bc74-11e6-94dc-bebaefd12aa3.png)

The link converted to "#":
![image](https://cloud.githubusercontent.com/assets/2878432/20965045/6613dd9e-bc74-11e6-999a-338c2d0ef5ae.png)

Thanks for continuing this cool thing! 😄

**Comment by jackycute** [comment]
This issue has been fixed in f5d471106c35f5ebb3aa28ccd73bd32dac6d79d9 and 07673f07262a3e742b06d886b23a2969a6abe58a
Please wait until next version release and upgrade your docker image.

**Comment by Someniak** [comment]
It seems this issue has not yet been resolved in the docker image? Could it be the docker repo is not up to data?
