### ISSUE TITLE
Automatic URLs

### ISSUE THREAD

**Issue by mihaipopescu** [hackmdio/hackmd#271]
Not sure if this is a known issue (or feature) but it seems like there is some kind of automatic url detection on the text and basically:

```
perlfile.pl
[perlfile.pl](http://perlfile.pl)
```
results in the same html code: [perlfile.pl](http://perlfile.pl)

when I expected a simple verbatim text `perlfile.pl`

**Comment by jackycute** [comment]
Hi @mihaipopescu,
This is a feature called `linkify`,https://github.com/markdown-it/linkify-it
You could wrap that text with <code>`</code> to make it as code.
