### ISSUE TITLE
path is not defined when I use local file system to store image

### ISSUE THREAD

**Issue by ccwinder** [hackmdio/hackmd#278]
Hi, Sir

I got the latest code from github today. But when I set up to store image to my local file system, 
I got an error message from console and there is no image path showed on the article.
```bash
2016-12-12T04:15:28.788Z - error:  ReferenceError: path is not defined
    at /home/hackmd/app.js:488:33
```

When I checked the app.js and I found that there is no `var path = require('path');` in the `app.js`.

Because I am not familiar with node.js, I don't know should I add `var path = require('path');` to the `app.js`.
Can you help to check it?

Thanks a lot!

**Comment by jackycute** [comment]
Hi @ccwinder 
Yeah, I missed to add that dependency in 5958654ea4d722cb6af6a170da94c0d5373015d2
Thanks for reporting this.
Fixd in bb3ed8e249ebf8b8c6801cb81610f127db40b580
