### ISSUE TITLE
Release issues on docker repo

### ISSUE THREAD

**Issue by Someniak** [hackmdio/hackmd#286]
Hey,
It seems like something is wrong with the docker image of hackmd.
@tomwyckhuys 

<img width="639" alt="screen shot 2016-12-19 at 14 39 41" src="https://cloud.githubusercontent.com/assets/9357656/21314818/5690fc1a-c5f9-11e6-982b-e19dfbd4996e.png">

**Comment by jackycute** [comment]
Not so hurry ready bro, I'm fixing it.
And please open issue there if it's not an issue here.

**Comment by Someniak** [comment]
Ow super 👍 
I posted the issue here because I'm not able to do it on the docker repo on github?

**Comment by jackycute** [comment]
@Someniak I think you can https://github.com/hackmdio/docker-hackmd
