### ISSUE TITLE
Apply style on email address will break email parsing/link

### ISSUE THREAD

**Issue by PeterDaveHello** [hackmdio/hackmd#288]
Style on email address will break the email parsing and then generate wrong link on the email, examples:

```
 - **peter**@peter.com
 - **peter**.rd@peter.com
 - peter**.rd**@peter.com
 - peter@**peter.com**
```

**Comment by ccoenen** [comment]
Id vote to close this unresolved. It's an edge-case that can be worked around quite easily with the long form of the links:

```
 - **peter**@peter.com -> [**peter**@peter.com](mailto:peter@peter.com)
 - **peter**.rd@peter.com -> [**peter**.rd@peter.com](mailto:peter.rd@peter.com)
 - peter**.rd**@peter.com -> no solution, see below
 - peter@**peter.com** -> [peter@**peter.com**](mailto:peter@peter.com)
```

The behaviour is also the same on Githubs Markdown (output of exactly the code above):

 - **peter**@peter.com -> [**peter**@peter.com](mailto:peter@peter.com)
 - **peter**.rd@peter.com -> [**peter**.rd@peter.com](mailto:peter.rd@peter.com)
 - peter**.rd**@peter.com -> no solution, see below
 - peter@**peter.com** -> [peter@**peter.com**](mailto:peter@peter.com)



a) I find this to be a rare case
b) finding and parsing this level of intertwined formatting address is a can of worms
c) there's a valid workaround that is unambiguous to parse and display
d) formatting within an email address is not part of the markdown standard
e) example three does not work at all with other examples as well:  (enclosed**.bold**text with a dot as first character)

**Comment by jackycute** [comment]
This definitely is a edge case and I don't think will be fixed in `markdown-it` because this is not in the spec.
Please avoid this kind of usage.
Thanks for testing @ccoenen
