### ISSUE TITLE
Cannot export .md file to dropbox

### ISSUE THREAD

**Issue by iotchef** [hackmdio/hackmd#290]
.md file cannot export to HackMD's default folder in Dropbox and there is no error message prompt.

**Comment by jackycute** [comment]
Hi @iotchef 
I just tried on our service, but it exported successfully.
Could you turn on your devtools and try again to see any error logs?
Also please provide your OS, browser version info.

**Comment by iotchef** [comment]
I just found there is already an issue submitted (#161). Sorry for bothering.

**Comment by jackycute** [comment]
Not at all.

We left cloudflare few weeks ago.
So actually it should be able to export to Dropbox.
Please try again.

**Comment by iotchef** [comment]
My browser is Firefox 50.1.0 and OS is Windows 7 profession edition.

**Comment by iotchef** [comment]
Here is the log when I click Export->Dropbox and select the folder and click Save

> GET https://www.dropbox.com/saver [HTTP/2.0 200 OK 410ms]
Content Security Policy: 忽略 script-src 或 style-src 當中的「'unsafe-inline'」: 指定了 nonce-source 或 hash-source  (未知)
Content Security Policy: 無法處理未知指示「worker-src」  (未知)
Content Security Policy: 指示「frame-src」已被棄用，請改用「child-src」。  (未知)
GET https://cfl.dropboxstatic.com/static/css/packaged/components-vflZL22EY.css [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/css/saver-vflW3HQF_.css [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/css/sprites/dropins_sprites-vflzBpCNG.css [HTTP/2.0 200 OK 0ms]
GET https://fonts.googleapis.com/css [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/require_bundle.min-vflmZrWxc.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/images/icons/icon_spacer-vflN3BYt2.gif [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/images/icons/ajax-loading-small-vfl3Wt7C_.gif [HTTP/2.0 200 OK 0ms]
GET https://dropbox.com/hstsping [HTTP/2.0 200 OK 0ms]
GET https://fonts.googleapis.com/css [HTTP/2.0 200 OK 0ms]
GET https://dropbox.com/hstsping [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/images/sprites/dropins_sprites-vflPeImb1.png [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/images/widgets/dropdown-arrow-vflkuszgw.png [HTTP/2.0 200 OK 0ms]
GET https://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2 [HTTP/2.0 200 OK 0ms]
GET https://fonts.gstatic.com/s/opensans/v13/MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5-oayXSOefg.woff2 [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/packaged/pkg-ab.min-vfleidZSA.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/packaged/pkg-am.min-vflx-7Hpi.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/tslib.min-vfl5j4I4k.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/packaged/pkg-aa.min-vfl9hgv1U.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/react-15.3.1-prod.min-vflMYPHbf.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/langpack/zh_TW.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/flux.min-vflUoCnE8.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/purify.min-vflkgrzs0.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/keymaster.min-vflLu22dA.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/rsvp-3.2.1.min-vflPwaXEC.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/sha1.min-vflnBGgMP.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/react-dom-15.3.1-prod.min-vflgUUIsY.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/classnames.min-vfl4ukfgw.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/jquery.min-vflPKFS8a.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/underscore.min-vflio7YxP.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/tracekit.min-vfllJSVmx.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/jquery_ui.min-vflnSF8u0.js [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/javascript/compiled/external/sjcl.min-vflRtcU5Z.js [HTTP/2.0 200 OK 0ms]
Content Security Policy: 頁面的設定阻擋了 self 的資源載入:（「script-src 'unsafe-eval' https://www.dropbox.com/static/javascript/ https://www.dropbox.com/static/api/ https://cfl.dropboxstatic.com/static/javascript/ https://www.dropboxstatic.com/static/javascript/ https://cfl.dropboxstatic.com/static/api/ https://www.dropboxstatic.com/static/api/  'nonce-HkxDv+oMH+un9UR8R3yN'」）。  saver
Content Security Policy: 頁面的設定阻擋了 self 的資源載入:（「script-src https: 'unsafe-eval'」）。  saver
GET https://cfl.dropboxstatic.com/static/css/react/breadcrumbs-vflF2qDrO.css [HTTP/2.0 200 OK 0ms]
GET https://cfl.dropboxstatic.com/static/images/favicon-vflk5FiAC.ico [HTTP/2.0 200 OK 0ms]
GET https://www.dropbox.com/static/images/icons/icon_spacer-vflN3BYt2.gif [HTTP/2.0 200 OK 0ms]
POST XHR https://www.dropbox.com/log/ux_analytics [HTTP/2.0 200 OK 255ms]
POST XHR https://www.dropbox.com/log/ux_analytics [HTTP/2.0 200 OK 240ms]
POST XHR https://www.dropbox.com/log/ux_analytics [HTTP/2.0 200 OK 252ms]
POST XHR https://www.dropbox.com/log/ux_analytics [HTTP/2.0 200 OK 236ms]
GET https://cfl.dropboxstatic.com/static/images/widgets/selected-folder-vflXa4Sw2.png [HTTP/2.0 200 OK 0ms]
POST XHR https://www.dropbox.com/dropins/browse [HTTP/2.0 200 OK 566ms]
POST XHR https://www.dropbox.com/dropins/browse [HTTP/2.0 200 OK 335ms]
POST XHR https://www.dropbox.com/log/ux_analytics [HTTP/2.0 200 OK 248ms]
POST XHR https://www.dropbox.com/dropins/browse [HTTP/2.0 200 OK 372ms]
POST XHR https://www.dropbox.com/dropins/save_url_batch [HTTP/2.0 200 OK 767ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 561ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 254ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 273ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 420ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 284ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 997ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 261ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 265ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 283ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 263ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 276ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 294ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 262ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 1155ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 289ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 289ms]
GET XHR https://www.dropbox.com/dropins/job_status [HTTP/2.0 200 OK 273ms]
...

**Comment by jackycute** [comment]
It seems like dropbox job workers unable to finish its job and keep polling.

**Comment by iotchef** [comment]
OK. I will try the export feature later. Thanks anyway. :)
