### ISSUE TITLE
Allowing one user only to use

### ISSUE THREAD

**Issue by ifvictr** [hackmdio/hackmd#297]
I'm hosting my own HackMD, and I don't want any other people to sign up on it. This means that non-registered people will only be able to read public notes, and nothing else (not even sign up). Would this be possible to implement?

**Comment by jackycute** [comment]
you can set `email` to `false` and `allowanonymous` to `false` to disable ability to signin and guest usage.
but you also won't able to do anything, so register first then disable later.

**Comment by ifvictr** [comment]
@jackycute If `HMD_EMAIL` is set to `false`, that will also prevent myself from signing in, which renders the app unusable. I have disabled all external logins also.

**Comment by jackycute** [comment]
So I said as above. You could register first and change your server config and restart later.

**Comment by jackycute** [comment]
Oh yes, you won't able to signin.

**Comment by jackycute** [comment]
Actually I'm wondering how many people need this.

**Comment by ifvictr** [comment]
I'm suggesting separating the email login and registration functionalities, because right now, they're bound together. By separating, we could achieve what you mentioned earlier.

**Comment by jackycute** [comment]
We need to consider about backwards capability, it's not ok to change current exist config.
But adding a `disableemailregister` is fine.

**Comment by jackycute** [comment]
To keep the config naming consistency, will use `allowemailregister` instead.

Also if anyone need this enhancement please +1 or comment.

**Comment by ccoenen** [comment]
I find this to be somewhat related to https://github.com/hackmdio/hackmd/issues/272

**Comment by jackycute** [comment]
Please check if this issue solved in #317

**Comment by jackycute** [comment]
@ifvictr Hi, do you read us?

**Comment by ifvictr** [comment]
@jackycute Sorry I didn't see this earlier, I usually unsubscribe from repos I don't own, so I didn't get the notification (I only get them when @mentioned). Anyways, I tested it, and it works perfectly! Thanks!

**Comment by jackycute** [comment]
No problem!

**Comment by youngcraft** [comment]
in docker ，How to config my docker-compose?? limit one user to use

**Comment by Aincvy** [comment]
> in docker ，How to config my docker-compose?? limit one user to use

Maybe this can help.
```yaml
environment:
  - CMD_ALLOW_ANONYMOUS=false
  - CMD_ALLOW_EMAIL_REGISTER=false
```
