### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by farleylai** [hackmdio/hackmd#30]
1. 支援AsciiDoc，除了使用偏好，許多md的擴充語法在ad已標準化，
2. 所見即所得表格編輯，Hackpad的優點，點選複數表格欄位編輯，
3. 往IPython/Beaker靠攏，除了貼上程式碼，也能執行顯示輸出結果，參考http://beakernotebook.com

AsciiDoc: http://www.methods.co.nz/asciidoc/
AsciiDoctor: http://asciidoctor.org/
Table: http://www.tablesgenerator.com/
Beaker: http://beakernotebook.com

---

1. Support AsciiDoc, besides preferences, lots of extension in md already standardized in ad.
2. WYSIWYG table editing, it's a pros in Hackpad - editing in multiple cells.
3. Go with IPython/Beaker, not only copy/paste code but also show the output, refer: http://beakernotebook.com

**Comment by jackycute** [comment]
Thanks again.

**Comment by grexe** [comment]
+1 for asciidoctor, that would make for a killer combination!

**Comment by madmas** [comment]
@grexe  @farleylai if you are looking for asciidoc support, have a look at https://github.com/hackergarten/hackadoc
htanks to the great codebase of hackmd, we were able to switch the rendering library to asciidoc.js :)

I'd also love to see it as an option in one project where you can choose either per installation or per note which syntax to use. The latter one might get complicated/confusing when some ppl on one instance use MD and others ADoc ;-)

**Comment by SISheogorath** [comment]
Wow, that looks lovely!

An idea for:
> I'd also love to see it as an option in one project where you can choose either per installation or per note which syntax to use.

You can use the meta section for switching the renderer and also set a default option in configs

**Comment by SISheogorath** [comment]
After revisiting this issue I think it's out of our scope to maintain two renderer with the idea of providing a similar feature set. 

This would mean either remove some features form the markdown renderer or put more time than we have into building all or most of the features into the adoc renderer.

And even when there are various people very interested in adoc, I don't see this coming together in HackMD. I think we have too many other feature requests that are focused on our main competence, markdown, that need to be done.

So I'll close this issue for now. But I'm also open for a discussion if you think it's needed.

For a discussion we can either meet here again or on [Gitter](https://gitter.im/hackmdio/hackmd) or on our matrix.org channel [#hackmd:matrix.org](https://riot.im/app/#/room/#hackmd:matrix.org).
