### ISSUE TITLE
GitLab OAuth requests too much permissions

### ISSUE THREAD

**Issue by almereyda** [hackmdio/hackmd#301]
When logging in to HackMD via GitLab, the latter tells me the requested scope is too broad, as I am an admin. How could one request a smaller scope, which only receives what is needed from a user?

**Comment by jackycute** [comment]
Hi @almereyda 
I'm not sure why gitlab sent you that letter.
We directly use the `passport-js` and `passport-gitlab2` in here https://github.com/hackmdio/hackmd/blob/master/lib/auth.js#L89
`passport-gitlab2` repo is here https://github.com/fh1ch/passport-gitlab2

The scope that `passport-gitlab2` default request for is `api` https://github.com/fh1ch/passport-gitlab2/blob/master/lib/strategy.js#L46
And according to GitLab doc `api` is the default and currently the only scope they supported https://docs.gitlab.com/ee/integration/oauth_provider.html

**Comment by Viper61** [comment]
Hi,

On latest Gitlab CE (8.15.1), we have 2 scopes for an application:
- API (Access your API)
- read_user (Read user information)

This seems to not appear in the documentation...

**Comment by Viper61** [comment]
Because it could be found in the interface. On GitLab, go to Admin > Applications > Edit.
Here a scrrenshot :
![hmd-gl](https://cloud.githubusercontent.com/assets/1450966/21505640/7c05810c-cc69-11e6-80dd-98dd3ab8c648.png)

**Comment by jackycute** [comment]
The best approach is open an issue to `passport-gitlab2`
https://github.com/fh1ch/passport-gitlab2/issues

**Comment by ccoenen** [comment]
I'd like to propose a tag "upstream" or "3rdparty" oder something similar, for issues that are blocked by another library. This would also apply to the "superbold" issue (267, intentionally not linked), and possibly others in the future.

**Comment by jackycute** [comment]
good idea @ccoenen

**Comment by almereyda** [comment]
The [README.md](https://github.com/fh1ch/passport-gitlab2#how-do-i-change-permissions--scope-when-obtaining-a-user-profile) of said module states it would allow for requesting different scopes, if passed accordingly.

This feature is indeed only usable with the latest GitLab release 8.15 from six days ago, see:

* https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5951
* https://gitlab.com/gitlab-org/gitlab-ce/tags

**Comment by SISheogorath** [comment]
Upstream [already implemented](https://github.com/fh1ch/passport-gitlab2/blob/master/lib/strategy.js#L46) it. It's a lack of configuration in hackmd. 

See https://github.com/hackmdio/hackmd/pull/320

**Comment by jackycute** [comment]
I should find out this earlier -  we have ability to import/export snippet to gitlab.
And that might need api scope permission.
https://github.com/hackmdio/hackmd/blob/master/lib/response.js#L531

can anyone confirm this?

**Comment by jackycute** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix gitlab request permission by config](https://trello.com/c/5u6ay7od/6-fix-gitlab-request-permission-by-config)

**Comment by jackycute** [comment]
Fixed in 506a381eca5e2bdc31d3529ecd3f1f7797551406
