### ISSUE TITLE
[BUG] Math Processing Error

### ISSUE THREAD

**Issue by YuChunLOL** [hackmdio/hackmd#304]
Cannot write latex in hackmd. 
Please fix it asap, thanks.

**Comment by jackycute** [comment]
It looks good to me.
<img width="743" alt="2016-12-28 2 00 24" src="https://cloud.githubusercontent.com/assets/2639151/21514968/27b0518e-cd06-11e6-9bae-376261463d6d.png">

BTW, you'll need to specify more detail when you report anything.
Thanks.

**Comment by ccoenen** [comment]
I have a hackmd setup on my own server, currently running 0.4.6 with tiny modifications. I believe I can replicate the problem, I just went to the features-page, and it looks like this:

![hackmd-mathjax problem](https://cloud.githubusercontent.com/assets/124909/21517935/23f24930-cce3-11e6-9869-41ebfbf17ab2.png)

The other integrations work just fine.

My browser console has a few warnings, but nothing that seems to be related to the problem:

![hackmd-mathjax problem-console](https://cloud.githubusercontent.com/assets/124909/21518035/e7aa4ecc-cce3-11e6-8ba4-4d360194067a.png)

**Comment by jackycute** [comment]
This has been fixed in 418a852cc483edf6c27eca24ffc8f95d8bcfe414
But will only ship in the next release.
If you're using the docker image, please try to pull the latest one instead of 0.4.6.
