### ISSUE TITLE
pasted URL after image upload

### ISSUE THREAD

**Issue by almereyda** [hackmdio/hackmd#305]
In [my local instance](https://hack.allmende.io/anarchist-meshbook?both#anarchist-meshbook), built from [allmende/docker-hackmd](https://github.com/allmende/docker-hackmd), I am experiencing an issue of malformed image IRIs after upload. Adding the missing `/` would show the image as expected.

    https:/hack.allmende.io/uploads/upload_93db96cf2e7abd7e1679442e3c7e7474.jpg

**Comment by jackycute** [comment]
Already fixed in #302 9fd5c86b826300bdff2677797d607aa3b9cdf975
For docker image, please wait for next release or you could grab the latest one.
