### ISSUE TITLE
YAML metadata not parsed for published revision

### ISSUE THREAD

**Issue by almereyda** [hackmdio/hackmd#306]
When publishing a document, its YAML metadata is not used for generation of the `<meta />`description within the resulting `/s/`ed version of the document.

**Comment by jackycute** [comment]
Hi @almereyda 
I don't think we experience this issue, could you describe more about it?
Thanks.

**Comment by almereyda** [comment]
If I publish a document which has a description entry in its YAML metadata, the generated HTML after publishing will not contain this, but an excerpt of the first paragraph as `meta description` tag.

**Comment by jackycute** [comment]
Bug confirmed.

**Comment by jackycute** [comment]
Fixed in 10a8448c6a9cdde0ad8cadf3dc250de159eacbf2
