### ISSUE TITLE
Prevent creation of empty notes

### ISSUE THREAD

**Issue by ifvictr** [hackmdio/hackmd#309]
I noticed that notes that are _completely_ empty are also saved to the database. Would there be a way to prevent this?

**Comment by jackycute** [comment]
Hi @ifvictr 
It's completely empty in content but not empty in id, shortid, createdAt and so on.
It will also be added into your history list, you could check that empty note later and change it.
So why not? You could delete it if you want.

**Comment by ifvictr** [comment]
Sorry, I made a mistake in wording on my part. By empty (not including the things on the back-end), I meant no title and content. I'm worried that users might spam create blank notes, and when notes are deleted, they are only deleted on the user side, but not from the database.

**Comment by jackycute** [comment]
It's ok.

Actually the database would delete the note, but in soft way.
So the practical practice is running a SQL script periodic to clean note that have been deleted for a while.
Hope this helps.

**Comment by jackycute** [comment]
For example:
```sql
DELETE FROM "Notes" WHERE "title" = NULL AND "content" = NULL AND "deletedAt" > "2016-01-01";
```

Feel free to reopen if you got any other related questions.
