### ISSUE TITLE
Standalone app

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#31]
Can make a chrome extension looks like https://dragdis.com/
Would be great to quick access notes and organize them.

Chrome apps can help to do an offline editing and saving images in local.
Even more convenient to access notes without loading remote resources.

**Comment by jackycute** [comment]
And also maybe http://electron.atom.io/

**Comment by Rplus** [comment]
:+1:

**Comment by jackycute** [comment]
Also can make plugins or packages for text editor like: atom, brackets, sublime text

**Comment by jackycute** [comment]
If you can't wait, try on https://github.com/jiahaog/nativefier
I have tested it on OSX, everything works fine! :100:

**Comment by LuisHsu** [comment]
Electron sounds great!!

**Comment by SISheogorath** [comment]
@jackycute the hint with nativefier is great!

We pusht those natived apps to our users and it's super lovely too have HackMD as a separated window from the browser itself!

For all who want to follow:
```console
# I was forced to run this twice but it worked than
npm install nativefier -g

nativefier --platform {windows,linux,osx} --maximize "<place a title here>" "https://<plcae your hackmd url here>"
```

Now you can zip the resulting folders and hand them over to your users. Easy, fast and very useful.

In case you really want to do: you can place these steps in travis and provide the artefacts using Github.

**Comment by jackycute** [comment]
https://github.com/hackmdio/hackmd-desktop

**Comment by jackycute** [comment]
This issue turned into the electron wrapped desktop app in https://github.com/hackmdio/hackmd-desktop.
Please follow above repo for more details.
