### ISSUE TITLE
No linting in frontmatter or code blocks

### ISSUE THREAD

**Issue by almereyda** [hackmdio/hackmd#311]
Writing the YAML frontmatter can lead to the introduction of unneccessary YAML errors, which leads to rendering of said frontmatter. Including a linter, at least for selected code or structured data bocks, could solve some headaches.

**Comment by jackycute** [comment]
Yeah, actually we have the error message showed in console.
We could also make a div for that.

**Comment by jackycute** [comment]
Added in eaf9218f612f9aa23414decb676d87c812e70f66
