### ISSUE TITLE
Inconsistent cases in config

### ISSUE THREAD

**Issue by neopostmodern** [hackmdio/hackmd#315]
In my understanding the configuration keys (in `config.json`) are case sensitive. Unfortunately, they don't use case consistently. `allowanonymous` is all lowercase while `imageUploadType` is camel case.

I'd suggest to convert everything to camel case due its readability. Backward compatibility could be achieved by e.g. changing
```js
var allowanonymous = process.env.HMD_ALLOW_ANONYMOUS 
    ? (process.env.HMD_ALLOW_ANONYMOUS === 'true') 
    : ((typeof config.allowanonymous === 'boolean') ? config.allowanonymous : true);
```
to 
```js
var allowanonymous = process.env.HMD_ALLOW_ANONYMOUS 
    ? (process.env.HMD_ALLOW_ANONYMOUS === 'true') 
    : (((typeof config.allowAnonymous === 'boolean') ? config.allowAnonymous : true) 
        || ((typeof config.allowanonymous === 'boolean') ? config.allowanonymous : true));
```
Et cetera.

Definitely low priority but would make configuration / initial setup more intuitive.

**Comment by jackycute** [comment]
Yeah, I knew this, and it shows in many config options (most of it), I was keeping them all in lowercase.
The `imageUploadType` was from PR and I missed that style check.

Anyway, PR welcome.

**Comment by neopostmodern** [comment]
But would you then rather stick to lowercase or are you good with transitioning to camel case?

**Comment by jackycute** [comment]
I would like to see camel case because the readability.

It was my old habit to keep them in lowercase, so the first few configs were made in lowercase.
Then I found camel case is better, but for consistency we still keep using lowercase here.

**Comment by jackycute** [comment]
Nah, I've changed my mind, for consistency I will make `imageUploadType` into lowercase.

**Comment by ccoenen** [comment]
@SISheogorath the config right now is still a mixed bag. all the top-level vars are lower case, but many that take objects will have camel-cased keys in them (`cdn`, `hsts` ... among others)

**Comment by SISheogorath** [comment]
I'm not sure we want to fix them. They are often based on the names of the libraries we use behind. If we want to make such a switch, the backwards compatibly changes become a mess. we shouldn't do this.

**Comment by ccoenen** [comment]
But if all other things are camelized, I'd rather go with https://github.com/hackmdio/hackmd/issues/315#issuecomment-271247929 -> all camel case for readability (and for "the way it's usually done in JavaScript").

I'm raising it now, because it's not yet released, and if we were to switch the config file, we shouldn't do this scattered over many releases.

**Comment by SISheogorath** [comment]
I agree, but we still have to maintain the old options which means writing some code for backwards compatibility.
