### ISSUE TITLE
Clean package.json production dependencies

### ISSUE THREAD

**Issue by gbisheimer** [hackmdio/hackmd#318]
Hi. I was checking out the hackmd docker image and trying to make it slimmer. I saw that package.json Dependencies contains some packages that looks like are only needed on the client side (like jquery) and once the application is compiled they won't be needed anymore and could be freed.

Can you indicate which packages are needed as Dependencies and which as DevDependencies, please?

Thanks!

**Comment by SISheogorath** [comment]
Hi,

sounds very useful to me. Maybe I'll run parallel build to kill all maybe isolate dependencies later.

If you are interested in helping reduce the image size you can take a look at https://github.com/hackmdio/docker-hackmd/tree/lite

Currently there is a bug in which breaks the PDF support. A fix is nearly done in https://github.com/SISheogorath/docker-hackmd/tree/fix/pdfGenerator

So feel free to improve this version as we try to switch to alpine which already shrinks the image size to the half.

As long as @jackycute supports that idea ;)

**Comment by jackycute** [comment]
Hi guys,
The idea to minimize the docker image is great.
And I would like to move build only deps (like: webpack, client side deps) to `devDependencies`.
But the most size in the current image is from our base OS image.

**Comment by jackycute** [comment]
The `dependencies` and `devDependencies` both described in `package.json` for now.
https://github.com/hackmdio/hackmd/blob/master/package.json#L144

And I think we should move docker related issue to https://github.com/hackmdio/docker-hackmd
