### ISSUE TITLE
Enforce protocol in callback URLs

### ISSUE THREAD

**Issue by larskaislaniemi** [hackmdio/hackmd#319]
I am in a situation where I want to run HackMD behind a reverse proxy: Nginx serves as a HTTP(S) server with SSL and requests are then forwarded (over internal/secure network/localhost to HackMD that uses HTTP only. For this purpose I want to run HackMD without SSL but still have it generate callback URLs with HTTPS protocol.

I could not figure out a way to achieve this with current config options, so I think a new option would be needed for this (see a fork commit [here](https://github.com/larskaislaniemi/hackmd/commit/c058b43284a1002e6941ad1236519beccf3374d9))

**Comment by SISheogorath** [comment]
I'm not sure if there is a patch needed.

I'm currently run hackmd behind an apache instance and have no problem with non-ssl links:

```apacheconfig
<VirtualHost *:443>
        ServerName hackmd.example.com
        ServerAdmin hostmaster@example.com
        Header always set Strict-Transport-Security "max-age=63072000; preload"
        ProxyPreserveHost On
        ProxyRequests off
        RewriteEngine On
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*) ws://127.0.0.1:3000/$1 [P,L]

        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000
        ProxyVia On
        SSLEngine On
        SSLHonorCipherOrder On
        SSLCertificateFile    /some/path/to/fullchain.pem
        SSLCertificateKeyFile /some/path/to/privkey.pem
        SSLUseStapling on
</VirtualHost>

```

It works fine, maybe you should "translate" this config to your setup.

PS: I use the following config with the docker container of version 0.5.0:
```
HMD_DOMAIN=hackmd.example.com
HMD_PROTOCOL_USESSL=true 
HMD_URL_ADDPORT=false
```

**Comment by SISheogorath** [comment]
Maybe you can provide your configs to reproduce the issue.

**Comment by jackycute** [comment]
Hi @larskaislaniemi ,
We also use a nginx proxy server with SSL setup and it works great.
So you need to set `protocolusessl` be true to keep all resource and callback url will start with `https`.

**Comment by jackycute** [comment]
@larskaislaniemi Hi, do you read us?

**Comment by larskaislaniemi** [comment]
Hi all,
Indeed, `protocolusessl` seems to do exactly what I wanted. I tried this now on another server and there were no problems at all. I need to re-check my Nginx config for the earlier case, but this issue can certainly be dismissed.

Thanks!
