### ISSUE TITLE
Slide mode

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#32]
We may also show the markdown as slides.
see more as below:
https://github.com/hakimel/reveal.js
https://github.com/webpro/reveal-md

https://github.com/gnab/remark
https://github.com/jdan/cleaver

you can suggestion more

**Comment by jackycute** [comment]
Thanks to @x000032001, we are now more close to this. #43

**Comment by jackycute** [comment]
Supported all extra syntax in d39f1fc70084ad5b7c40a03657e5ff8d03cc7944

**Comment by jackycute** [comment]
That's it for now, reopen if any further ideas come in.

**Comment by wirew0rm** [comment]
Syncing the the currently active slide across devices would be pretty cool.

I see various usage scenarios:
* Distributed presentations for videoconferences
* Acessibility for people with impared vision and backrow seats
* Controling the slides on the beamer from mobile device or laptop on the speakerdesk

The clients would have to share the currently active slide with the server and the following clients would have to append some session identifier to the URL like `https://hackmd.io/p/slide-example#/?follow=<user/sessionID> ` to get notified about slide transitions.

For the UI a "follow slides" button could be added to the menu, which allows to select a user. So by default slide mode would be launched as presentation master and everyone else can connect to it. Not sure if sharing the current slide with everyone with access to the note by default would be a problem tough.

This is already implemented in reveal.js and called [multiplexing](https://github.com/hakimel/reveal.js#multiplexing). The client part looks like it should have that is needed, the server part would have to be adapted or at least integrated.

Thanks for this really great project :)

**Comment by jackycute** [comment]
Hey @wirew0rm !

Thanks for heads up, I already knew that reveal.js have that multiplexing feature but I was wondering any use scenario and UI until you mentioned as above.
I think I will take this cool advise, could you please open an new issue and paste your need there?

Thanks a lot 😄

**Comment by wirew0rm** [comment]
Thanks for the fast reply, i've opened #207
