### ISSUE TITLE
List all available notes

### ISSUE THREAD

**Issue by gbisheimer** [hackmdio/hackmd#322]
I'm new to HackMD, so I may be missing something, but I found no way to list all available notes. I recently wrote a note with as certain user and then forgot its password. Created another user but couldn't retrieve the note I've wrote. I had to go through the DB to retrieve the data by manually setting the `alias` field to some string to be able to open the note in the browser.

Is there a way to list all available notes?
Is there a way to configure or change the note alias once it's created?

**Comment by jackycute** [comment]
Hi @gbisheimer,

> Is there a way to list all available notes?
No, and I think it might losing confidentiality of the notes.

> Is there a way to configure or change the note alias once it's created?
No, and we haven't consider about it.

Thanks.

**Comment by gbisheimer** [comment]
Hi @jackycute,

About confidentiality, once a logged in user has the link of a note, it can be seen by anyone. It can also be seen by non registered users (tested by opening up an incognito mode browser) just by using the note URL.

About the alias, I will keep using direct table editing to set the note alias for my preferred notes, so I can access them using the short url.

Thanks!

**Comment by jackycute** [comment]
> About confidentiality, once a logged in user has the link of a note, it can be seen by anyone. It can also be seen by non registered users (tested by opening up an incognito mode browser) just by using the note URL.

Yes, that's part of our design. So the url is encoded which it won't be guessed easily.
Actually you could set note permission to restrict edit or view privilege after you signed in.
![image](https://cloud.githubusercontent.com/assets/2639151/22148928/ea6ec7a8-df4b-11e6-973d-f19e282e9848.png)
