### ISSUE TITLE
Add fontawesome in Revealjs presentation

### ISSUE THREAD

**Issue by sedrubal** [hackmdio/hackmd#323]
In hackmd you can write things like

```md
- hackmd + fontawesome = <span class="fa fa-heart"></span>
```

Which renderes to something like this:

- hackmd + fontawesome = ❤️ 

But this does not work in Revealjs presentations.

Can you simply add

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
```

to the presentation page?

**Comment by SISheogorath** [comment]
It already has support for emojis:

See: https://hackmd.io/p/H15llLAUe#/ Source: https://hackmd.io/KwZgjApsEOwwtCAhgEwQFggBgvARhAMYBs8AnIRAExIgBmxI9wQA#

Why do you need more?

**Comment by sedrubal** [comment]
Thanks for your answer. But unfortunately I need more icons. There are many icons that are only available with fontawesome like company brands, technical icons, ...

**Comment by jackycute** [comment]
Hi @sedrubal ,
We already support font-awesome in slide mode.
I just found the font file not load properly, this is just a bug.

**Comment by jackycute** [comment]
OK, I found the reason.
You should use `<i>` tag for font-awesome icons or its font-family might be overwritten.
@sedrubal I'm going to close this issue.

**Comment by sedrubal** [comment]
Oh oops. Sorry...

**Comment by jackycute** [comment]
It's ok 😄
