### ISSUE TITLE
Image (or any other external content) placing next to text

### ISSUE THREAD

**Issue by vogelfr** [hackmdio/hackmd#327]
It would be nice to be able to declare a file, similar to [Files in Wikipedia](https://en.wikipedia.org/wiki/Help:Files), where an image would be aligned to the right alongside of text.

**Comment by SISheogorath** [comment]
Something like this: https://hackmd.io/EwMwjAxiBGBsCcBaAhveBTRAWeB2AzIgBzTBGLo7wIQQnRZA#

As Markdown supports HTML you can do nearly anything with it out of the box. Sometimes it's not that easy but possible.

If you need it more often you can write a short patch to add a handle for it ;)

**Comment by ccoenen** [comment]
slightly related to https://github.com/hackmdio/hackmd/issues/261

**Comment by ccoenen** [comment]
I'm closing this, but feel free to reopen it. I think HTML is a good suggestion, and AFAIK Markdown does not offer a syntax for alignment.
