### ISSUE TITLE
Make the "Download as Markdown" link wget friendly

### ISSUE THREAD

**Issue by qiuwch** [hackmdio/hackmd#330]
Hackmd.io provides an awesome web interface, but lacks some functions such as full-text search. These features can be provided by local tools, such as grep. Right now there is no way to export all notes to the local filesystem, it is only possible to do it one by one. "Download as Markdown" is a javascript-based button. If this link is wget friendly, I can easily download all notes with a script, then manipulate notes with my local binaries.

**Comment by jackycute** [comment]
Thanks @qiuwch.
We have temp api for "download as markdown" is add `/download` after your note link.
For example: `https://hackmd.io/features/download` will give you the raw markdown with content-type `text/markdown`.

**Comment by qiuwch** [comment]
Thanks, @jackycute. This is exactly what I am looking for. Awesome.

**Comment by qiuwch** [comment]
What if I want to download a private note? Is there a way to provide authentication info in the request header? Thanks.

**Comment by jackycute** [comment]
Nope, not for now.
What you're asking for is API which already filed in #11 
We'll need to build a OAuth process to allow programmatic usage.

**Comment by qiuwch** [comment]
Thanks. This prevents me from creating a simple full-text search solution based on `grep`.
But what you have provided is already pretty awesome.

**Comment by jackycute** [comment]
No problem, please subscribe to the that API issue and you'll be informed 😄

**Comment by qiuwch** [comment]
Is there a way to `Export history` with code, besides clicking the button on the web interface?

**Comment by jackycute** [comment]
Yes, but it only works when you've signed in.
For example, visit: `https://hackmd.io/history` will see all your history list.

**Comment by qiuwch** [comment]
So there is no way to get it with a script, right? This is similar to the API issue I mentioned.

**Comment by jackycute** [comment]
Yeah, currently you won't able to fetch it because not authorized.
This part will come along with API, too.

**Comment by apoikola** [comment]
Any chance of making the /download to work also HTML and other formats?

In Etherpad the different formats can be conveniently downloaded, just by modifying the URL

.../export/html or .../export/txt
