### ISSUE TITLE
Support import from Hackpad

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#335]
Once our inspiration and example - Hackpad begun corruption.
Some pads are missing or inaccessible.
Here is a good start to save them.

This won't be a easy job - their APIs are not reliable and keys are needed.
PRs Welcome 😄 .

**Comment by Yukaii** [comment]
Also take a look at what Quip does. They provide a step-by-step UI to get this done.

**Comment by jackycute** [comment]
@Yukaii Sounds great, could you paste some screenshots?

**Comment by Yukaii** [comment]
![screen shot 2017-01-26 at 5 00 28 pm](https://cloud.githubusercontent.com/assets/4230968/22325567/97040d9c-e3e9-11e6-820a-abfb2d2e3af9.png)

  
![screen shot 2017-01-26 at 5 00 37 pm](https://cloud.githubusercontent.com/assets/4230968/22325578/9d3f58c4-e3e9-11e6-85c5-8340f899db6b.png)            

### Not workspace

![screen shot 2017-01-26 at 5 00 49 pm](https://cloud.githubusercontent.com/assets/4230968/22325583/a67bcd0a-e3e9-11e6-8588-5cc04c58805d.png)

### Is workspace  

  
![screen shot 2017-01-26 at 5 01 14 pm](https://cloud.githubusercontent.com/assets/4230968/22325599/bb8d22a2-e3e9-11e6-9807-1b285e5dd84b.png)

**Comment by jackycute** [comment]
Yeah, I was thing how to tell user give us Client ID and Secret.
Provide a link is kind of intuitive 😄

**Comment by sakura26** [comment]
Actually hackpad have export function, owner can choose "Export to Markdown" and will get a zip package from email. Maybe we can have .MD/.zip uploads first? we can write DIY instruction.

here is the export sample:
[ethanol.hackpad.com.me4dHrdkbyg.sgjhWg1aKj.zip](https://github.com/hackmdio/hackmd/files/732187/ethanol.hackpad.com.me4dHrdkbyg.sgjhWg1aKj.zip)

**Comment by jackycute** [comment]
@sakura26 It's surprising works better than its own API!
Hackpad sometimes will fail to response or response with glitch unicode when request for markdown.

**Comment by sakura26** [comment]
And maybe we can do grouping with GroupName+UUID tags first, so it will have its own list page without modify code.

**Comment by jackycute** [comment]
@sakura26 oh, that's somehow a good idea.

**Comment by ccoenen** [comment]
Request for the Markdown-zip-export hasn't worked for me, as far as I remember. We used to use Hackpad with a small team, so I bet I can get someone from the team to do a test-run.

**Comment by Vdragon** [comment]
The export to Markdown option produces markup that is not exactly map the Markdown spec, including but not limited to:

* "Heading 1" style being translated as 2nd level header `## Markup`
* "Heading 2" style being translated as boldface `**markup**`
* "Heading 3" style being translated as HTML `<undefined><italic>markup</italic></undefined>`

We should convert to proper markup in the import process though

**Comment by ccoenen** [comment]
This is now invalid as Hackpad is no longer, right?
