### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#338]
- user profile #314 
- advanced permission #35 
- user settings
- modulize/plugin/extension
- core scope/class diagram
- admin #272 
- organization/workspace #12 
- collection/book mode #109 
- api (generate api key/secret) #11 
- Unit Test, Integration testing #22

**Comment by a60814billy** [comment]
HackMD 1.0 Roadmap
===

- Permission
- settings
- modulize/plugin/extension
- core scope/class diagram
- admin
- organization/workspace
- collection/book mode
- api (generate api key/secret)
- Unit Test, Integration testing

**Comment by jackycute** [comment]
Move this big roadmap overview to https://github.com/hackmdio/hackmd/wiki/Roadmap
