### ISSUE TITLE
Stripped spaces in published docs

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd#340]
Today I recognized a problem when publishing notes:

While in "view"-view the spaces in a script in the code block exists, they were gone in the published version.

See https://pad.shivering-isles.com/EwUwZgnA7AHADAQwLRQCYQMZICxigNiQQymVQCMBWSqbOKc4UIA=
vs.
https://pad.shivering-isles.com/s/Sk8HLWg_x#

It's a bit annoying.

**Comment by jackycute** [comment]
Hi @SISheogorath 
Our app won't stripe the newline `\n` char on publishing. (just tested on our official service)
Probably is your proxy made some html compression which cause this.

**Comment by SISheogorath** [comment]
Oh thanks, you were right.

mod_pagespeed+HackMD works well until it comes to published notes. Didn't thought of it :D

Thanks for the great support!
