### ISSUE TITLE
Google Drive not showing .md's in _posts directory

### ISSUE THREAD

**Issue by Er-c** [hackmdio/hackmd#352]
Hello,

I am interested in using HackMD for editing (collaboratively) some markdown documents that exist in a Jekyll project. I've placed my Jekyll project in google drive. And now I go to hackmd.io and then try to import from google drive. While I am able to navigate the directories comprising the structure of the project. When I go into, for example _posts, where I know there are many `.md` files, it says that it is empty. I can confirm that thru the direct google drive web UI, they are present. I also see the files in the native google drive within finder on macOS. Lastly, I would note that my html files in the _includes directory are showing up.

Any ideas?

Thank you.

**Comment by jackycute** [comment]
Hi @Er-c 
Based on the docs here https://developers.google.com/picker/docs/reference
I think maybe those files you've mentioned not owned by you, it just shared with you (maybe in your other accounts).
So I will set `setOwnedByMe` to `true` to enable showing shared files/folders in your google drive.
https://github.com/hackmdio/hackmd/blob/master/public/js/google-drive-picker.js#L54

**Comment by jackycute** [comment]
Try to fix in 99a2cbc60461de724167c525cfc89d35c3480cec
Also updated in hackmd.io, @Er-c please refresh and try again.

**Comment by jackycute** [comment]
Wait, I think I misunderstanding the `setOwnedByMe` option meaning.
It will only showing the folders that owned by you but not other people.
Please check if this working or I will revert it back.

**Comment by jackycute** [comment]
Well, I just tested on my laptop, it works in subfolder too (even folder named `_posts`).
How deep is your folder? Could try to move in/out the folder or files around and try again?
This seems not us issue.

**Comment by Er-c** [comment]
Thank you.

The files are definitely owned by me. No Sharing going on.

Your comment re: depth seemed like a good place to start, so I copied the `_posts` directory which was deep at: `My Drive/45cio/src/_posts`

Into: `My Drive/_posts`

Even from there, going into the directory, only directories show, no `.md`s, but I have confirmed they are there from both Google Drive Web UI and from local machine Google Drive.

same with inside for example: `My Drive/_posts/subdir`

Lastly, I'll note the `.html`s are being found fine, even is nested a few directories within. For example:

`My Drive/45cio/_site/subdirectory/file.html` presents itself from within hackmd ui just fine.

---

Note: This is a Jekyll site, perhaps that is apparent from the above. Having the ability to allow participants to use hackmd, to collaborate on an article/post using this method would be amazing. It would allow me to send them one of your share links, have them make changes or do a complete writeup and then I could (assuming Google drive is syncing properly) view the changes on my local machine, do edits and cleanup and then push to git which cause travis to do it's magic, etc.

**Comment by Er-c** [comment]
Followup: I've not installed Hackmd as I see I can do, to use for my own purposes. I'm just trying to use hackmd.io to access my google drive from your website. I feel this should be possible, since I've granted it access to my google drive and it definitely sees directories and some files, just not the all important `.md`s. If I need to do this a different way, I will, but just a heads re: how Im trying it initially now.

**Comment by jackycute** [comment]
OK, so another thing to check.
Do the `.md` files really have the file extension `.md`?
We DO set the MIME type when open up google drive picker.

**Comment by Er-c** [comment]
They do. I am on a Mac. All of my markdown files have `.md` as in `date-post-name.md`.

**Comment by Er-c** [comment]
Here is an exact filename if it helps:

`2017-01-25-Slide-Test.md`

**Comment by jackycute** [comment]
that's super weird, maybe you should ask Google Drive Support (if any)
It's working on my side.
![image](https://cloud.githubusercontent.com/assets/2639151/22839357/040c0e50-f004-11e6-83fb-dae1ccf704a8.png)

**Comment by Er-c** [comment]
Alrighty, thank you so much for your help. I'll continue to dig. I can try dropbox I guess, was trying to keep this segregated is only reason for google drive, so not averse to other methods. So maybe that'll work.

**Comment by jackycute** [comment]
Reopen this if anyone have same issue here.

**Comment by NeverBehave** [comment]
Hi there, I have encountered the same issue here. 

- I have files with `.md` in my Google Drive and owned by me, and I try importing them into Hackmd, but folders are shown empty. 
- I found that only files exported from Hackmd to my Google Drive can show up properly. 

Is it an issue related app scope or something?
