### ISSUE TITLE
scrypt crashing

### ISSUE THREAD

**Issue by PaulDebus** [hackmdio/hackmd#354]
Hey,

first of all, thank you for that awesome project. I really like using it.

I am having trouble getting it to run without docker though.... I tested on my own laptop with docker and it was really easy and just worked. Now I am trying to deploy it on a server where I am not able to run docker. And to be honest, getting it to run is really hard....

I now reached a point, where I really do not know what to do. I have it running and can visit the site in the browser. When I try to register via email, it crashes and in the console I get:
```
(unknown): Generic scrypt code is broken - please report bug!
Aborted
```

Have you any idea what could be wrong?

**Comment by jackycute** [comment]
Thank you @PaulDebus 
That's why we recommend using docker to deploy.
And I found this issue in `scrypt` repo.
https://github.com/barrysteyn/node-scrypt/issues/123

**Comment by PaulDebus** [comment]
Oh, thanks for the fast response. 

Sadly I cannot use docker on the machine, I do not have root rights. 

I now fixed it by changing the dependency for `scrypt` to version 5.4.... not really ideal, but now it works. Maybe I check again if `scrypt` gets updated....

**Comment by SISheogorath** [comment]
I close this issue for now. If it still exists, feel free to reopen.
