### ISSUE TITLE
A way to export all articles to .md file

### ISSUE THREAD

**Issue by ccwinder** [hackmdio/hackmd#356]
Hi, 

I meet a problem when I host a `hackmd` services to my member.
Yesterday the service is normal, but all registered users only can see my post in their history suddenly today.

I want to know is there any way to export all articles to .md files first before I fix the server.
Thanks a lot.

**Comment by jackycute** [comment]
Not for now, we save all data to database and there is no way to export them all at once.
Please backup your database before maintenance.

**Comment by ccwinder** [comment]
Hi, jackycute
Thanks for your response.

It seems I need to find out why other users only can see my post in their history.

**Comment by jackycute** [comment]
You need to provide more detail information to debug.
Are your users signed in?
What's your version? What's your DB type?
Also your `config.json`? Any logs?

**Comment by ccwinder** [comment]
Hi, jackycute
All users use facebook account to log in.
My version is 0.4.5 and database is MySQL

my config is as below
```json
  1 {                                                                                                                                                                                        
  2     "development": {
  3         "domain": "localhost",
  4         "db": {
  5             "username": "",
  6             "password": "",
  7             "database": "hackmd",
  8             "host": "localhost",
  9             "port": "3306",
 10             "dialect": "mysql"
 11         }
 12     },
 13     "production": {
 14         "domain": "192.168.115.87",
 15         "debug": true,
 16         "urladdport": true,
 17         "db": {
 18             "username": "root",
 19             "password": "xxxxxxx",
 20             "database": "hackmd",
 21             "host": "127.0.0.1",
 22             "port": "3306",
 23             "dialect": "mysql"
 24         },
 25         "facebook": {
 26             "clientID": "xxxxxxxxxxxxxxxxxx",
 27             "clientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 28         },
 29         "imageUploadType": "filesystem"
 30     }
 31 }
```
The log file only output when debug is true?

**Comment by jackycute** [comment]
No, the there still some log will output even in production.
Your config looks fine.
Please look at database directly on "Users" table and find "history" field and see if they are all the same.

**Comment by ccwinder** [comment]
Hi, jacky

I check the database directly. Yes, the **history** field are all the same.
I am not sure why it is. 
Could you tell me where is the log file location?

And I think the articles should be still in the database.
Do you have any suggestion to get the article from database?

**Comment by jackycute** [comment]
The log file location is depends on how you run the node server.
It might in the `logs` folder under the server location.
But this never happened before and I couldn't think of how possible this could be.

Yes, all notes and revisions are still there I think.
history is just a json structure that saves all your note browse history but not the notes you owned.
btw, there will be a profile page that shows all you owned notes in 0.6.0.

To get it out just look at the `Notes` table and `content` field will be your notes.

**Comment by ccwinder** [comment]
Hi, jacky

I want to get notes out. 
But when I look at the `content` field at the `Notes` in the DB, I only see the data like **KoOwLglmA2CmAmQ=** or other strings that the human can't read.

It is possible to get data that is readable?

**Comment by jackycute** [comment]
Yes, the data in DB was compressed before 0.5.0.
So please migrate to 0.5.0 and you will get plain text.
See how to migrate to 0.5.0 here https://github.com/hackmdio/migration-to-0.5.0

**Comment by ccwinder** [comment]
Hi, jacky
Yes, after I migrate to 0.5.0, I get plain text.
Now I will export all data from data base and provide to my member to solve my situation.

But I have a question. From users' point of view, we only can get articles from history ?
How about a page like "Owned by me" ?

**Comment by jackycute** [comment]
It's just not implement yet, as I mentioned in above comment:
> btw, there will be a profile page that shows all you owned notes in 0.6.0.

refer to #314

**Comment by ccwinder** [comment]
Hi, jacky
Thanks for your response. After upgrade to 0.5.0, I have solved my problems as my way.
It's a great software!  I donate a little for it.

**Comment by jackycute** [comment]
Thanks @ccwinder 
We appreciate it your kindness!

**Comment by jackycute** [comment]
Reopen if this issue happen again.
