### ISSUE TITLE
cannot show :musical_note: in slide mode

### ISSUE THREAD

**Issue by terric912** [hackmdio/hackmd#360]
Cannot show :musical_note: in slide mode, it shows :musical_ only.

**Comment by jackycute** [comment]
Yeah, this seems like regex issue from speaker note plugin in the slide mode upstream (reveal.js)
https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.js#L119

**Comment by jackycute** [comment]
Fixed in 48f83783350e49cce38e2f9dee2b54f3adda69a8
