### ISSUE TITLE
Mysql ?

### ISSUE THREAD

**Issue by fredhampton** [hackmdio/hackmd#369]
How do Install and use Mysql ?
I have looked at the config file and I m confused about where and how to add an entry for Mysql

Thanks !

**Comment by jackycute** [comment]
Hi @fredhampton 
You have to install MySQL somewhere else.
The DB configs can be passed via `config.json` here: https://github.com/hackmdio/hackmd/blob/master/config.json.example#L9
Or via environment variables `HMD_DB_URL`.

**Comment by ccoenen** [comment]
I created a StackOverflow Tag, I think these kinds of questions are a good fit for StackOverflow.
http://stackoverflow.com/questions/tagged/hackmd

**Comment by jackycute** [comment]
Thanks @ccoenen 
You must notice here been used like a Q&A board.
We'll soon build a forum for community 😄

**Comment by jackycute** [comment]
Reopen if you have further questions @fredhampton
