### ISSUE TITLE
"Publish" button and smiley images use "localhost" as domain

### ISSUE THREAD

**Issue by ColinMaudry** [hackmdio/hackmd#371]
Hello,

I just deployed v0.5.0 at https://pad.maudry.fr.

The "publish" buttons redirects to http://localhost/[pad_id]. The "New" and the logo/home buttons work fine.

Similar problem with the smileys/emojis. Example:

```
https://localhost/build/emojify.js/dist/images/basic/smile.png
```

Any chance it's related to #42?

Thanks.

**Comment by SISheogorath** [comment]
Did you use set `HMD_URL_DOMAIN` as environment variable or `domain` in your config.json correctly?

**Comment by ColinMaudry** [comment]
@SISheogorath Yes... but I bet rerunning `npm run build` will fix it.

I think I switched from `localhost` to `pad.maudry.fr` **after** building the front.

**Comment by ColinMaudry** [comment]
:bulb: That did it.

You, who googled this problem: if you change `HMD_URL_DOMAIN` (env variable) or `domain` (in `config.json`, don't forget to rebuild the frontend libraries with `npm run build`.

**Comment by SISheogorath** [comment]
It's related to https://github.com/hackmdio/hackmd/issues/269

**Comment by ColinMaudry** [comment]
Well, I have broken links to the built JS now, with error 502 "Bad gateway" (cache is clean, I restarted nginx).

**Comment by SISheogorath** [comment]
I tested your setup (as far as I can) and didn't see any 502. In general 502 is more a problem of your reverse proxy than your backend or frontend code.

**Comment by ColinMaudry** [comment]
Sorry @SISheogorath  I forgot commenting back: I ended up backing up my configuration, deleting the hackmd folder and doing a fresh setup.

This time, indeed, it works fine :) Thanks.
