### ISSUE TITLE
String '.insert()` makes service down (release 0.5 and SQL Server)

### ISSUE THREAD

**Issue by derekhsu** [hackmdio/hackmd#377]
Hi, We encounter a problem.

When we inpurt a String ".insert()" in the content, it makes service down and cannot be restarted.
The screen like this:

![Error Screen](http://i.imgur.com/OMWa5Ip.png)

I have to delete the notes from the database for restarting successfully.

I use SQL Server 2008

**Comment by jackycute** [comment]
Hi @derekhsu 
I can't see anything wrong from your screenshot.
I believe this related to the ORM `sequelize` or its SQL server dependency package `tedious`.

Please paste your error logs or we won't able to help.
Thanks.

**Comment by derekhsu** [comment]
Hi, @jackycute 
Actually, I didn't see any error when it happened.
We just saw a line of info SQL command when we restart the service.
I'll paste the info log tomorrow

**Comment by jackycute** [comment]
@derekhsu Hey, could you provide more logs? or we're going to close this now.

**Comment by ccoenen** [comment]
I'm closing this for now. @derekhsu if you get around to providing more details, we'll gladly reopen this!
