### ISSUE TITLE
enable distraction free / word wrap?

### ISSUE THREAD

**Issue by braingineer** [hackmdio/hackmd#378]
Hi!

Absolutely in love with this app so far.  It's everything I've ever realized I wanted and even some things I didn't. 

I was just wondering, how hard would it be to get distraction free mode in place?   e.g. centered, single column text with customizable wrap length

in addition, would it be difficult for a general word wrap parameter?  

I haven't poked around the code base yet, but if I could be pointed at roughly the starting points for this contrib, I could do a PR for it. 

Thanks!

**Comment by jackycute** [comment]
Hi @braingineer 
Sorry for late reply, we are busy on our infrastructure recently.
Thanks you for loving us!

The distracting free mode is related to #176.
And the custom wrap length actually is related to the document width which could easily support by yaml-metadata (but not implemented yet).

The distraction free mode will need to add a theme and lots of UI sugars for editing.
And our codebase now is under refactoring.
So I only suggest you could look at below for yaml-metadata
https://github.com/hackmdio/hackmd/blob/master/public/js/extra.js#L174 

Thanks!

**Comment by ccoenen** [comment]
There's a lot of discussion on the topic in issue #176. I'm closing this as a duplicate. If this is not related, please feel free to reopen!
