### ISSUE TITLE
emoji in html export

### ISSUE THREAD

**Issue by orthagh** [hackmdio/hackmd#380]
Emoji use tortue.me for displaying the corresponding pictures.
This site seems actually down

**Comment by jackycute** [comment]
@orthagh Yeah, you're right. We need to move on to other place (or maybe depends on ourself).

**Comment by jackycute** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix export markdown emoji source](https://trello.com/c/WfzV5LWS/7-fix-export-markdown-emoji-source)

**Comment by jackycute** [comment]
Replace `tortue.me` to `cdn.js`
Fixed in 2fa51fb4ba22a636486ab5add21c69e7cc453574
