### ISSUE TITLE
ABC.js support

### ISSUE THREAD

**Issue by elliptic-shiho** [hackmdio/hackmd#381]
I wrote a music notation support patch using [ABC.js](http://abcjs.net/) based hackmd 0.5.0.

https://gist.github.com/elliptic-shiho/dcdda9e99e5e6e01d2142a8ff7f84477

This code is makeshift code. and I have never developed using Node.js. so, If can merge this patch, I would like to rewrite code by any professional developers.

**Comment by a60814billy** [comment]
It's awesome!!! 
Thanks @elliptic-shiho, we'll add ABC.js support in version 0.6.0 based on your patch.

**Comment by a60814billy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support ABC.js](https://trello.com/c/4cjvQsPh/14-support-abc-js)

**Comment by elliptic-shiho** [comment]
Thanks!

I changed `max-width` of main container ( https://gist.github.com/elliptic-shiho/dcdda9e99e5e6e01d2142a8ff7f84477#file-x-patch-L82 ) for ABC.js output SVG. That may break a some other designs... I think necessary to fix it.

**Comment by jackycute** [comment]
I think we could fix the abc.js output SVG to make it resizable.
We'll make it work as charm, no worries.
Great Job @elliptic-shiho

**Comment by jackycute** [comment]
Supported in 61dc6dbc150dd80e4c1aaa5068cd1432363998dc
Thanks again @elliptic-shiho

**Comment by elliptic-shiho** [comment]
Thanks!
