### ISSUE TITLE
Support for Grammarly Chrome extension?

### ISSUE THREAD

**Issue by orschiro** [hackmdio/hackmd#389]
Dear all, 

I love your tool!

I noticed that the [Grammarly Chrome Extension](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) is not supported. 

It does not check my text as it does on other websites. 

See the example below taken while writing this request. 

I find grammar check support hugely important and very beneficial.

Can we make HackMD compatible with Grammarly?

Yours,

Robert

**Screenshot Example:**

![image](https://cloud.githubusercontent.com/assets/170947/23936560/27511a8c-0953-11e7-9325-e8078ab10a48.png)

**Comment by orschiro** [comment]
Dear @jackycute,

I appreciate your time.

Thank you!

**Comment by SISheogorath** [comment]
If someone want to build that, this is very welcome, but for now, we have not the resources to rewrite codemirror.

Let's just see what the future brings. closing this for now.

**Comment by chhch** [comment]
May this will help others. [StackEdit](https://stackedit.io/app) is a markdown editor, which supports native spell check. But it's missing CodiMD's or HackMD's nice collaboration features. Also, the developing process is not as active as here,  [Github Repo StackEdit](https://github.com/benweet/stackedit). So I ended using both. When I write alone, I use StackEdit. When I write with others, I use CodiMD.
