### ISSUE TITLE
預覽頁面出現再製片段

### ISSUE THREAD

**Issue by s890081tonyhsu** [hackmdio/hackmd#39]
![default](https://cloud.githubusercontent.com/assets/3825000/10777331/5545bb4a-7d55-11e5-98e0-25743f5272d5.png)
敝人使用的是 Firefox Nightly 44.0a1
這份文件只有我一個人在編輯，可是在大量增刪內容時卻出現片段重複內容

原始碼沒有問題，可是預覽貌似沒有同步齊全

先求短期應變方法，老實說我不知道這算不算是一種bug

**Comment by s890081tonyhsu** [comment]
按完publish之後就恢復正常了，這點我自己再研究看看

**Comment by jackycute** [comment]
你好，不好意思晚看到了~
如果這個問題再次發生請跟我說

部分更新的邏輯是我寫的
也不確定不是有潛在BUG

謝謝！
