### ISSUE TITLE
Title Metadata: two digits -> 404

### ISSUE THREAD

**Issue by ccoenen** [hackmdio/hackmd#390]
When you add `title` to the yaml meta data and start with digits (as in: I'm trying to type "2017"), it will redirect to a 404 page.

I tried this here: https://hackmd.io/BwMwbATGCcAmEFoAMYwgQFghdAjDIsCAjBEgOwgjkDMAhrBrEA== but it also happens on my own installation.

## Steps to reproduce

Have a document with YAML metadata, it could look like this:

```
---
tags: Bla bla
title:
---
```

continue typing to add a title, begin with <kbd>2</kbd> and <kbd>0</kbd> to start spelling 2017.

## What is expected

A title like "2017"

## What actually happens

I'm redirected to the 404 page.

**Comment by jackycute** [comment]
Hi @ccoenen, Thanks for reporting this.
Sounds like a serious issue, will check it out now.

**Comment by jackycute** [comment]
Fixed in 4a1d08c653070e856bceb1bc4a7d8ff7ab1aa203
hackmd.io will followed few hours later.

**Comment by ccoenen** [comment]
That was quick :D Thanks!
