### ISSUE TITLE
RFE: Work towards CommonMark spec compliance

### ISSUE THREAD

**Issue by taw00** [hackmdio/hackmd#394]
I am not sure if folks are aware of this, but Markdown is not so much a spec as it is an aspiration. :)

There is an effort to codify and standardize the spec. It is largely complete at this point. Check it out: http://commonmark.org/

I filed this issue as a request to support this standard. If this is already tracked, please close this.

**Comment by jackycute** [comment]
Hi @taw00 
Actually we should already following CommonMark since our parser is [markdown-it](https://github.com/markdown-it/markdown-it).
We knew the Markdown lacking lots of common usage and CommonMark is lots better 😄 
Anyway, Thanks!
