### ISSUE TITLE
Feature request: create new document from URL?

### ISSUE THREAD

**Issue by orschiro** [hackmdio/hackmd#395]
Dear all, 

I just had an idea I want to share with you:

Would it be possible to create a new document from a URL?

For example, hackmd.io/create 

Yours,

Robert

**Comment by a60814billy** [comment]
Hi @orschiro, actually we support to use hackmd.io/new for created a new document.

**Comment by orschiro** [comment]
Perfect! This is what I have been looking for. 

Just great. Thank you. :-)
