### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by mramydnei** [hackmdio/hackmd#396]
Hi!

我发现你的XSS过滤规则有一些问题。在render.js文件中你尝试使用下面的正则来检测URL的合理性。
```
var linkRegex = /^([\w|-]+:\/\/)|^([.|/])+/
```
可能是出于用户友好度的考量，你并没有对可以使用的scheme进行任何限制，只要scheme后面跟着`://`就好。但是下面的这段javascript开头的scheme也是合法的。
```
javascript://%0aalert
```
在上面的例子当中，我们可以通过换行符来结束js里的单行注释`//`进而再下一行执行`alert(document.domain)`

hackmd恰好允许用户自由设定iframe标签的source
```
whiteList['iframe'] = ['allowfullscreen', 'name', 'referrerpolicy', 'sandbox', 'src', 'srcdoc', 'width', 'height']
```
所以我们只需要构造如下的HTML片段，即可对目标系统的使用者进行XSS攻击.
```
<iframe src=javascript://%0aalert(document.domain)></iframe>
```

感觉有空的时候可以修复一下这个问题。
btw，我觉得你的webapp写的很棒！

**Comment by jackycute** [comment]
Fixed in e6298004572004b0f27b29a4b7ed51f884ba0095
Thanks again @mramydnei
