### ISSUE TITLE
CORS issue when embedding

### ISSUE THREAD

**Issue by VinzentE** [hackmdio/hackmd#397]
Hi there,

I want to **embed a hackmd note** in another page in a way that there is **no separate scrollbar** displayed.
My approach was to get the height of the content I am loading from my note to adjust the container / iframe on my site accordingly = full size (heights) embed.
When I try to get the heights, I am receiving a **CORS error**.

Any ideas or suggestions?
Thanks

**Comment by jackycute** [comment]
Hi @VinzentE 
Unfortunately, you can't do that. There is a serious security reason to prohibit that.
The only way is using note's scrollbar - you can't get the content height unless we give you.
But you could set the height according to the note individually.

**Comment by VinzentE** [comment]
Hi @jackycute 
Could you elaborate on "But you could set the height according to the note individually."? Not sure I got our point - wouldn't that also be CORS related?

**Comment by jackycute** [comment]
What I mean is you'll know your note height when you view it (open dev tool or else).
And set that to your iframe height later, it's by manual inspection, no CORS.

**Comment by jackycute** [comment]
Close this for now, this couldn't solved until we implement iframe API (related to #11)
