### ISSUE TITLE
Push to Kindle

### ISSUE THREAD

**Issue by samdx** [hackmdio/hackmd#399]
Hi,
What about features:
- Compile (mobi) ebooks on-the-fly.
- Push compiled ebooks to Kindle (specified send-email).

Thanks!

**Comment by a60814billy** [comment]
Thanks @samdx 
Export markdown to any other format is possible, but we need to known how many people wants this feature.

**Comment by jackycute** [comment]
Actually this could be done with pandoc #48 
Also included epub and so on.

**Comment by ccoenen** [comment]
I'm closing this for now, everyone who wants this feature: make some noise! (or offer a pull request :-) )

**Comment by pirate** [comment]
This is possible with a cronjob and our the makeshift cli in case you're interested @samdx: https://github.com/hackmdio/hackmd/issues/808
