### ISSUE TITLE
Delete line syntax typing bug

### ISSUE THREAD

**Issue by aweimeow** [hackmdio/hackmd#400]
For Example: 
```
Some Text, *and here will be delete line quoted
```

if I type `<s>` at `*` position, then here will become as following
```
Some Text, <s></sand>and here will be delete line quoted
```

I thought the word `and` should not quote into `</s>`

Thanks :)

**Comment by a60814billy** [comment]
Thanks @aweimeow 
We use markdown-it/markdown-it as markdown compiler, maybe it's markdown-it issue.
We will investigate it.

**Comment by jackycute** [comment]
@a60814billy No, actually this is a issue from CodeMirror's close tag addon.
https://github.com/codemirror/CodeMirror/blob/master/addon/edit/closetag.js#L53
Please raise a issue there.

**Comment by aweimeow** [comment]
@jackycute 
I got it, Thanks a lot !

I will submit a issue at CodeMirror later.

**Comment by aweimeow** [comment]
@jackycute 
Hello Max, 
I report issue to codeMirror: codemirror/CodeMirror#4655

They said **HackMD** maybe running in old version or modified version CodeMirror, 

Thank you 😄

**Comment by jackycute** [comment]
We did using modified version of CodeMirror.
And I've checked their demo it does working fine.
We'll look into it.

**Comment by jackycute** [comment]
It appears the addon `closetag` are identical in official version and our fork.
So this occur on some addon combinations.

**Comment by jackycute** [comment]
OK, so this only occur in `text/markdown` mode but not in `text/html` mode.
But html tag should be compatible in markdown, so we need to report to CodeMirror.

**Comment by jackycute** [comment]
Nah, it's our issue, I found it.

**Comment by jackycute** [comment]
Fixed in a77f607ca7f7095c99ac4a37c1a7830c3818f34b

**Comment by aweimeow** [comment]
I cant see commit `a77f607ca7f7095c99ac4a37c1a7830c3818f34b`

but thanks for the working on this bug :)

**Comment by jackycute** [comment]
Oops, I mean https://github.com/hackmdio/CodeMirror/commit/a77f607ca7f7095c99ac4a37c1a7830c3818f34b
This patch will go online few hours later.
