### ISSUE TITLE
Cannot Add Blanks Between Words in a line

### ISSUE THREAD

**Issue by alapha23** [hackmdio/hackmd#403]
In editor mode, it's possible to add blanks between words in a line.

But the blanks are gone when published. It's seems that I can't add spaces and every word in a line are of the same distance from each other.

**Comment by a60814billy** [comment]
Hi @alapha23 
By default will ignore more than one space, you can use `markdown code block syntax` or HTML pre tag to reserve space.
BTW, if you want to custom your pre style, you can write CSS style on your note.

**Comment by jackycute** [comment]
It's a spec in Markdown to ignore multiple continuous inline spaces.
The other methods to add space between or before a line is using the html entities.
For example: `&nbsp;` `&ensp;` `&emsp;` `&thinsp;`.
