### ISSUE TITLE
vexflow/abcjs? what is it?

### ISSUE THREAD

**Issue by serapath** [hackmdio/hackmd#405]
I just saw https://hackmd.io/KwDgpmCMDM3AtAE0SALPVAzEAmeBDANgCNiCAGcgdkQGNhJad9Ug?both

Is there a standalone library that enables 

```abc
X:1
T:Speed of Plough
M:4/4
C:Trad.
K:G
|:GABC dedB|dedB dedB|C2ec B2dB|C2A2 A2BA|
GABc dedB|dedB dedB
```

this notation to work?

It wasnt too easy to find by browsing the source code. I just found `window.ABCJS` but not sure where it comes from :-)

Would like to use the markdown library that supports `abc` template literals or add that feature to an existing markdown library.

I figured there is a library called `vexflow` but couldnt find something minimal that i could just use out of the box

**Comment by jackycute** [comment]
It's `abc.js` implemented abcnotation in javascript, here you are: https://github.com/paulrosen/abcjs

**Comment by serapath** [comment]
I'd like to use/add this to y module https://www.npmjs.com/package/belmark
... or have it standalone too

**Comment by serapath** [comment]
https://codepen.io/serapath/pen/EWeVMZ

**Comment by jackycute** [comment]
It appears not support npm nor publish on it.
There are only standalone version in https://github.com/paulrosen/abcjs/tree/master/bin

And this is not a issue here.

**Comment by serapath** [comment]
sure, thx :-)
