### ISSUE TITLE
Easily adding blockquote tags

### ISSUE THREAD

**Issue by sygi** [hackmdio/hackmd#407]
Hi!
Thank you very much for hackmd.io, I like the page very much :)

I would like to ask: is there a way to easily add author/time blockquote tags currently? I understand that you can write your name and the current time, but I'd like something like:
- press some keyboard shortcut
- hackmd puts my name from my login and the current time in the current block quote

If not, could we mark it as a feature request for someone (I unfortunately am not that proficient with JS)?

**Comment by jackycute** [comment]
Hi @sygi 
Thanks for your suggestion.
We actually provide some auto complete in these tags input.
You could try type below text, there should be some dropdown for you to quickly select what you need.
```
> []I
```
Place your cursor in the "I" position and you will see.

However, we also brought this issue from other people, so maybe a keyboard shortcut will still be easier.

**Comment by sygi** [comment]
That's actually good enough for me. I didn't know it suggests anything, because it does when you are after the closing ], but it is entered automatically. If I were to suggest something, it is to show this dropdown after the user if after [ (instead of []), if possible, but anyway -- that's good for me, thanks.

**Comment by SISheogorath** [comment]
We have a toolbar to insert the needed basics. Filling them is up to the users and I don't think we want to automate too much here as keyboard shortcuts are limited. Maybe take think about a browser extentsion for custom shortcuts.
