### ISSUE TITLE
Make pages uncrawlable

### ISSUE THREAD

**Issue by nicholastulach** [hackmdio/hackmd#409]
This is more of a comment than an actual issue, but is it possible to make hackmd pages uncrawlable by search engines?

**Comment by jackycute** [comment]
Yes, by default we won't add any meta to prevent search bot.
But you could specify it via yaml-metadata, put below code to the very beginning of your note:
```
---
robots: noindex, nofollow
---
```

For detail please visit: https://hackmd.io/yaml-metadata#robots
