### ISSUE TITLE
Documentation on hardware requirements

### ISSUE THREAD

**Issue by xgdgsc** [hackmdio/hackmd#422]
What' s the minimum server hardware requirements of running hackmd? Currently I didn' t find any documentation on this.

**Comment by a60814billy** [comment]
Hi @xgdgsc 

It hard to list minimum server hardware requirement.  It depend on how many notes you want to store, and how many people collaboration in the same times.  But we can provide ours production server specification for references.

```
vCPU: 2 cores (3.3GHz)
memory: 4GB
sorage: 32GB SSD
```
average CPU Utilization is 8%, Memory Utilization is 10%

**Comment by xgdgsc** [comment]
Thanks.

**Comment by ccoenen** [comment]
as an additional data-point: i have my own instance running on the cheapest virtual server I could find. It has an ancient magnetic HDD, 2 GB of ram and one VCPU (which is heavily overbooked in my opinion). I work on this pretty much alone, at most there's 3-4 people on my instance. It works great for the most part.
