### ISSUE TITLE
Not sure how to set up urlpath

### ISSUE THREAD

**Issue by thomsna** [hackmdio/hackmd#424]
I'd like to run hackmd on a sub directory like `example.com/<urlpath>`

I'm running latest version from master, and config.json file looks like this:

```
    "production": {
	"port": "3000",
	"domain": "example.com",
	"urlpath": "hackmd",
	...
```

I have nginx configured like this:
```
    location /hackmd {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

I get a 404 when accessing the page. Is there something I'm missing in the above?

**Comment by jackycute** [comment]
Hi @thomsna 
Please take a look #100 and #86 to see if it helps.

**Comment by thomsna** [comment]
Thanks. It works fine when hackmd is accessed from a root directory, configured as shown in #86.
The problem arises when "urlpath" is defined in config.json, and nginx configured with `location /hackmd`

**Comment by TheAssassin** [comment]
@SISheogorath how did you "solve" this? I don't find anything in the docs, and anything I tried so far doesn't make it work (with the new https://github.com/codmd/container project it's even worse than with the old 1.2.0 version in docker-hackmd).

**Comment by haccht** [comment]
@TheAssassin I'm also in the same situation and I found that the relative path feature is destroyed since codimd upgraded it's webpack in #932.

**Comment by nealian** [comment]
^ Likewise. Any guidance?

**Comment by TheAssassin** [comment]
I was not able to fix that and went for a subdomain instead. I was in a position to do so, but not everyone is.
