### ISSUE TITLE
Old presentations endup in 404

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd#430]
I noticed that an old presentation (pre 0.5.0) is ending up in a 404 page. (but redirected correctly when clicking on `Slide mode`).

I guess this is a problem based on the migration from 0.4.x to 0.5.0. I did that month ago so a new migration wouldn't really be helpful. In general is there a way to "relink" the ids from the presentation to the original source? It would be annoying to copy every presentation into a new note as I gave some links to students I can't change anymore.

Would be helpful to have a ready database statement otherwise I have to figure it out myself later.

**Comment by jackycute** [comment]
Hi @SISheogorath 
That's weird.
We didn't change any id related db schema from 0.4.x to 0.5.0.
The slide mode will use the `shortid` after the `/p/` url, and it's pretty much a stable path.
So could you check your db about how these notes look like?

**Comment by SISheogorath** [comment]
Database looks fine :confused: 

Notes are stored in plaintext (like they should since 0.5.0) and also the shortid is fine. Even if I access `/p/<shortid>` directly I endup in a 404. Newly created notes (same content) work fine.

When I compare the data inside the data all columns of the node are identical besides the id, shortid, authorship (small difference in the last two section (I guess timestaps?)), and the timestamp entries.

I checked it back the redirect is identical, so it's not a shortid problem. But also the only error I see is the webserver say it has to report a 404. Not more. So it's not like there is a server-side exception or something.

I'm really hardly wondering how that happens .-. (Also tried up and downgrade between latest and 0.5.0).

Very weird.

**Comment by jackycute** [comment]
@SISheogorath omg, you really hunted a ghost down.
I thought it was caused by the `shortid` package but result in a bigger one.

**Comment by jackycute** [comment]
According above comments, this issue is not directly related to us.
Close for now.

**Comment by bvanelli** [comment]
A bit late to the party, but I had the same exact issue. In my case, the issue went away after running a REINDEX on the table (or on the database, as a general fix), as some indexes can brake between postgres instances. Maybe this can help other people in the future, as I was clueless in the beginning.
