### ISSUE TITLE
Idea: Show hint to log in on 403 page

### ISSUE THREAD

**Issue by neopostmodern** [hackmdio/hackmd#431]
I frequently get messages by our users complaining about 403 messages on notes that were shared with them. They are simply unaware that they have to log in.

The current text (**403 Forbidden** oh no.) isn't very helpful with that.
How do you feel about adding something like:

> You're not logged in. Log in *here* to access this document.

**Comment by ccoenen** [comment]
related to #526

**Comment by SISheogorath** [comment]
I think it can be done easier than a redirect. We can probably render the [sign-in.ejs](https://github.com/hackmdio/hackmd/blob/master/public/views/shared/signin-modal.ejs) into the view, so we don't need to redirect. from the original document. But I'm not sure if the sign-in code already handles redirects to the page where it came from.

**Comment by SISheogorath** [comment]
Redirect happens now: https://github.com/hackmdio/hackmd/pull/785
