### ISSUE TITLE
When are revisions created?

### ISSUE THREAD

**Issue by PaulDebus** [hackmdio/hackmd#433]
Hey,
 I just have a quick question: When are revisions of the document created? Or can I trigger that manually? We want to be able to return to a previous state easily and I thought this is what the revision feature does, but I only can return to the revision of the initial creation of the document, where it is empty.

Thanks for your time and the great work!

**Comment by jackycute** [comment]
Hi @PaulDebus 
Revisions are created when note not been modified for 5 mins or not saved for 10 mins.
Code is here: https://github.com/hackmdio/hackmd/blob/master/lib/models/revision.js#L200
You can't trigger it manually for now. Please be patient.

Thanks.

**Comment by PaulDebus** [comment]
Hey,

thanks for your fast response! I did not know that. That is a good solution I think. Should work for me.

Keep up the good work!

**Comment by berkowitze** [comment]
Are revisions ever deleted? would love to use it as a years-long version control but not sure if that's an option.

**Comment by SISheogorath** [comment]
They are deleted when the note is deleted. Otherwise they stay as long as the database stays without data corruption.

But please feel free to open a new issue when you have further questions or just join us at the community chat: [`#codimd:matrix.org`](https://matrix.to/#/#codimd:matrix.org)

**Comment by zuzanca4** [comment]
Any updates on forcing a new revision, please?
