### ISSUE TITLE
User password changing

### ISSUE THREAD

**Issue by conspacer** [hackmdio/hackmd#434]
Is there a way users can change their own passwords after logging in? (or can admins hardcode new passwords in the DB somehow?)

**Comment by jackycute** [comment]
Hi @conspacer 
There isn't any way to change user's password after signed-in.
But yes, you could change it in the DB.
The password is hashed (scrypt), so you could hash your new password then replace it.

**Comment by conspacer** [comment]
@jackycute do I need to pull the salt value from the instance to generate a correct hash?

**Comment by jackycute** [comment]
Yes, you do.

**Comment by conspacer** [comment]
Thanks for the info

**Comment by Xumeiquer** [comment]
I think reseting the password by using the script manually is no a propper solution. You have to take care to not damage the DB, for example.
It would be more useful for everyone to have a reset button as other web apps have.

**Comment by ccoenen** [comment]
#952
