### ISSUE TITLE
Image upload to S3 - ContentType not set

### ISSUE THREAD

**Issue by LluisArevalo** [hackmdio/hackmd#435]
Hello!

First of all, thanks for providing us hackmd.

When you are using hackmd configured with S3 to upload images, these images have no ContentType specified. By default, the image is set with the `application/octet-stream` type. When you try to open this image in a separate tab of the browser, it starts a download instead of show it.

To solve that, you have to add the correct ContentType to the parameters you are sending to S3. I have already implemented the solution in the version we forked, so let me know if you want me to create a PR to send it to you :)

Thanks again for the project!

Best,

Lluis Arévalo

**Comment by jackycute** [comment]
Hey @LluisArevalo 
We'd love to see your PR.
Thanks for heads up 😄

**Comment by LluisArevalo** [comment]
Thanks @jackycute, here it is: https://github.com/hackmdio/hackmd/pull/452

I hope it's well done :)

**Comment by jackycute** [comment]
Well done @LluisArevalo 👍
