### ISSUE TITLE
Support configuration of reveal.js theme

### ISSUE THREAD

**Issue by nichtich** [hackmdio/hackmd#437]
Looks like the reveal.js theme "black" is hardcoded in https://github.com/hackmdio/hackmd/blob/master/public/views/slide.ejs. How about a YAML configuration field to select a predefined theme:

~~~yaml
slideOptions:
  theme: white
~~~

**Comment by jackycute** [comment]
Thanks @nichtich
I agree with this one.

**Comment by SISheogorath** [comment]
Fixed by #471 

https://github.com/hackmdio/hackmd/blob/e5834c077f203aa5c80f777f91e0bf650614241d/public/views/slide.ejs#L32-L37
