### ISSUE TITLE
CSS style of notes

### ISSUE THREAD

**Issue by nichtich** [hackmdio/hackmd#438]
Slides can have speaker notes such as this:

~~~
<aside class="notes" data-markdown>

This is a note with *markdown* formatting.
</aside>
~~~

These are shown as expected in slide mode with reveal.js (press "S") but the default HTML preview shows them as normal content. A CSS rule for element "aside" should better show these notes them in a smaller font or hideable.

**Comment by jackycute** [comment]
Hi @nichtich
The note markdown parser is different from the slide markdown parser.
And I don't know if it's the time to add that in because the speaker notes plugin actually having an issue here #360.

**Comment by nichtich** [comment]
ok, with two different parsers this is hard to do.

**Comment by jackycute** [comment]
No much difference, it's the slide parser extend note parser and add some plugins from reveal.js.
The problem is more like the speaker notes plugin have above mentioned bug.
And I personally think the slide is different from note, so it's reasonable of the speaker notes parsing as normal syntax in note.

**Comment by nichtich** [comment]
By the way Pandoc Markdown supports [a different syntax](http://pandoc.org/demo/example19/Speaker-notes.html) which I would prefer to not have too many different standards:

~~~markdown
<div class="notes">
This is a note with *markdown* formatting.
</div>
~~~

**Comment by SISheogorath** [comment]
You can actually use
```
Note: Some speaker notes
```
Maybe it's `Notes:`.

I found it by accident :D
