### ISSUE TITLE
Download as pdf file

### ISSUE THREAD

**Issue by albertcht** [hackmdio/hackmd#446]
Do you remove the function of downloading as pdf?
I can't find any pdf options in the download section.

**Comment by jackycute** [comment]
Hi @albertcht 
We temporarily disable download as pdf feature.
Because it affects the system performance a lot.
It's still available in this repo.

Also I would like to suggest to use the browser built-in print as pdf feature.
That result even better than our pdf export.

**Comment by albertcht** [comment]
Got it! Thanks for your amazing reply speed :)
