### ISSUE TITLE
Using absolute symbol for math expression in the table leads wrong parsing

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#447]
The absolute symbol for math expression is same as the table dividers.
So if user input the absolute symbol for math expression in the table.
It will parse the absolute symbol as the table dividers and ignore the math expression.
Example:
```
|test|test|
|----|----|
|$|asd|$|aasd|
```
<img width="138" alt="2017-05-04 11 50 46" src="https://cloud.githubusercontent.com/assets/2639151/25690046/f08d0670-30bf-11e7-9cc4-f16a6585ff3c.png">

**Comment by Lin-Buo-Ren** [comment]
Isn't $$ \mid asd \mid $$ can be used as a workaround?  Not familiar with TeX syntax though...

**Comment by SISheogorath** [comment]
@Lin-Buo-Ren This seems to work! Nice!

If there are still problems, I would recommend to open in upstream issue on the markdown-it repository. It seems to be more general.
