### ISSUE TITLE
Download URL for raw Markdown file

### ISSUE THREAD

**Issue by nichtich** [hackmdio/hackmd#448]
I miss an URL to directly download the Markdown source, e.g. query parameter `?format=markdown`.

**Comment by jackycute** [comment]
Hi @nichtich 
You can download the markdown directly by adding `/download` path after your note url.
Like: `https://hackmd.io/features/download`

**Comment by standage** [comment]
Soooo...on my end, this works for the features page, but not for any other pages. Has this been tested on arbitrary pages?

**Comment by BinotaLIU** [comment]
hi @standage, for hackmd.io related issues, please report to https://github.com/hackmdio/hackmd-io-issues. This repository is for CodiMD (which is previously called HackMD CE, Community Edition)

Please ensure to cleare url [fragment/query strings](https://en.wikipedia.org/wiki/URL#Syntax)(anything after `#` and/or `?`) while you trying to append `/download` into the url.
For example, say `https://hackmd.io/dflbiMW1RyOwIkpQ5Bk6WQ#`, you should remove the `#` and all string after it in the url, which should becomes `https://hackmd.io/dflbiMW1RyOwIkpQ5Bk6WQ`, then you can append `/download` to it.

**Comment by metal3d** [comment]
Doesn't work for me...

**Comment by jackycute** [comment]
Hi @metal3d, I think that API still works.
Could you share what link you're using is not working?

**Comment by metal3d** [comment]
Yes, the fact is that if the note is not "shared" or readable by everyone, it is impossible to get it via that URL. I opened rights to be able to get markdown (to stream that in pandoc, my god it's so nice with yaml headers to configure) and it works.

The best I hope is to have a link in "read only" with a secret. But for now, opening rights fixed my problem.

**Comment by loismbferraz** [comment]
https://hackmd.io/dflbiMW1RyOwIkpQ5Bk6WQ/download

**Comment by holgerbrandl** [comment]
The `/download` suffix works nicely, but it does not seem to include the uploaded images. Is there an easy way to fetch them along with the markdown?
