### ISSUE TITLE
能否提供帶側邊目錄欄的HTML / Provide HTML with sidebar TOC?

### ISSUE THREAD

**Issue by menervil** [hackmdio/hackmd#453]
##下載功能中或者發表時，能否提供帶側邊目錄欄的HTML。如下：
![wx20170508-172839](https://cloud.githubusercontent.com/assets/6245136/25798511/0eac44a2-3414-11e7-8faf-150174c00848.png)

**Comment by jackycute** [comment]
嗨 @menervil 
我們已有提供右側目錄 (當螢幕過小會自動變成按鈕)
<img width="178" alt="2017-05-08 7 10 53" src="https://cloud.githubusercontent.com/assets/2639151/25801843/1deb6a3e-3422-11e7-9694-f1bb4683286e.png">
<img width="359" alt="2017-05-08 7 11 04" src="https://cloud.githubusercontent.com/assets/2639151/25801845/20a70de6-3422-11e7-8a13-40e976c7f047.png">

**Comment by menervil** [comment]
@jackycute 嗯，我也注意到了右側的目錄按鈕，非常方便！可能我的建議有點苛刻，我的想法是發布出來的HTML網頁上，能否就帶有左側的目錄列表，這樣在給其他人閱讀時，切換目錄非常方便，效果類似於我之前發的圖片。我查詢過其他的一些類似的工具或者網站，在導出HTML格式的文檔時，都沒有提供自動生成左側的目錄列表的功能。也許這個功能並不是剛需，但是可以成為一個亮點，畢竟是別的工具沒有的。當然這可以作為可選的功能提供給用戶。只是建議，您可以不採納。

**Comment by jackycute** [comment]
嗨，不好意思，我還是沒有很清楚您想要的是什麼
是想要把目錄放在左邊？還是希望目錄可以全部展開？

另外，我剛剛發現了一個問題
就是其實下載的 HTML 應該可以要展開目錄，所以剛剛修正了be99350655ca33aaa14b99d7b44b529aba0c8773

您可以按 Expand All/Collapse All 去展開/折疊 目錄，如下圖
<img width="191" alt="2017-05-10 12 13 10" src="https://cloud.githubusercontent.com/assets/2639151/25860977/ddbc5442-3515-11e7-8a48-b67063b06b0d.png">

**Comment by TzuChin** [comment]
Hi, 我猜想 @menervil  的意思是否是底下兩個猜測之一? ：

1. 有可能只是想表示，需要 Book Mode ?
如果是的話，現在已經有了，參考： [Book example](https://hackmd.io/c/book-example/%2Ffeatures)

2. 或者menervil是想表達... :
現在有提供下載HTML的功能，
雖然有BookMode，
但下載回來是單一頁HTML，
以這個為範例： [Book example](https://hackmd.io/c/book-example/%2Ffeatures)
下載後其實就是一個 Features.html 單一檔，
而不是整個有架構的 Book

**Comment by menervil** [comment]
是的，我的意思就是@TzuChin說的第二個猜想。不過單一頁HTML可以按 Expand All/Collapse All 去展開/折疊 目錄，雖然是在右邊，但是也能夠滿足我說的需求了。還是感謝 @jackycute @TzuChin 你們的參與！

**Comment by TzuChin** [comment]
抱歉，我上面2的舉例說錯了，
我的意思是，
以這頁的BookMode   [Book example](https://hackmd.io/c/book-example/%2Ffeatures) 來說
要下載的話，
就會到這邊下載 https://hackmd.io/book-example
但是下載出來的HTML沒有 BookMode 預覽時的那個架構

**Comment by akira9478** [comment]
同上
現在在整理筆記才看到有book mode可以使用
我會再建一頁來組合所有筆記頁再使用book mode
打開book mode後卻沒有可以下載html的功能
所以沒辦法載下整本自己整理好的book
希望有載下bookmode的html功能
或是可以打包下載整本書的所有page

**Comment by jackycute** [comment]
For better management and avoid confusing, please report any further issue in https://github.com/hackmdio/hackmd-io-issues

Thanks!
