### ISSUE TITLE
config.json port 無法設定

### ISSUE THREAD

**Issue by kay54068** [hackmdio/hackmd#454]
使用port var不能設定port， 
    "development": {
        "domain": "localhost",
        "port": "3000",
        "email": "true",
        "allowemailregister": "true",
    },
只能更改domain var
     "development": {
        "domain": "localhost:3000",
        "email": "true",
        "allowemailregister": "true",
    },

**Comment by jackycute** [comment]
嗨 @kay54068 
port 請使用數字型別
```
"development": {
  "domain": "localhost",
  "port": 3000, // <-- here
  "email": "true",
  "allowemailregister": "true"
}
```
