### ISSUE TITLE
請問 book mode 要如何開啟??

### ISSUE THREAD

**Issue by kay54068** [hackmdio/hackmd#455]
請問您於 config.json 如何設定 book mode 功能將它開啟??

**Comment by jackycute** [comment]
嗨 @kay54068
book mode 尚未開源

**Comment by kay54068** [comment]
@jackycute 
謝謝您，未來會開源嗎?
正好需要此功能架設在學校的實驗室.

**Comment by jackycute** [comment]
現在我們專心在開發新功能
因此程式碼跟系統還不太穩定
未來等架構比較完整的時候會考慮開源 😉

**Comment by darkblinded** [comment]
@jackycute Any news on this? Could really use this feature. Can you give an ETA when the feature will be released?

**Comment by jackycute** [comment]
@darkblinded Hi, book mode is now exclusive available in hackmd.io and HackMD Enterprise Edition. 😉

**Comment by darkblinded** [comment]
Are you planning to release this or will this be an enterprise-only feature?

**Comment by jackycute** [comment]
@darkblinded Yes, currently it’s a enterprise-only feature.
