### ISSUE TITLE
無法新增筆記 & 無法使用Mail登入

### ISSUE THREAD

**Issue by kay54068** [hackmdio/hackmd#456]
目前遇到兩個問題:
1. 無法連線新增筆記
2. mail 登入可註冊但無法登入:

![image](https://cloud.githubusercontent.com/assets/3054544/25861570/badee262-3517-11e7-98c1-a1fc29ca3cc6.png)

web services : forever
sql: mysql

請問我是哪邊沒設置好呢?

**Comment by jackycute** [comment]
請問您是用什麼方式部署呢？
請提供您完整的 `config.json` 或是環境變數以及系統平台版本

如果對於環境架設比較不清楚的，建議使用 [docker-hackmd](https://github.com/hackmdio/docker-hackmd) 會更簡單

**Comment by jackycute** [comment]
@kay54068 請問有看到以上的留言嗎？

**Comment by kay54068** [comment]
抱歉，最近有事沒上線

my config.json  : 

     "development": {
        "domain": "localhost:3000",
        "email": "true",
        "allowemailregister": "true",
        "db": {
            "username": "hackmd",
            "password": "firmware",
            "database": "hackmd",
            "host": "localhost",
            "port": 3306,
            "dialect": "mysql"
        }
    },

OS:  4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
npm: 3.10.10
forever: v0.15.3

**Comment by jackycute** [comment]
@kay54068 
您設定檔中的 `domain` 無須在最後加上 `:3000`
還有，`allowemailregister` 是 `true` 不是 `"true"`

**Comment by jackycute** [comment]
您好，因有一段時間未收到此問題的回覆
先將此問題關閉，如您仍有疑問，歡迎重新開啟此問題！
