### ISSUE TITLE
fork audreyt/pad2an to be used in hackmd

### ISSUE THREAD

**Issue by kiang** [hackmdio/hackmd#457]
Some people are still using https://github.com/audreyt/pad2an to maintain sayit content with hackpad. It would be great if hackmd could have the same feature.

**Comment by kiang** [comment]
before: https://hackpad.com/ep/pad/static/fGuLa9AEe2Z
after: http://mixtaiwan.sayit.mysociety.org/mixtaiwan-20170322-%E8%B6%A8%E5%8B%A2-%E6%9E%97%E5%AE%88%E5%BE%B7-%E8%A7%A3%E6%B1%BAai%E7%9A%84%E5%9B%B0%E5%B1%80%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E7%9A%84%E7%AC%AC%E4%B8%89%E6%B3%A2%E9%9D%A9%E5%91%BD

**Comment by SISheogorath** [comment]
Since Hackpad has shut down its service I'm not sure what the actual service is, that was offered here. Can you maybe explain what the service is that is offered?

For me, it seems like a 3rd party tool. If it wants to use HackMD it should be updated. But if we know the functionality, we can maybe provide something

**Comment by kiang** [comment]
The service is simply that you could have a specified hackpad page and edit the content following the rules. Then execute the tool could convert the content into sayit. The reason using hackpad is just for collaboration.

Currently Ronny had forked the hackpad and rebuild it at https://hackpad.tw/ . We can use the tool again.

**Comment by SISheogorath** [comment]
looks like it's enough to replicate the functionality of this file:

https://github.com/audreyt/pad2an/blob/gh-pages/pad2an.ls

And add it as an export option. It's mainly translation work for LifeScript to JS or writing a wrapper for a library import. No matter how we do it, it needs some work and all help is welcome 😄

**Comment by SISheogorath** [comment]
Seems to be not interesting enough for someone to work on it.

Closing for now, but Pull requests are welcome
