### ISSUE TITLE
*emphasis* & **strong emphasis** markup not working under certain circumstances

### ISSUE THREAD

**Issue by Vdragon** [hackmdio/hackmd#459]
* [Bug Reproducing Playground for Hackmd Issue \#459 \- HackMD](https://hackmd.io/IYNgHALARgTArATgLQGMEgkiBTCyoAmw2qAZgQIwwAMKiFCCQA==?both)
    * Issue can be reproduced when:
        * the symbol_character is not at the end of the markup(symbol_character can either English or Chinese punctuation character, like colon:： and period.。)
        * AND space is not immediately after the markup
* [Daring Fireball: Markdown Syntax Documentation - EMPHASIS](https://daringfireball.net/projects/markdown/syntax#em)
* [CommonMark Spec - Emphasis and strong emphasis](http://spec.commonmark.org/0.27/#emphasis-and-strong-emphasis)

![_025](https://cloud.githubusercontent.com/assets/1192163/26048999/fc1a29bc-398b-11e7-8d64-5b3260c3c752.png)

**Comment by jackycute** [comment]
Hi @Vdragon 
We use `markdown-it` as our parser engine.
You could try those cases in their demo page: https://markdown-it.github.io/
And please open issue there for edge cases: https://github.com/markdown-it/markdown-it

Thanks.

**Comment by ccoenen** [comment]
This has not been touched in a long time, and there are not related issues in the upstream repo. I'm closing this. If somebody adds this to the markdown-it bugtracker, feel free to report back here! But the issue probably needs to be fixed there.

**Comment by Vdragon** [comment]
Apologies for the ignorance, the issue has been filed upstream at <https://github.com/markdown-it/markdown-it/issues/410>
