### ISSUE TITLE
Export Gist - 404 not found

### ISSUE THREAD

**Issue by howkj1** [hackmdio/hackmd#461]
Menu --> Export Gist 
opens HackMD in new tab and results in 404 not found message.

My HackMD.io has github auth for creating new gists.

---
![screen shot 2017-05-16 at 12 48 46 pm](https://cloud.githubusercontent.com/assets/9202867/26120430/5689f4c2-3a36-11e7-8434-dad6bba8c53a.png)

---
![screen shot 2017-05-16 at 12 48 21 pm](https://cloud.githubusercontent.com/assets/9202867/26120433/59a9ddd4-3a36-11e7-8d8a-78c17e7ad7c1.png)

---
![screen shot 2017-05-16 at 12 53 11 pm](https://cloud.githubusercontent.com/assets/9202867/26120527/acf1fb16-3a36-11e7-8ca3-c75c3b254ec9.png)

**Comment by jackycute** [comment]
Hi @howkj1 
Thanks for reporting this.
This bug has been confirmed, will fix soon.

**Comment by jackycute** [comment]
Fixed in 0a6793747cf1f40467bcf3e562d358173fffcad1

**Comment by howkj1** [comment]
When will 0a67937 be pushed to hackmd.io public servers for use? https://github.com/hackmdio/hackmd/commit/0a6793747cf1f40467bcf3e562d358173fffcad1

**Comment by jackycute** [comment]
Like now, we've pushed it few minutes ago.

**Comment by howkj1** [comment]
Refreshed, tested, and it is working now. Thanks for the quick response time and fix!
