### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by VinzentE** [hackmdio/hackmd#469]
Hi there,

I am trying to set up hackmd locally and did follow these steps:
1. cloning: git clone https://github.com/hackmdio/hackmd.git
2. installing: run the script in bin/setup
3. building: npm run build
4. running: npm run start

PS: I have not changed any of the default settings in config.js nor any ENV.

I am getting some error about sqlite:
error: uncaughtException: dlopen(/Users/.../hackmd/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:        
/Users/.../hackmd/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1609728 which is past end of file 6568
96 ...

I had it working fine a couple of weeks ago - as far as I remember, the sqlite file was automatically created in the root-folder.

And:
I have installed a heroku postgres db - now to attach my local copy of hackmd (once i have it up and running again) to that database - would I just have to adjust the values in config.json and then run "npm run build" once again? How would I create / update the schema in the db? 

Would be great to have a detailed step by step for setting hackmd up e.g.
1. locally only
2. app locally, db on heroku
3. app on heroku, db on heroku
I would contribute the documentation, but would need some help on the actual steps.

Thanks for your ideas up front!

**Comment by SISheogorath** [comment]
In case of your error message:

> error: uncaughtException: dlopen(/Users/.../hackmd/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node, 1): no suitable image found. Did find:
/Users/.../hackmd/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1609728 which is past end of file 6568
96 ...

It looks like you're using OSX. That's maybe a problem (I'm not an OSX user, so can't say for sure). Please check: https://www.npmjs.com/package/sqlite3#on-os-x-with-homebrew

---

> How would I create/update the schema in the database?

In case of a switch from 0.4.x to 0.5.x check the [Migrator](https://github.com/hackmdio/migration-to-0.5.0).

Otherwise, all needed schemas are included. Check out the [upgrade instructions](https://github.com/hackmdio/hackmd#upgrade-guide).

For the database, there is no difference if it's located on your local system or somewhere else. For upgrading of a Heroku deployment of HackMD itself, I can't say, as I don't use it.

**Comment by VinzentE** [comment]
Thanks a lot for your quick response.
I have it up and running locally (used not the latest master branch, but version 0.5.1). I have it working with a local sqlite.
now I wanted to change the database to heroku postgres (or any other hosted postgres) - so I have added the details here:
 "production": {
    "domain": "localhost",
    "db": {
      "username": "...omc",
      "password": "f...df3e...f",
      "database": "d....",
      "host": "ec2-5.....eu-west-1.compute.amazonaws.com",
      "port": "5432",
      "dialect": "postgres"
then I did run 'npm run build' and then 'npm run start' - but it is still using the local sqlite database and not the one I had entered in config.json.

Any hint on what I am missing?

**Comment by SISheogorath** [comment]
Have you set `NODE_ENV` to `production`? If not, that's your problem :D

**Comment by VinzentE** [comment]
Great idea - thanks. I actually haven't had set it! 
1. added the following ENVs:
`
NODE_ENV=production
DEBUG=false
HMD_DB_URL=postgres://vow...o...9.eu-west-1.compute.amazonaws.com:5...m
HMD_ALLOW_ORIGIN=localhost
`
2. then `npm run build`
3. then `npm run start``

Result: it still accesses the local sqlite :(

Any other hints and tricks?

**Comment by SISheogorath** [comment]
Sounds like you did something wrong by setting the environment variables. Currently, environment variables overwrite the config settings in `config.json`.

You can verify the environment variables are set for the running instance, by getting the id of the node process which runs HackMD and then use `cat /proc/<pid of the node process>/environ`.

Make sure you use `export` in front of the environment variables when you set them in your shell.

**Comment by SISheogorath** [comment]
Closing because of no further response.

Please reopen if the issue still exists.
