### ISSUE TITLE
Windows Installation Fails

### ISSUE THREAD

**Issue by jojify** [hackmdio/hackmd#470]
Hi there,

Windows installation fails at codemirror package. It also fails in several optional dependencies. In logs, it says the package is not for win32 platform. I didn't change any configs. Thanks and Regards,

Joji John

**Comment by jackycute** [comment]
Hi @jojify 
Due to our install scripts and dependencies, we could only support unix-like OS for now.
Please use https://github.com/hackmdio/docker-hackmd to deploy on Windows.
Thanks.

**Comment by jackycute** [comment]
Close for now.
