### ISSUE TITLE
Rendering emoji on titles is buggy

### ISSUE THREAD

**Issue by HaoCherHong** [hackmdio/hackmd#475]
Adding following line causes error on rendering
`## 💰`
Rendering result:
![image](https://cloud.githubusercontent.com/assets/2157335/26752692/b49d0c6a-4888-11e7-8afa-e97f21b8e6e4.png)

**Comment by jackycute** [comment]
Hi @HaoCherHong 
I couldn't reproduce this issue by simply give emoji on headers.
Could you give complete example?

**Comment by HaoCherHong** [comment]
Ok I think that the problem only occurred when you use this chrome extension to enter the emoji:

[Emoji for Google Chrome™](https://chrome.google.com/webstore/detail/emoji-for-google-chrome/immhpnclomdloikkpcefncmfgjbkojmh
)

just type ## on the editor and copy the money emoji on in the plugin. 
Then paste it on the editor

my OS is Windows 10 Pro

**Comment by jackycute** [comment]
That extension replace the emoji (unicode) it found in the html to a span with image.
Not our issue, I would suggest to disable that extension.
