### ISSUE TITLE
Connection refused error - Hackmd call out to an IP over port 8080

### ISSUE THREAD

**Issue by JJediny** [hackmdio/hackmd#483]
`connection: dial tcp 10.254.0.82:8080: getsockopt: connection refuse`

Which Hackmd process(es) are responsible for this?

**Comment by jackycute** [comment]
Hi @JJediny 
It depends on which port you run HackMD on.
Default is `3000`.

**Comment by JJediny** [comment]
@jackycute the default port is set to 443 with self-signed cert and ssl options enabled in config.json. I was wondering if there was a stage of the deployment that was making an outbound tcp call for some external resource? If not feel free to close

**Comment by jackycute** [comment]
Hey @JJediny 
I don't think we call any other port out in any stage.
Re-open if anyone find we do.
