### ISSUE TITLE
can't run HackMD in c9.io

### ISSUE THREAD

**Issue by jojify** [hackmdio/hackmd#485]
I am trying to run hackmd in cloud development environment called c9.io. setup script run successfully. but when I run the command npm run build or use npm run dev, it throws error in numerous packages. Is it possible to run HackMD in c9.io

**Comment by Yukaii** [comment]
I've just tried c9.io, and it's possible. But the production build (`npm run build`) is unacceptably slow for the free account 😛 .

### Instructions

1. Start a new workspace with node.js template
    ![screen shot 2017-06-17 at 9 49 09 pm](https://user-images.githubusercontent.com/4230968/27253432-446c0d04-53a7-11e7-9314-0910a9d01e4d.png)
2. Install node version **6.x or up** with preinstalled nvm on c9.io:
    ```bash
    nvm install 6.11.0
    nvm alias default 6.11.0
    nvm use default
    ```
3. Run the setup script and build assets
    ```bash
    ./bin/setup
    npm run dev
    npm run start # in a separate terminal
    ```
4. Preview running application
    ![screen shot 2017-06-17 at 9 56 28 pm](https://user-images.githubusercontent.com/4230968/27253477-db59cce2-53a7-11e7-9a2e-0b1349c04290.png)

And that's it!

![screen shot 2017-06-17 at 9 58 43 pm](https://user-images.githubusercontent.com/4230968/27253490-2ec06026-53a8-11e7-81fd-04fe8329e244.png)

**Comment by SISheogorath** [comment]
Close for now.

If there are still questions, feel free to reopen.
