### ISSUE TITLE
Listed checkbox data broken next Line in editor

### ISSUE THREAD

**Issue by wubaibai** [hackmdio/hackmd#489]
Below Data Format will broken Editor since 6/17, 2017

Type below content first
```
- [ ] [API] Some texts
```

Then click Enter (it will duplicated first line), but yesterday only duplicated `- [ ] `
```
- [ ] [API] Some texts
- [ ] [API] Some texts
```

Then Click Enter Again
```
Editor goes black. 
```

**Comment by jackycute** [comment]
Issue confirmed.
Fixed in https://github.com/hackmdio/CodeMirror/commit/a1e8c5cdc2b6a669b18d45b680865d2f052911fb
