### ISSUE TITLE
Update shell scripts to use /usr/bin/env

### ISSUE THREAD

**Issue by xorander00** [hackmdio/hackmd#490]
Hi, great project :) I'm evaluating it now as a replacement for StackEdit.

I'm attempting to install on FreeBSD, but it fails because the shell scripts use #!/bin/bash as the shebang.  Bash is not guaranteed to be in /bin/bash, since FreeBSD better enforces separation between the base system and additional local packages.  Bash is in /usr/local/bin/bash.

The fix is to change the shebang line in the shell scripts, which in my case was release.sh for codemirror, to: #!/usr/bin/env bash

**Comment by SISheogorath** [comment]
If the issue still persists, please open an issue on the upstream repository.
