### ISSUE TITLE
[Design suggestion] Make "New note" pop

### ISSUE THREAD

**Issue by tjohnell-handy** [hackmdio/hackmd#493]
Yes, pop. I know it's a trigger word, but in this case I think it really is required.  I hunted on the main page for several seconds trying to figure out how the heck I create a new note:

![image](https://user-images.githubusercontent.com/13623283/27354879-22b31216-55d7-11e7-8682-c36100c37128.png)

Seems like it should be a large green/button, front and center.

**Comment by geekyd** [comment]
I would like to work on this. Please assign this issue to me.

**Comment by ccoenen** [comment]
It appears I can only assign an issue to people that are formally "on the team". Please feel free to work on this issue :-)
