### ISSUE TITLE
LDAP Auth / Strange Bug / user sessions

### ISSUE THREAD

**Issue by traedamatic** [hackmdio/hackmd#498]
Hello Community,
we installed hackmd on our server and enabled OpenLDAP for auth. Everything works fine we can login via Openldap and start creating or editing a note. 

But then a strange bug with the user sessions happens. I will explain it here step by step for better understanding:

1. Person A logs in via OpenLDAP account
2. hackmd shows the correct username in the top-right corner
3. Person B logs in via OpenLDAP account with **different computer**
4. Person A reloads hackmd. 
5. Suddenly, on Person A computer, hackmd shows the name of Person B in the top-right corner
6. Person B is still logged in as Person B.

Somehow the user session changed for Person A to Person B. This behavior can be reproduced every time a other user logs into hackmd.

Use the hackmd docker image latest version . There see the docker-compose.yml that we use to run hackmd:

```
version: '2'
services:
  hackmdPostgres:
    image: postgres
    environment:
      - POSTGRES_USER={{HMD_POSTGRES_USER}}
      - POSTGRES_PASSWORD={{HMD_POSTGRES_PASSWORD}}
      - POSTGRES_DB=hackmd
    volumes:
      - /var/hackmd-service/database:/var/lib/postgresql/data
  hackmd:
    image: hackmdio/hackmd:latest
    environment:
      - HMD_ALLOW_EMAIL_REGISTER={{HMD_ALLOW_EMAIL_REGISTER}}
      - HMD_DEFAULT_PERMISSION={{HMD_DEFAULT_PERMISSION}}
      - DEBUG={{HMD_DEBUG}}
      - POSTGRES_USER={{HMD_POSTGRES_USER}}
      - POSTGRES_PASSWORD={{HMD_POSTGRES_PASSWORD}}
      - HMD_ALLOW_ANONYMOUS={{HMD_ALLOW_ANONYMOUS}}
      - HMD_EMAIL={{HMD_EMAIL}}
      - HMD_LDAP_PROVIDERNAME={{HMD_LDAP_PROVIDERNAME}}
      - HMD_LDAP_TOKENSECRET={{HMD_LDAP_TOKENSECRET}}
      - HMD_LDAP_URL={{HMD_LDAP_URL}}
      - HMD_LDAP_SEARCHBASE={{HMD_LDAP_SEARCHBASE}}
      - HMD_LDAP_SEARCHATTRIBUTES={{HMD_LDAP_SEARCHATTRIBUTES}}
      - HMD_LDAP_SEARCHFILTER={{HMD_LDAP_SEARCHFILTER}}
      - HMD_LDAP_BINDDN={{HMD_LDAP_BINDDN}}
      - HMD_LDAP_BINDCREDENTIALS={{HMD_LDAP_BINDCREDENTIALS}}
    links:
      - hackmdPostgres:hackmdPostgres
    ports:
      - "{{HMD_HOST_PORT}}:3000"
``` 
Does anyone have a solution for this very strange behavior?

bye,
nicolas

**Comment by SISheogorath** [comment]
Sounds a little bit like https://github.com/hackmdio/hackmd/issues/432

Do you have an `uid` field in your LDAP setup?

**Comment by SISheogorath** [comment]
Feel free to reopen if the issue is not related to #432
