### ISSUE TITLE
Deploying to Heroku Problems :(

### ISSUE THREAD

**Issue by f3r** [hackmdio/hackmd#500]
Hi guys, 

We have been having problems running hackmd in production since a few weeks ago. We have a deployed instance in heroku that runs with cedar-16 stack (node v8+) and there are two main issues that kept us from updating hackmd:

The first one is [an error in UWS at boottime](https://github.com/uNetworking/bindings/issues/37) which has to do with UWS not having the right compiled version for node's latest ABI (57).

The second one has to do with [this line](https://github.com/hackmdio/hackmd/blob/master/app.js#L40):

```
ejs.renderFile(constpath, data, {}, function (err, str) {
  if (err) throw new Error(err)
  fs.writeFileSync(path.join(__dirname, './public/build/constant.js'), str)
})
```

Seems like when you start hackmd, it will create a file named `./public/build/constant.js` that contains something along the lines of:

```
window.domain = 'your.domain.com'
window.urlpath = ''
window.debug = false
window.version = '0.5.1'

window.GOOGLE_API_KEY = ''
window.GOOGLE_CLIENT_ID = ''
window.DROPBOX_APP_KEY = ''
```

The problem is that, as you may know, heroku's file system is READ-ONLY. Therefore I can't start my server because when it tries to start it in heroku, `writeFileSync` will throw an exception.

I'd suggest wrapping `fs.writeFileSync(path.join(__dirname, './public/build/constant.js'), str)` in a try...catch block and managing this case. Seems to me that this way of passing data to all of the views needs to be refactored, but i'm not familiar with the codebase enough to suggest how.

Thankks guys!!

**Comment by f3r** [comment]
```
2017-06-30T16:10:54.553Z - error: uncaughtException: ENOENT: no such file or directory, open '/app/public/build/constant.js' d
ate=Fri Jun 30 2017 16:10:54 GMT+0000 (UTC), pid=17, uid=44785, gid=44785, cwd=/app, execP
ath=/app/.heroku/node/bin/node, 
version=v8.1.3, 
argv=[/app/.heroku/node/bin/node, 
/app/app.js], 
rss=84848640, 
heapTotal=73424896, 
heapUsed=45117488, 
external=132986, 
loadavg=[17.814453125, 
11.29248046875, 
10.35400390625], 
uptime=692332, 
trace=[column=18, 
file=fs.js, 
function=Object.fs.openSync, 
line=651, 
method=fs.openSync, 
native=false, 
column=33, 
file=fs.js, 
function=Object.fs.writeFileSync, 
line=1300, 
method=fs.writeFileSync, 
native=false, 
column=6, 
file=/app/app.js, 
function=null, 
line=42, 
method=null, 
native=false, 
column=10, 
file=/app/node_modules/ejs/lib/ejs.js, 
function=tryHandleCache, 
line=208, 
method=null, 
native=false, 
column=10, 
file=/app/node_modules/ejs/lib/ejs.js, 
function=Object.exports.renderFile, 
line=412, 
method=exports.renderFile, 
native=false, 
column=5, 
file=/app/app.js, 
function=, 
line=40, 
method=null, 
native=false, 
column=30, 
file=module.js, 
function=Module._compile, 
line=569, 
method=_compile, 
native=false, 
column=10, 
file=module.js, 
function=Object.Module._extensions..js, 
line=580, 
method=Module._extensions..js, 
native=false, 
column=32, 
file=module.js, 
function=Module.load, 
line=503, 
method=load, 
native=false, 
column=12, 
file=module.js, 
function=tryModuleLoad, 
line=466, 
method=null, 
native=false, 
column=3, 
file=module.js, 
function=Function.Module._load, 
line=458, 
method=Module._load, 
native=false, 
column=10, 
file=module.js, 
function=Function.Module.runMain, 
line=605, 
method=Module.runMain, 
native=false, 
column=16, 
file=bootstrap_node.js, 
function=startup, 
line=158, 
method=null, 
native=false, 
column=3, 
file=bootstrap_node.js, 
function=null, 
line=575, 
method=null, 
native=false], 
stack=[
  Error: ENOENT: no such file or directory, open '/app/public/build/constant.js',     
  at Object.fs.openSync (fs.js:651:18),     
  at Object.fs.writeFileSync (fs.js:1300:33),     
  at /app/app.js:42:6,     
  at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:208:10),     
  at Object.exports.renderFile (/app/node_modules/ejs/lib/ejs.js:412:10),     
  at Object.<anonymous> (/app/app.js:40:5),     
  at Module._compile (module.js:569:30),     
  at Object.Module._extensions..js (module.js:580:10),     
  at Module.load (module.js:503:32),     
  at tryModuleLoad (module.js:466:12),     
  at Function.Module._load (module.js:458:3),     
  at Function.Module.runMain (module.js:605:10),     
  at startup (bootstrap_node.js:158:16),     
  at bootstrap_node.js:575:3]
```

**Comment by f3r** [comment]
If any of you have this problem, you can [follow this guide](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) and set your node version to "7.10.0", which is the last version with ABI 51

**Comment by SISheogorath** [comment]
@f3r How did you patch the missing write permission for your instance?

And is the current master branch working?  (related to the ABI issue)

**Comment by SISheogorath** [comment]
I worked a little bit on this issue and came to a completely different conclusion: The problem is not that the directory is not writeable. It's caused by the fact that the build process aborts without causing an error message and this way never creates the `./public/build` directory.

Which also means it's never actually deployable this way.

Please verify that `./public/build` exists on your deployment. Otherwise, you should use the docker image or a more powerful machine.

**Comment by SISheogorath** [comment]
To build the current version of HackMD on heroku please **don't** use the Heroku default settings. We recommend to use the deploy key in the README.

If you already have a version running, please use the same buildpacks as the app.json suggests:

https://github.com/hackmdio/hackmd/blob/1a4800e21a2d10b51ff8464804b877b384662eea/app.json#L151-L158

This should fix this problem
