### ISSUE TITLE
刪除上傳到 imgur 的圖片

### ISSUE THREAD

**Issue by sss63232** [hackmdio/hackmd#501]
我是用拖曳的方式插入圖片，
但是不小心拖錯了...

請問有辦法刪除上傳到 imgur 上的圖片嗎？

**Comment by jackycute** [comment]
您好，這部分請至以下網頁向 imgur 請求刪除
http://imgur.com/removalrequest

**Comment by sss63232** [comment]
了解了，謝謝您！
