### ISSUE TITLE
Ignores $NODE_ENV

### ISSUE THREAD

**Issue by brandoncurtis** [hackmdio/hackmd#504]
I'm using the current master, commit d1d6d58.  In my config.json, I have configurations listed for `test`, `production`, and `development`.  Regardless of how I set the `NODE_ENV` environmental variable, the `development` configuration is used (I see that this code was recently refactored in ecb05336055a37ba8a03c119995cd37d96aad90d, and that `development` is the fallback).

This previously worked in v0.5.1 51cdd433aa2d03723801cf08d715689ebaeb0e6b.

**Comment by SISheogorath** [comment]
The only reason I see is a problem with:

https://github.com/hackmdio/hackmd/blob/ecb05336055a37ba8a03c119995cd37d96aad90d/lib/config/index.js#L21

If the issue still exists, can you please provide your config.json?

**Comment by SISheogorath** [comment]
Closing for now. If the problem appears again, feel free to reopen the issue.
