### ISSUE TITLE
support for hovercraft in slide mode

### ISSUE THREAD

**Issue by MoritzFago** [hackmdio/hackmd#512]
[Hovercraft](https://github.com/regebro/hovercraft) is a cool tool to create 3d presentations, maybe it could be a future feature, because there isn't a collaborative editing tool.

**Comment by jackycute** [comment]
Hi @MoritzFago 
Hovercraft seems like a good one!
Thanks for telling us about it.

But I'm kind of busy recently, so PR welcome.

**Comment by SISheogorath** [comment]
> Hovercraft! is a tool to make impress.js presentations from reStructuredText. 

Since HackMD is a markdown editor I'm not sure if it's the right platform.
