### ISSUE TITLE
keybindings macOS

### ISSUE THREAD

**Issue by MoritzFago** [hackmdio/hackmd#513]
the sublime keybindings doesn't work for macOS users.

**Comment by jackycute** [comment]
Hi @MoritzFago 
Please provide more detail about what sublime keybinding not working on macOS.

And it actually the keybinding similar to the sublime, not totally the same.
See more in here: https://codemirror.net/demo/sublime.html

**Comment by ccoenen** [comment]
I'm going to close this for now. Please feel free to reopen this issue if it is still a problem!
