### ISSUE TITLE
Weird Home and End key behaviour

### ISSUE THREAD

**Issue by ccoenen** [hackmdio/hackmd#514]
I use the <kbd>Home</kbd> and <kbd>End</kbd> keys a lot. They don't work as expected, though. This throws me off multiple times a day.

## what I do

Suppose, you edit a regular paragraph of text, which spans a few lines on your screen. What I mean is a block of text that is not broken by any newlines - it is just automatically flowing into the next line(s). You are in the middle of this paragraph and Press <kbd>Home</kbd>.

## what I expect

behaviour in pretty much every single editor I use is "jumping to the beginning of the current line within the paragraph on screen". I will stay at the very same vertical position, but my horizontal position will be the first character there.

## what happens

Right now, the key will put me to the very first character in the whole block of text, so I am actually jumping "up" speaking of visible lines.

I presume this might be an upstream change to CodeMirror, but I wasn't certain, so I posted it here, first.

**Comment by jackycute** [comment]
Hi @ccoenen 
Thanks for telling us this problem.
We will investigate soon.

**Comment by jackycute** [comment]
Fixed in 2bdccd39964c8f6f643fd72ed7bdb648378068f8
