### ISSUE TITLE
file:// hyperlink markup is not translated

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#518]
Screenshot: 
![_133](https://user-images.githubusercontent.com/13408130/28489799-73db5c62-6efe-11e7-9567-f5f2d8650073.png)

Probably intentionally disabled due to security reasons, but it still good to support it.

**Comment by jackycute** [comment]
Hi @Lin-Buo-Ren 
The protocol starts with `vbscript`, `javascript`, `file`, `data` might contain XSS security issue.
So it've been disabled by default from our parser in here:
https://github.com/markdown-it/markdown-it/blob/c9199b582dbe80fbbed0a0bcb72b4080d864250c/lib/index.js#L32

**Comment by Lin-Buo-Ren** [comment]
I'm fine about it then, thanks for the info!
