### ISSUE TITLE
ODF -> ODT

### ISSUE THREAD

**Issue by zuphilip** [hackmdio/hackmd#519]
The label for the LibreOffice document is currently `ODF` but it should be rather `ODT` in the [online editor](https://hackmd.io/).

![odf-hackmd](https://user-images.githubusercontent.com/5199995/28636134-7a72f7fa-723d-11e7-908e-feb34136232f.png)

**Comment by ccoenen** [comment]
(sorry, I added the label in error, I believe the required lines are not yet part of this git repo)

**Comment by jackycute** [comment]
For better management and avoid confusing, please report any further issue in https://github.com/hackmdio/hackmd-io-issues

Thanks!
