### ISSUE TITLE
Editor Toolbar

### ISSUE THREAD

**Issue by davidmehren** [hackmdio/hackmd#523]
Hi!
I noticed that the hosted version on hackmd.io features a toolbar in the editor, for text fomatting, inserting images etc.
This feature does not seem to be present in version 0.5.1.
Is it going to be included in a later version? Is it an exclusive feature for hackmd.io?
Thanks for the info.

**Comment by MartB** [comment]
Duplicate of https://github.com/hackmdio/hackmd/issues/375

**Comment by KrzysztofMadejski** [comment]
So this issue should be closed. @davidmehren ?
