### ISSUE TITLE
allow non-english spell check

### ISSUE THREAD

**Issue by azrdev** [hackmdio/hackmd#524]
As it seems, spell check can only correct the english language, I couldn't find any language selection. It should support others, too. The easiest way might be the in-browser check, see #150

**Comment by ccoenen** [comment]
Hi, I'm also looking forward to spell checking in another language than english. I believe this is the point of #150 exactly, so I'll close this as a duplicate. Please feel free to comment on this issue or reopen this. You may of course also join the discussion in #150!
