### ISSUE TITLE
add SVG support?

### ISSUE THREAD

**Issue by foojiawen** [hackmdio/hackmd#525]

**Comment by SISheogorath** [comment]
Can you please be a bit more descriptive?

What did you do?
What did happened?
What did you expect?

What version of HackMD are you using?
Can you file an example note on https://HackMD.io?

**Comment by ccoenen** [comment]
not neccessarily what the author of the issue intended, but [draw.io](https://github.com/jgraph/drawio) is a pretty interesting open source tool for in-browser-drawing.

**Comment by ccoenen** [comment]
I'm voting to bump this one more time (for notification) and close it in ~2-3 weeks. That is, unless any other feedback is given.

**Comment by ccoenen** [comment]
It is not really clear what you have in mind, there's many routes that could be taken. I'm closing this for now, feel free to jump back into the discussion at any point!

**Comment by TimDaub** [comment]
I'm interested in adding draw io support too!

**Comment by lfuhr** [comment]
On hackmd.io if I paste some svg (which is html) it will be filtered out. So that it does not appear on the page.
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
<g><path d="M500,10C229.4,10,10,229.4,10,500c0,270.6,219.4,490,490,490c270.6,0,490-219.4,490-490C990,229.4,770.6,10,500,10L500,10z M799,799c-38.8,38.9-84.1,69.3-134.4,90.6c-52.1,22-107.4,33.2-164.6,33.2c-57.1,0-112.5-11.2-164.6-33.2c-50.3-21.3-95.6-51.8-134.4-90.6c-38.9-38.8-69.3-84.1-90.6-134.4c-22-52.1-33.2-107.4-33.2-164.6c0-57.1,11.2-112.5,33.2-164.6c21.3-50.3,51.8-95.6,90.6-134.4c38.9-38.9,84.1-69.3,134.4-90.6c52.1-22,107.4-33.2,164.6-33.2c57.1,0,112.5,11.2,164.6,33.2c50.3,21.3,95.6,51.8,134.4,90.6c38.8,38.9,69.3,84.1,90.6,134.4c22,52.1,33.2,107.4,33.2,164.6c0,57.1-11.2,112.5-33.2,164.6C868.3,714.9,837.8,760.1,799,799L799,799z M727.6,315.4L426.9,616.2L297,486.3c-12.6-12.6-33-12.6-45.6,0c-12.6,12.6-12.6,33,0,45.6l152.6,152.6c12.6,12.6,33,12.6,45.6,0L773.2,361c12.6-12.6,12.6-33,0-45.6C760.6,302.8,740.2,302.8,727.6,315.4L727.6,315.4z"/></g>
</svg>
```
I think it would be a major improvement
