### ISSUE TITLE
Ada syntax highlighting

### ISSUE THREAD

**Issue by raph-amiard** [hackmdio/hackmd#532]
Hi, 

I'm having a great time using hackmd, however I work a lot in Ada, and the language does not seem to be highlighted, neither in the editor nor in rendered markdown.

I understand that you use prism and highlight.js, and both support Ada, so I'm wondering what's the source of the problem.

I'm ready to make and contribute a fix ! However I would appreciate a few pointers :)

Thanks for a great product !

**Comment by SISheogorath** [comment]
We currently use the default `highlight.js` which only brings the "common languages" with it: https://highlightjs.org/download/

I'm not sure if we want to build an own version for HackMD, but maybe there is another way when you are creative. Feel free to contribute :)

**Comment by JohnAZoidberg** [comment]
`highlight.js` seems to bring quite a lot of languages with it and it seems that HackMD supports not just the list of "common languages" but some more. However some of the common languages like Java are not supported by HackMD.
Did you create your own bundle? Why not support all languages?

**Comment by SISheogorath** [comment]
We support `Java` code highlighting: https://hackmd.io/EYTgTAhgDAJjwFphhAMwQFhgdhkgrDGAlAGz7QDGwMAHFPvkA===

```
> hljs.listLanguages()
< (22) ["apache", "bash", "coffeescript", "cpp", "cs", "css", "diff", "http", "ini", "java", "javascript", "json", "makefile", "xml", "markdown", "nginx", "objectivec", "perl", "php", "python", "ruby", "sql"]
```

But not all languages are listed in the auto-completion in the editor right now. Maybe I do some investigation about it.

**Comment by JohnAZoidberg** [comment]
Hm, it seems that you are right - Java is indeed supported.

I did some digging:
1. In this file version 9.7.0 is still included https://github.com/hackmdio/hackmd/blob/d1d6d5810b12645ddb02275ce0c2498b2189a8a0/public/views/html.hbs#L23

2. This line seems to be responsible for what is shown in the auto-completion: https://github.com/hackmdio/hackmd/blob/f85d1d880114b6787fdb2bac488341776deaad3d/public/js/index.js#L96

3. Are you sure that `> hljs.listLanguages()` lists all supported languages? The output does not contain Haskell for example, but the auto-completion shows it and it actually gets highlighted. (I appended an example to [your](https://hackmd.io/EYTgTAhgDAJjwFphhAMwQFhgdhkgrDGAlAGz7QDGwMAHFPvkA===) note)

**Comment by SISheogorath** [comment]
True. Haskell highlighting is supported :confused: 

Reason: Besides highlight.js there is also [prismjs](http://prismjs.com) used, which provides haskill language. See the output of `Prism.languages`. 

We should maybe find a way to uniform it a bit more :thinking:

**Comment by ccoenen** [comment]
I believe ada is supported via prismjs, it is at least somewhat highlighted in the rendered HTML. Note the use of the ` ```ada ` at the beginning of the code-block.

example: https://hackmd.io/EwYwzARgLAjAhnAtMAJmADIqcYHZEQBmArMIoSgKZSXFgwAcwhUQA===

**Comment by ccoenen** [comment]
I'm closing this for now, I believe it should work. This ticket has not been updated for two weeks.

If your problem is not resolved or if new information is available, feel free to post here and we'll reopen it!

**Comment by raph-amiard** [comment]
Hi! Very old issue I know, but Ada code is still not correctly highlighted - and you can visit 
https://hackmd.io/LDtBqi0wShe_Uv3k5TGC9A

I'm ready to investigate and maybe do a pull request
