### ISSUE TITLE
Embedded videos support

### ISSUE THREAD

**Issue by zipang** [hackmdio/hackmd#533]
Sure, it's not a common part of any markdown standard, but we should support it !
If we support images, then why not videos ?
It happens that the node module on which you rely to transform markdown is pluggable and has an extension for videos : https://github.com/brianjgeiger/markdown-it-video

**Comment by SISheogorath** [comment]
We currently provide a different way of embedding: https://hackmd.io/features#youtube

I see the charm of this way of embedding, Pull requests are welcome :+1:

**Comment by zipang** [comment]
Hi @SISheogorath !
I did some tests with `markdown-it-video` in a standalone SimpleMDE editor.
But there are big issues with it, mainly an infinite loop that freezes the browser while rendering.
I've looked at the source and your solution based on the markdown-it-regexp plugin is better at the moment !
We can close this issue right now. :)

**Comment by John-LittleBearLabs** [comment]
It looks like that only supports videos on YouTube and Vimeo.
There's no way to tell Hackmd it's OK to render a raw `<video>` element as one could with, say, cmark?
