### ISSUE TITLE
Login Using Email & Password

### ISSUE THREAD

**Issue by RoyiAvital** [hackmdio/hackmd#539]
Hello,

Could you allow creating an account based on Email + Password?

Thank You.

**Comment by ccoenen** [comment]
It is already in there, it needs to be activated in the config, though! If you host your own installation, please change your `config.json` to contain `"email": true` somewhere in here (same hierarchical level as `"facebook"` or `"db"`): 
https://github.com/hackmdio/hackmd/blob/master/config.json.example#L15-L66

**Comment by RoyiAvital** [comment]
I was talking about the Online Application you have on hackmd.io.

It doesn't allow using Email for Sign In.

**Comment by ccoenen** [comment]
That is a deliberate choice, I do not believe they will change their minds. There was a short statement about it here: https://github.com/hackmdio/hackmd/issues/36#issuecomment-254024336

**Comment by ccoenen** [comment]
I don't know if there are other public hosts, perhaps someone else knows more about that.

The second question is hard to anwer.

The underlying technologies are NodeJS and an SQL database (most commonly either PostgreSQL or MySQL). How hard setup is, depends on two things: The number of hoops your web hosting company makes you jump through, and your experience with JavaScript and/or web servers. If you have not heard either of these technologies, you may need some guidance or at least you should plan for extended google-sessions.

For your own server, follow the [setup instructions](https://github.com/hackmdio/hackmd/wiki/Get-started).

If you don't plan on managing your own server, I believe this can be [deployed to Heroku](https://github.com/hackmdio/hackmd/wiki/Heroku-Deployment) (basically a provider for web servers) but I haven't tried that, so I'm not exactly sure how well it works. Also the free offer of heroku might or might not be satisfactory for you. If you use this alone, it will most certainly be alright. If you are planning on using it with a large number of people, you might want to spend a few bucks for hosting.

**Comment by SISheogorath** [comment]
As already mentioned this won't be fixed upstream for now. https://github.com/hackmdio/hackmd/issues/36#issuecomment-254024336
