### ISSUE TITLE
[Feature Request] 嵌入圖片時希望可以只調整比例

### ISSUE THREAD

**Issue by alan23273850** [hackmdio/hackmd#540]
開發團隊您好：

　　近日使用圖片嵌入時，有發現可以調整大小的格式：![](https://xxxxxx.jpg =\_\_\_x\_\_\_)，後面可填入想要的長寬像素。然而，通常在調整大小的時候會希望比例維持不變，如此一來便必須先查看原始檔案的大小，分別手動乘以固定比例之後再行填入，如此一來步驟會稍嫌繁複且不直覺。
　　建議可以新增格式：![](https://xxxxxx.jpg =___)，也就是說當尺寸不出現 x 符號時便代表百分比數值，例如：![](https://xxxxxx.jpg =80) 意思就是說我希望這個圖片縮放成原來的 0.8 倍。請問這個提案是否可行？

謝謝，
Alan Tsai

**Comment by SISheogorath** [comment]
你好 Alan，
我是德国人。不好意思,我会说一点汉语。你會說英語？

I hope so, otherwise please refer to google translate (I did so with your text :smile:).

I created this little example how to use percentage with the `![](https://xxxxxx.jpg __x__)` writing: https://hackmd.io/IwDgrAxhDMBGAsBaSsyPhYATRJ4DN9FpgB2AU2nwlhBAENSg?edit

When I got you right you request to automatically use the percentage when you don't use the second `x__` part?

**Comment by alan23273850** [comment]
Oh, oh, oh, thank you very much for your reply!!! I have seen your example and it really scales the picture with percentage mode! Although only filling one blank for both height and width can be more convenient, it is not necessary. Your example best answers my question, so this issue can be closed. Thanks!

**Comment by yenskr** [comment]
Hi @SISheogorath  sorry to bother, but I found the example you provide has been modified and now is dead. Can you give the feasible example again? (and maybe set it to uneditable? :) )

> 你好 Alan，
> 我是德国人。不好意思,我会说一点汉语。你會說英語？
> 
> I hope so, otherwise please refer to google translate (I did so with your text 😄).
> 
> I created this little example how to use percentage with the `![](https://xxxxxx.jpg __x__)` writing: https://hackmd.io/IwDgrAxhDMBGAsBaSsyPhYATRJ4DN9FpgB2AU2nwlhBAENSg?edit
> 
> When I got you right you request to automatically use the percentage when you don't use the second `x__` part?

**Comment by jackycute** [comment]
Hi @yenskr 
You can try this:
```
![](https://xxxxxx.jpg =80%x)
```

Then the image will be showed in 80% of the page width and the height will be kept in ratio.

**Comment by yenskr** [comment]
Thank you @jackycute !!!
It really should be written in the [feature manual](https://hackmd.io/s/features). lol
