### ISSUE TITLE
Export of Reveal.js slides

### ISSUE THREAD

**Issue by zeigerpuppy** [hackmdio/hackmd#545]
It would be great to be able to export a .zip file with all the files required for an offline reveal.js slide presentation.

This could then be loaded from a local folder.

To achieve this the following would be required:

1. export `.md` file
2. export `js` and `css` folders for reveal.js
3. export uploaded images
4. rewrite links (if necessary), actually image upload links should be relative anyway.

This would be really useful as a backup for presentations

**Comment by SISheogorath** [comment]
As a workaround, you can print the slides to PDF. See https://github.com/hackmdio/hackmd/issues/33#issuecomment-267508760

**Comment by Marwe** [comment]
use "save as" in your browser, e.g via right-click or ctrl-s

**Comment by Profpatsch** [comment]
`wget --recursive --convert-links` did the trick for me.

**Comment by SISheogorath** [comment]
With #863 We should provide an easy way to print slides and this way export them.

I don't see the need to add a more complex export. 

If one wants the slides offline, we offer to download the markdown. Integrating it in his revealjs should be doable or they can just use PDF based slides or the online version.

**Comment by zeigerpuppy** [comment]
I have found a way to save an archive of a slide presentation built with codimd.
I had some trouble getting wget to pull the images from the presentation (I think because the links to the images are in markdown).

So, it's a three step process but it's quick and works well.
Let's say you have a slide show at https://codimd.server.net/p/S1PIjfhM8#/

1. use `wget` to grab the files and the requisites (.css and .js)
  - your presentation will end up as `p/S1PIjfhM8.html`

  ```
  wget   --recursive   --no-clobber   --page-requisites   --html-extension   --convert-links   --domains codimd.server.net https://codimd.server.net/p/S1PIjfhM8#/
  ```
2. use the firefox plugin: [ImageAssistant Batch Image Downloader](https://addons.mozilla.org/en-US/firefox/addon/ia-batch-image-downloader/?src=search)
  - it gets all images on page (including .svg)
  - save them in a folder called `uploads` in the web archive root

3. we need to use `sed` to change the links in the html file to relative links so that they point to the images

  ```
  cd p
  sed -i .bak 's|/uploads/upload_|../uploads/upload_|g' S1PIjfhM8.html
  ```

**Comment by ostrokach** [comment]
I have had success with the [Save All Resources](https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb) chrome extension. The only issue is that it uses the browser cache for all external assets, so if you purge your cache (for example by pressing `Ctrl + Shift + r`, the offline presentation stops working.

**Comment by cboulanger** [comment]
As far as this is useful for anyone, I put together a script that lets you create a self-contained copy of the Reveal.js presentation integrated in the HedgeDoc platform, at least as it is implemented on https://pad.gwdg.de. The code is [here](https://gist.github.com/cboulanger/bd9300ad4481d29b87c3b35a5fcc798c). It only works with https://pad.gwdg.de but should give you a clue how to write a script for other Reveal.js integrations.
