### ISSUE TITLE
Document "fork" into two versions

### ISSUE THREAD

**Issue by pellaeon** [hackmdio/hackmd#548]
Sometimes when many people are typing, the same document "fork" into 2 different line of revision history.

I will DM the problematic document to you on Twitter.

**Comment by SISheogorath** [comment]
This sounds like a crazy problem. What happens when you open the document in a new tab? Is there still a "fork" in the revisions?

Did you edit the same position in text over and over again or did it happen when you edit in different areas at the same time?

I mainly ask to see where the bug is located.

**Comment by pellaeon** [comment]
Sorry for missing out the details.

There are ~10 devices on the same document. One group (let's name it A) of them sees one version of the document, another group (name it B) of them sees another version of the document. 

Group A cannot see anything Group B is typing, nor vice versa.

I tested 2 devices in different groups:
1. reload the tab: still see the same version
2. reload and clear cache (Ctrl+F5) : still see the same version
3. open the document in another browser: still see the same version

Did you edit the same position in text over and over again or did it happen when you edit in different areas at the same time?
-> Mostly 2 people typing at different areas at the same time, but I'm not really sure, someone may be editing small scale in the same area.

Not sure if it'll help:
- All devices on the same document use the same public IP with NAT
- I'm guessing, perhaps 2 devices went offline at roughly the same time, and they typed in different things, when they connect again, there's a conflict.

Also, after roughly 30 minutes, suddenly group B's version suddenly disappers, i.e. it suddenly became group A's version, and group B's edit is lost.

**Comment by SISheogorath** [comment]
When you check the revisions page of the Pad, are there both versions listed?

If it's possible to share the documents link, that would be helpful for us to see what went wrong.

**Comment by SISheogorath** [comment]
@pellaeon I checked the document and was unable to find suspicious things.

The revision history looks clean and straight. Right now, I can't explain why it happened.

**Comment by SISheogorath** [comment]
If the issue appears again, feel free to reopen :)
