### ISSUE TITLE
GitLab OAuth only works with gravatar enabled

### ISSUE THREAD

**Issue by smarrk** [hackmdio/hackmd#549]
Hi, 

we just noticed that OAuth via GitLab only works correctly if Gravatar support is enabled in GitLab.

*Requirements:*  
* HackMD 0.5.1
* GitLab CE 9.5.5 (with Gravatar support disabled)

*Expected behaviour:*  
Login via GitLab username and password via "Sign In" button. Username is shown in the upper right of HackMD (replacing the login button).

*Actual behaviour:*  
Login via GitLab seems to succeed. Upper right button still shows "Sign In".

*Steps to reproduce:*  
1. Configure OAuth via GitLan as described in the documentation
1. Disable Gravatar support in GitLab
1. Login to HackMD via GitLab
    The login seems to succeed but you will still see the login button instead of the username
1. HackMD shows the following error
    `error: read me failed: TypeError: Cannot read property 'replace' of null`

After (re)enabling Gravatar support in GitLab login via OAuth succeeds without any errors.

**Comment by SISheogorath** [comment]
I guess, I found the issue:
https://github.com/hackmdio/hackmd/blob/master/lib/models/user.js#L105-L109

Is there a profile picture set for your account?

If not Gitlab maybe doesn't return an URL which casues the problem. A PR to patch this should land soon. It maybe can be backported but no promises.

**Comment by smarrk** [comment]
Thanks for reviewing this.

You're right: I currently don't have a profile picture set. If I do set a profile picture the login succeeds without error with both Gravatar support enabled and disabled.
