### ISSUE TITLE
Unable to paste from mobile

### ISSUE THREAD

**Issue by kiliankoe** [hackmdio/hackmd#551]
Hi,

absolutely ❤️ hackmd so far. I'm also really enjoying using it from a mobile device, but I just had some issues with trying to paste a copied URL from mobile safari on iOS 11 into a document.

On repeatedly tapping at the cursor position or trying to long-press no dialog prompting me to paste my clipboard contents popped up. What made the matter even worse is that after this I was unable to type any text at all. Reloading the page fixed that, until I again tried to paste.

Not quite sure how to debug this, but I'm definitely willing to try anything to bring further light into this. Thanks!

**Comment by SISheogorath** [comment]
Yes, this is a known problem.

Dublicate #263

**Comment by kiliankoe** [comment]
Oh, didn't find anything with a quick search. Thanks for pointing me towards the parent issue. I'll close this then (it's now linked anyways) 😊

**Comment by SISheogorath** [comment]
No problem, I needed 3 search terms myself 😄 

You're welcome!
