### ISSUE TITLE
Slide Mode Syntax Highlight Error

### ISSUE THREAD

**Issue by hortune** [hackmdio/hackmd#554]
I love to use hackmd to make slides.
However, in the code highlight area I wrote like
\``` clang
#include \<iostream\>
\```

it would represent as 
```
#include &lt; iostream&gt;
```
I think that there may be some escape character issue in it.

**Comment by SISheogorath** [comment]
I wonder how you produced it. Can you maybe extent this note: https://hackmd.io/CYTgHAjARmAMDMBaCB2ALMRaCsUBmiAhgKYraLCzZ7xh4gBs9UQA

In Firefox 55.0.3 on Fedora Linux 26 and Chromium Version 60.0.3112.113 on Fedora Linux 26 it looks totally fine.

On HackMD.io as well as my private instance.

What Version of HackMD are you running?

What browser are you using?

Do you run thought some kind of Reverse Proxy?

**Comment by hortune** [comment]
@SISheogorath Here's the slides that I had made.
https://hackmd.io/CYBgZiCcwBwGwFoDGAjGB2BAWAzDSCkOApkssAExwCsAjFiAIYxpA
You could see that some of the syntax works fine, however, others are broken.

**Comment by jackycute** [comment]
@hortune It was caused by the security fix for XSS in slide mode which escapes `<` and `>` twice.

Fixed in fe384d80bf03a4d33fd38500cbaaf2ec3abb8bdb

**Comment by jackycute** [comment]
Related to f2743ff8f87d79556ced7e038dd3486f19f116b0
