### ISSUE TITLE
target="_blank" doesn't work on side menu when in book mode

### ISSUE THREAD

**Issue by hugoinperson** [hackmdio/hackmd#556]
The page I tried to link on the side menu has `X-Frame-Options` set to `sameorigin`. Which means the embedded iframe won't be able to open on the right side. 

The code I used for the side menu is like this:
```
Links
---
- <a href="https://sample.domain" target="_blank">This is a link opens in a new tab</a>
```

Is there a way to open links in the new tab on the side menu? 
Or, to make the above code work?

**Comment by jackycute** [comment]
@hugoinperson Sorry for late reply.
There is a tricky way to achieve this.

If your link starts with http (non-SSL) in book mode, it will been opened in new tab (as design).
So even your link is in https, you can use its http variation as a workaround.

**Comment by jackycute** [comment]
Fixed, will deploy to site soon.
We've added a syntax allowing user to specified in which link they would like to open in new tab and also will be marked with an icon in the summary list.
Thanks @hugoinperson

**Comment by jackycute** [comment]
@hugoinperson 
Please take a look at: https://hackmd.io/book-example#external-link

**Comment by fweng322** [comment]
> @hugoinperson
> Please take a look at: https://hackmd.io/book-example#external-link

After exactly one year...
https://i.imgur.com/om6UtRy.png

It works, but it is... um... ugly and weird, I have to say.

**Comment by jackycute** [comment]
@fweng322 Thanks for telling us more.
Book mode currently not available in CodiMD, please report related issue here: https://github.com/hackmdio/hackmd-io-issues/issues

The `[target=_blank]` is intended for book mode, but I understand you might also publish that note. I think the better way is to hide that syntax in all conditions.
