### ISSUE TITLE
Greater-Than escape in style-CSS

### ISSUE THREAD

**Issue by Wolvereness** [hackmdio/hackmd#558]
The &gt; symbol is escaped in `<style> ` tagged CSS, making certain styles difficult (if not impossible). See https://github.com/hackmdio/hackmd/issues/209#issuecomment-333614484

As a security feature, it's not particularly useful, as https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Remote_style_sheet_part_2 still works.

**Comment by jackycute** [comment]
The style tag security risk has been revealed in #467

Also, this issue has been fixed in b0b417cefcc91b2c14f48d4b0b41008d1e12754c

**Comment by jackycute** [comment]
`@import` in style tag will been removed after d96385eafdc8e9c408088a3f95a60c9a0193ef67
