### ISSUE TITLE
Delete a note should also delete image uploaded to imgur

### ISSUE THREAD

**Issue by florentulve** [hackmdio/hackmd#559]
Or at least a way to delete image should be provided.

**Comment by ccoenen** [comment]
I'm not familiar with imgur, do you know if they offer some way of deleting images? So far, I thought it was a pretty permanent thing.

There's also a possibility that images are reused across documents (upload once, then copy the url to other documents) which is next to impossible to detect.

**Comment by jackycute** [comment]
Hi @florentulve 
Since the image upload is replying on imgur and we simply use the anonymous method to upload them.
So the images only can be deleted when you request to imgur.
See more here: https://imgur.com/removalrequest

**Comment by ccoenen** [comment]
I guess if someone wanted to put in the effort, it would probably get merged. Personally, I can't judge how much work that would be. I'm closing this topic for now.
