### ISSUE TITLE
rendering problem for MathJax after colon

### ISSUE THREAD

**Issue by leomao** [hackmdio/hackmd#56]
the following is not rendered correctly

```markdown
Testing:
    something strange with $\LaTeX$. QQ
```

BTW, this is really an amazing project!! :+1:

**Comment by jackycute** [comment]
Thanks for like it.
Issue confirmed, try to fix it now.

**Comment by jackycute** [comment]
Fixed in 2ad54c516a5c3cd88345b9c0f6e5a720050c935d
