### ISSUE TITLE
Disable PDF export by config

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd#561]
The PDF export is currently experimental and causes problems when running on Alpine Linux or other musl-based distros because phantomjs doesn't work.

By allow to disable this feature by a config value, the alpine build of https://github.com/hackmdio/docker-hackmd/pull/14 will no longer break.

**Comment by Hrafnkellos** [comment]
I'll take a quick look if i can help with this.

**Comment by Hrafnkellos** [comment]
This might be to much for me sorry ^^

**Comment by ccoenen** [comment]
No worries, thanks for taking a look anyway :-)

**Comment by SISheogorath** [comment]
I want to provide some hints for this issue.

A good point to start is:

https://github.com/hackmdio/hackmd/blob/ca959012047bef3c0b2dd6f2974a8373a6615125/lib/response.js#L5

Trace the variable it and you'll find an export function.

Also have a look at:

https://github.com/hackmdio/hackmd/blob/53c2d0b5ca5901c1d1cad819e2049b16fba18ea8/public/views/hackmd/header.ejs#L71-72

And last but not least have a good example PR like https://github.com/hackmdio/hackmd/pull/585 to see where and how to add options and config.

Hopefully this helps to make this change :)

**Comment by geekyd** [comment]
@SISheogorath I would like to work on this one.

**Comment by SISheogorath** [comment]
:+1: sounds good. Go for it!
