### ISSUE TITLE
Book Mode - making a heading a link causes it to disappear

### ISSUE THREAD

**Issue by edwag** [hackmdio/hackmd#572]
When creating a book, if you add a heading which is also a link\* and then view in Book Mode, the heading is not visible on the pane in the left hand side (though a heading with empty text _is_ created - the underline for it is visible). See [here](https://hackmd.io/BwQwjAnADBBMUFoIQGwgQFgKYQMYJDWAQBNcVcIAzWKgIyy2CA==) for an example.

It's not clear to me whether having a heading which is also a link is something that should be allowed in Book Mode (though I think I would personally like to have this), but the current behaviour doesn't seem correct.

\* i.e. something like `## [Link Heading](/features)`

**Comment by jackycute** [comment]
Fixed, will deploy to website soon.
Thanks @edwag
