### ISSUE TITLE
Empty export section should be hidden

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd#577]
When you run HackMD without external auth providers the export section exists but is empty. We shouldn't show an empty section.

![image](https://user-images.githubusercontent.com/8719867/31442135-b312409a-ae95-11e7-8ad6-2a18630c2e03.png)

This file should be the place to look for it: https://github.com/hackmdio/hackmd/blob/master/public/views/hackmd/header.ejs

**Comment by kunal12422** [comment]
@SISheogorath can I work on this?

**Comment by SISheogorath** [comment]
Sure :) Pull Request are welcome :heart: 

Feel free to ask if you have questions :smile:

**Comment by geekyd** [comment]
@kunal12422 Have you started working on this??
