### ISSUE TITLE
a commit has broken the view and edit feature

### ISSUE THREAD

**Issue by l12436** [hackmdio/hackmd#58]
commit a6d1bddf47f414b5af55797259ce29d26f632f59 (Updated other packages to lastest versions)  
broken the hackmd view and edit function.
I just revert this commit and everything work.

**Comment by l12436** [comment]
public/views/foot.ejs b/public/views/foot.ejs
this file causing infinite load in view and edit mode.

**Comment by jackycute** [comment]
Hi, did you install bower?
and please run `bower install` from the repo root.
We just transfer the client dependency to bower from recent commits

**Comment by l12436** [comment]
thanks for helping. now it works.
