### ISSUE TITLE
License Change Announcement

### ISSUE THREAD

**Issue by jackycute** [hackmdio/hackmd#580]
Dear Markdown hackers,

We propose a license change, from MIT to AGPL 3.0, for the open source project HackMD Community Edition (CE), and ask for your understanding and agreement.

Please read more here: https://hackmd.io/c/community-news/https%3A%2F%2Fhackmd.io%2Fs%2Fr1_4j9_hZ

We just created a [pull request](https://github.com/hackmdio/hackmd/pull/578), please leave a comment below the PR saying: 

**"I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD. 
Signed-off-by: Full Name <my_real@email.address>"**

Thank you again for your contribution to the project and the community.
Please let us know if you have any questions.

Best regards,
HackMD Team

**Comment by ccoenen** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Claudius Coenen opensource@amenthes.de
