### ISSUE TITLE
Don't enforce HSTS

### ISSUE THREAD

**Issue by SISheogorath** [hackmdio/hackmd#584]
Right now HSTS is configured statically. No way around.

https://github.com/hackmdio/hackmd/blob/c8d3951d321a4191f75a4589c33630c847098b57/app.js#L99-L104

We should allow users to disable HSTS or change the default values.

Pull Requests are welcome! :heart: 

If you have a question don't hesitate to contact us.

We are only one click away: 
[![Join the chat at https://gitter.im/hackmdio/hackmd][gitter-image]][gitter-url]

[gitter-image]: https://badges.gitter.im/Join%20Chat.svg
[gitter-url]: https://gitter.im/hackmdio/hackmd

**Comment by xxyy** [comment]
I'd like to take this.

**Comment by SISheogorath** [comment]
Go for it @xxyy :+1:
