### ISSUE TITLE
Is there any better ways to type algorithms in HackMD like latex?

### ISSUE THREAD

**Issue by onlyfly34** [hackmdio/hackmd#590]
I've search for ways to type algorithms like this:
![](https://i.imgur.com/hZwGEDz.png)

But now HackMD doesn't support latex syntax like this:
`\usepackage[ruled,vlined]{algorithm2e}`

Any suggestions?

**Comment by Marwe** [comment]
more complex things can be compiled externally, e.g. with pandoc and proper commandline options and/or a custom latex template including your additional packages.

**Comment by ccoenen** [comment]
I wonder if we should move Q&A things over to something like StackOverflow. I'm not really sure how long to keep these open, and they're not really issues that have a definitive resolution.

I'm closing this one for now, please feel free to post more suggestions, this is not meant to shut down the discussion.

**Comment by enricobottazzi** [comment]
Is there any way to do it today?

**Comment by Mikerah** [comment]
Bumping
