### ISSUE TITLE
Revision window showing empty revision

### ISSUE THREAD

**Issue by jmuheim** [hackmdio/hackmd#621]
In my [note](https://hackmd.io/IYEwjA7ATMBswFpZliBAWApiWCBGmmUCAxgAwBms6YAnJmcJEA==?view), the revision shows an empty revision:

![image](https://user-images.githubusercontent.com/1814983/32658977-bb348fa0-c61c-11e7-9c38-aa9472a4c73a.png)

Is this a bug?

**Comment by ccoenen** [comment]
I believe this to be a bug. Could you tell us a little more about your setup? Specifically which version of HackMD is running (for Example "Version 0.5.1" or the git-hash).

I also sometimes find problems with the various databases that HackMD runs on. Can you tell us, which database is running (Postgres/MySQL/MariaDB)?

**Comment by jmuheim** [comment]
I provided a link to the pen in the original post. It's on the official HackMD website.

**Comment by ccoenen** [comment]
But the note contains lots of content - so there should be more history entries, right?

**Comment by SISheogorath** [comment]
Oh yes, that's a bug. @jackycute 

But a HackMD.io bug. Doesn't appear in HackMD CE.

**Comment by jackycute** [comment]
Issue confirmed and solved.
This was caused by too many concurrent db connections.

**Comment by matclab** [comment]
@jackycute could you expand on the bug resolution ? I've got the same problem on HackMD.io today and on a local instance, either with 0.5.1 or master.

Or if the behavior is intendedn I probably didn't understand when a revision is created beyond the first empty revision. 

Thanks for any hint.

**Comment by jackycute** [comment]
@matclab Sorry for late reply.
If your note did have a revision then it's not related to this issue.

The revision creation policy is right here:
https://github.com/hackmdio/hackmd/blob/master/lib/models/revision.js#L200
Or say: note not been modified for 5 mins or not save for 10 mins will make a revision.

Thanks.

**Comment by matclab** [comment]
@jackycute Thanks a lot. I was too impatient. Sorry for the noise.
