### ISSUE TITLE
Getting the note ID from the Referer header is not reliable

### ISSUE THREAD

**Issue by jbg** [hackmdio/hackmd#623]
The server seems to parse the `Referer` header to find the note ID. In my installation of Firefox Nightly and Chromium Dev Channel this does not work, as this header is not sent with the WebSocket connection. IMO it would be better if the note ID was explicitly sent when the WebSocket connection is brought up.

Relevant code is the extractNoteIdFromSocket function here:
https://github.com/hackmdio/hackmd/blob/ea9b1557f9834b2b140bd9b07488b5fca3953791/lib/realtime.js#L274-L285

**Comment by a60814billy** [comment]
Below is my test environment

* macOS 10.13.1 
* Firefox Nightly 59.0a1 (2017-11-17 64-bit)
* Chromium Version 64.0.3272.0 (Developer Build) (64-bit)

In my environment, both of them send referer.
maybe you installed some extensions or plugins,
the extension/plugin block browser to send referer information to the server ?

**Comment by jbg** [comment]
Please understand that many environments (including some corporate firewalls, security software, privacy-sensitive users, unusual browsers such as those embedded into some applications) do not send this header, or do not send the full path in it.

It is broken to rely on the Referer header in this way.

Suggesting that the environment is the problem is suggesting that you only want your software to work in some environments. If that is the case, then that's your call - but it seems like a pity.

See for example https://stackoverflow.com/questions/8319862/can-i-rely-on-referer-http-header

**Comment by SISheogorath** [comment]
I agree that it's not perfect this way. But the point of relying on HTTP Referer is mainly that you shouldn't rely on it for AAA which is not the case.

But no matter, it's still a problem we should solve because there are various reasons why user agents don't send their referrer.

I'm not sure how we can easily solve this, without breaking anything, but we should really fix this.

**Comment by ccoenen** [comment]
IMO this should be a query parameter, this SO answer contains a short example: https://stackoverflow.com/a/27727566/2413043 - but there's probably other things that we need to check, too (presumably session cookie being one of them)
