### ISSUE TITLE
HackMD on Cloud 9

### ISSUE THREAD

**Issue by jd4rider** [hackmdio/hackmd#624]
I can't get HackMD to build on Cloud 9.  It hangs at about 80% then with no error just stops running.

Any directions on moving forward on this would be helpful.

Thanks,

Jonathan

**Comment by SISheogorath** [comment]
Can you check https://github.com/hackmdio/hackmd/issues/485?

**Comment by SISheogorath** [comment]
No further activity. If the issue persist feel free to reopen.
