### ISSUE TITLE
port config problem

### ISSUE THREAD

**Issue by laysdra7265** [hackmdio/hackmd#629]
There is something wrong when the port is not set to 80 .
Browser version:chrome 62.0.3202.94 64 bit
Linux version: Centos 7.4
Node version:6.11.3
When set port to 3000, client's `serverurl` variable get `http://www.example.com:3000:3000`

https://github.com/hackmdio/hackmd/blob/8ea09a8bd0a093a802a3fcb2fdac40935fa92f9e/public/js/lib/config/index.js#L5-L10

Windows.domain variable get `http://www.example.com:3000` then add duplicated `:3000` into string.
I guess this is why I can't login correctly,because it check login status on `http://www.example.com:3000:3000/me` which is invalid path.

Another problem if I don't set port in domain :`"domain": "www.example.com:3000"`
I'll get some request error problem because some resources request on incorrect server path `http://www.example.com` instead of `http://www.example.com:3000`

![image](https://user-images.githubusercontent.com/10185394/33238116-1afcdd92-d2c1-11e7-8148-aa609617c486.png)

**Comment by jackycute** [comment]
Hi @laysdra7265 
Please provide you `config.json` or environment variables.
The `port` should give a number type value and the `domain` should not given with port.

**Comment by laysdra7265** [comment]
But if I don't set port into domain I'll get a lot of 404 error.

![image](https://user-images.githubusercontent.com/10185394/33238177-a01744ee-d2c2-11e7-86cf-b4b445c2977e.png)

config.json:
```json
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        }
    },
    "development": {
        "hsts": {
            "enable": false
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        }
    },
    "production": {
        "domain": "www.example.com:3000",
		"port":3000,
		"alloworigin":["www.etherandir.com"],
        "hsts": {
            "enable": false,
            "maxAgeSeconds": "31536000",
            "includeSubdomains": "true",
            "preload": "true"
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hackmd.sqlite"
        },
		"imageUploadType":"filesystem",
       "allowanonymous":false,
	   "allowfreeurl":false,
	   "defaultpermission":"limited"
    }
}

```

**Comment by jackycute** [comment]
You'll need to set the `urladdport`, like below:
```
"production": {
        "domain": "www.example.com",
	"port": 3000,
        "urladdport": true,
...
}
```

**Comment by laysdra7265** [comment]
Oh,OK.
I finally know how does this option work.
And after I clear the browser cache It work as expected.Thanks
