### ISSUE TITLE
Image Markdown syntax doesn't generate alternative text

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#638]
The following Markdown fragment:

```markdown
![圖片替代文字](https://i.imgur.com/HnB4oQN.png)

![圖片失效時會顯示替代文字not showing](http://invalid.image.url:65536/ff.img)

<img src='http://invalid.image.url:65536/ff.img' alt='圖片失效時會顯示替代文字' />
```

renders:

![_458](https://user-images.githubusercontent.com/13408130/33343715-4c1ac37e-d4c1-11e7-83fa-6a49d0206f97.png)

the alternate text of the second image is missing, while the third one uses HTML preserves.

**Comment by SISheogorath** [comment]
You can actually rename this issue to "Markdown syntax doesn't generate alt text".

Because that's the actual problem.

```
![sometext](https://domain.tld/imag.png)
```

results in:
```
<img src="https://domain.tld/imag.png" alt="" class="">
```

And that's why no text is shown, as there is none set. Needs more investigation

**Comment by Lin-Buo-Ren** [comment]
This problem [isn't reproduced in markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5B%E5%9C%96%E7%89%87%E6%9B%BF%E4%BB%A3%E6%96%87%E5%AD%97%5D%28https%3A%2F%2Fi.imgur.com%2FHnB4oQN.png%29%5Cn%5Cn!%5B%E5%9C%96%E7%89%87%E5%A4%B1%E6%95%88%E6%99%82%E6%9C%83%E9%A1%AF%E7%A4%BA%E6%9B%BF%E4%BB%A3%E6%96%87%E5%AD%97not%20showing%5D%28http%3A%2F%2Finvalid.image.url%3A65536%2Fff.img%29%5Cn%5Cn%3Cimg%20src%3D%27http%3A%2F%2Finvalid.image.url%3A65536%2Fff.img%27%20alt%3D%27%E5%9C%96%E7%89%87%E5%A4%B1%E6%95%88%E6%99%82%E6%9C%83%E9%A1%AF%E7%A4%BA%E6%9B%BF%E4%BB%A3%E6%96%87%E5%AD%97%27%20%2F%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), which seems to be HackMD's markdown engine

**Comment by SISheogorath** [comment]
Thanks to @jackycute
