### ISSUE TITLE
User Cursor Indicator

### ISSUE THREAD

**Issue by KevinAT** [hackmdio/hackmd#641]
Does HackMD not have a name next to the cursor of each user like other editors like Etherpad do? This should really be added since it's impossible to know which cursor belongs to whom without any names or colours and makes working together hard..

**Comment by ccoenen** [comment]
Each cursor has its own color that matches up with the user list ("X ONLINE" button in the upper right corner is a drop down). Furthermore the name is visible as a tooltip if you hover over another user's cursor:

![grafik](https://user-images.githubusercontent.com/124909/33666868-8bf0f54c-da9b-11e7-9f6b-619bfc99b0a5.png)

The delay is a little long, perhaps it could be shortened. But in general I think this is a pretty good already.

**Comment by ccoenen** [comment]
Oh, and also: the left bar with the line numbers will also tell you who wrote which part of a document.

**Comment by KevinAT** [comment]
@ccoenen i swear when i tried it with the guest note on the website a couple days ago it didn't show anything!!!!!

well thanks your help, everything's working fine here now ;)

**Comment by SISheogorath** [comment]
Yes, iirc this highlighting doesn't work for guests by design.

But working as guest was more "hacked into HackMD" than "wanted by design" ^^
