### ISSUE TITLE
pasting image bug?

### ISSUE THREAD

**Issue by laysdra7265** [hackmdio/hackmd#644]
Here is something strange,looks not like all kind of copy & paste image can operating successfully.
When I copy an image from QQ,it just throw `Uncaught TypeError: Cannot read property 'name' of null` to console and nothing happen.
The script can recognize the pasted object as an png file.But when it trying to getAsFile() it just failed and return null.
Here is an screenshot of the debugging on chrome.

![image](https://user-images.githubusercontent.com/10185394/33525591-c5f40eb2-d86d-11e7-9ee8-90c00ee97c42.png)
![image](https://user-images.githubusercontent.com/10185394/33525600-e44d29e8-d86d-11e7-97e0-efd911ceb25b.png)

**Comment by SISheogorath** [comment]
The code itself is definitely not the problem.

Works fine with latest Firefox and Chromium builds.

Can you please provide some information about what Chrome version you are using? Also a like of a picture you tried to use.

This would be very helpful

**Comment by laysdra7265** [comment]
chrome version:62.0.3202.94 
Any picture copied from QQ software.The marked option in picture mean copy.
![image](https://user-images.githubusercontent.com/10185394/33526042-577c1828-d875-11e7-97fc-f6764029eba1.png)

**Comment by laysdra7265** [comment]
Looks like there some kind of limit to paste a image from clipboard.At least not all kinds of clip data.

**Comment by SISheogorath** [comment]
This appears when the picture that is copied doesn't generate some kind of file. In this case `getAsFile()` returns `null`.

I'm currently not sure where we want to handle this but probably I'll simply add some error handling for this later.
