### ISSUE TITLE
功能介紹裡的 Facebook Message 連結失效了/The link to "Facebook Message" isn't working.

### ISSUE THREAD

**Issue by karakarasuuuu** [hackmdio/hackmd#645]
As title,
中文版的跟日文版的用PC點會顯示找不到網頁（跟綁繃帶的讚=w=）
但英文版的是正常的。

**Comment by SISheogorath** [comment]
@karakarasuuuu can you please provide an English version of your request?

**Comment by karakarasuuuu** [comment]
@SISheogorath Sure. (it's a small problem tho)
The link to "Facebook Message" in the [features]( https://hackmd.io/features ) isn't working.
But it only happens in [Chinese version](https://hackmd.io/CwYwhgzAbApgHFAtHAnAIzY4awBNkwCsA7ImFCBCHAIxwBMhhIQA ) and [Japanese version](https://hackmd.io/GwMxE4HYA4EMBMC0BTcwBMiAs94FZFpktZFIQ91pp1xwAjdPIA==).

**Comment by jackycute** [comment]
Fixed, thanks @karakarasuuuu @SISheogorath
