### ISSUE TITLE
Ipython notebook viewer

### ISSUE THREAD

**Issue by apoyet** [hackmdio/hackmd#648]
Hi, 

I'm starting to use HackMD, thank you for this very beautiful tool. I was wondering: do you plan to include somehow a Ipython notebook viewer, like Jupyter? Ideally, something that could allow us to include notebooks inside a document. 

Thank you very much !

**Comment by SISheogorath** [comment]
Well, right now you can put iframes into your notes and this way you can embed any kind of code execution engine as ling as it supports being embedded by iframe.

Example: https://hackmd.io/IYJgbARgxg7AZnAtCAnAUwKyICwxBRFAZgm0QAYwATbCDSdIgDiA?both

**Comment by apoyet** [comment]
Thank you for this answer, I'll try to see what I can do with iframes. 

Thanks for your help!
