### ISSUE TITLE
webpack@1.15.0 does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by towo** [hackmdio/hackmd#655]
Running off of current master, using `bin/setup` straightforward on a Debian stretch:

```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@1.15.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer expose-loader@0.7.4 wants webpack@^2.0.0 || ^3.0.0
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer babel-loader@6.4.1 wants webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc
npm ERR! peerinvalid Peer html-webpack-plugin@2.30.1 wants webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3
```

`debug.log` obviously isn't more helpful here. I'm not sure why it isn't selecting a higher version than 1.15.0, seems to be in the yarn locks. (I'm very much unfamiliar with node.js dependency management.)

**Comment by SISheogorath** [comment]
Do you have anything of these things and/or a dependency globally installed?

In general we recommend to use `yarn`. But this may doesn't solve the problem.

**Comment by towo** [comment]
Layer 8 issue, that was a 4.x nodejs from nodesource.

**Comment by padlock98** [comment]
Hi, may I ask what is a Layer 8 issue means?  I am still having this error.  I can't really upgrade the npm nor nodejs because I need to maintain 4.8.4 nodejs and 2.15.11 npm version to be able to run Docker 1.5.1 .  Anyone has the solution?  Thank you.

**Comment by SISheogorath** [comment]
What is a layer 8 issue? Here you go https://en.wikipedia.org/wiki/Layer_8

And sorry, but as the README clearly says we require node 6 or higher to work.

You can may use the official docker image instead but, just to mention it, running this old version of docker is a really really bad idea as it's vulnerable to hell a lot of vulnerabilities. Also, node 4 is EoL (End of Life) and no longer gets any patches, again, high risky setup. We should not and will not support this.

Please update your setup.
