### ISSUE TITLE
Allow book pages to link to other book pages

### ISSUE THREAD

**Issue by patcon** [hackmdio/hackmd#658]
Currently, a link displayed on a page in book mode (that in this case links to another page in the book) will open a new window/tab when clicked. It would be great if this was either recognized as a special case, or if there was a way to tell hackmd that that link should open within the content pane's context :)

Thanks for hearing me out! Love the tool!

## Example

On this page, would like to be able to link the "related pattern" to another page in the book, without forcing a new tab to open.

https://hackmd.io/c/rynF_9jZz/https%3A%2F%2Fhackmd.io%2Fs%2FS12M4csbz

**Comment by jackycute** [comment]
Fixed, will deploy to site soon.
Thanks @patcon

**Comment by patcon** [comment]
haha wow, that was faster than expected..! I am so appreciative!

**Comment by benabraham** [comment]
It doesn't work as expected:

https://hackmd.io/@benabraham/book-example/

Sources:
Book https://hackmd.io/0HWwfBvSR_eeA4f95qteZA

Page A: https://hackmd.io/bC65cLJtT4iRtmCLxbIPKg
Page B: https://hackmd.io/qoN4Ee9NSY-r9Adv4avV3g
Page C: https://hackmd.io/uq8RHC3gQfWAb4QvqoUakQ

**Comment by jackycute** [comment]
> It doesn't work as expected:
> ...
> Weird is that sometimes for some links it works as expected but I don't see a pattern 🤔

Hi @benabraham,
The example you provided works for me.
Please make sure the link you put in the book mode is exact same as the link you put in the note, just like now.

**Comment by benabraham** [comment]
@jackycute I really appreciate your quick reply! 💗

I tested it more and it works in both the latest Firefox and Edge 18 but not in Chrome 80.0.3987.149.  (everything on Windows 10). By not working I mean sometimes some links work and sometimes not.

I tested it using a clean user profile (everything default, no extensions except Google's default for offline Docs use).

But this isn't probably the right place to report it, right? Can you point me to it if it is so? Thanks!

**Comment by jackycute** [comment]
> But this isn't probably the right place to report it, right? Can you point me to it if it is so? Thanks!

Yes, please report to https://github.com/hackmdio/hackmd-io-issues/issues
We would love to discuss that. It will be helpful if you can find any reproducible case.
