### ISSUE TITLE
HackMD's formatting toolbar should insert HTML tags counterparts when the selection is inside an HTML block

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#670]
## Example Content
```html
<p>
    白色廣場<br>
    White plaza, <br>
    The white pla-za, <br>
</p>
```

## Bug Reproduce Instructions
1. Select "The white pla-za, " in the paragraph (without the line break)
1. Click the "Bold" item in the formatting toolbar

## Expected Behavior
`strong` HTML tag pair should be inserted surrounding the selected "The white pla-za, " string

## Current Behavior
`**` Markdown markup pair are inserted surrounding the selected "The white pla-za, " string, which is interpreted as-is, as it is inside an HTML block

**Comment by jackycute** [comment]
Hi @Lin-Buo-Ren 
Please don't mix html and markdown syntax inside the same line or the parser might not work as expected.

**Comment by Lin-Buo-Ren** [comment]
I thought this is exactly opposite I want to achieve.  :-/

**Comment by Lin-Buo-Ren** [comment]
...as I like the toolbar to insert HTML tags in HTML blocks and Markdown tags out of the HTML block(depending on the selected context's location)

**Comment by jackycute** [comment]
The toolbar is an experimental design for markdown editor, please understand this is not an HTML editor.
Also, it's hard to make the parser completely support mixed markdown and HTML.

Anyway, I tried below code would work, and I don't know why to add the `<br>` after the line, since we use line breaks as default.
```
<p>
    白色廣場<br>
    White plaza, <br>
    
**The white pla-za,**
</p>
```

**Comment by Lin-Buo-Ren** [comment]
Thanks for your explanation, however I believe that HTML code is allowed in Markdown spec. with a exception of not mixing them together.

I put the original file of the example content here, just for reference
https://hackmd.io/BwBgLAnAxghiCMBaCAjKA2RYCmAmEyA7ACYzJgICsK6ux2AZiEA

**Comment by jackycute** [comment]
Thanks for giving us suggestions!
And yes, it's true that markdown allows HTML tag inside.
Please read more here: http://spec.commonmark.org/0.28/#raw-html
