### ISSUE TITLE
Service worker support for offline usage

### ISSUE THREAD

**Issue by TennyZhuang** [hackmdio/hackmd#676]
[Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)

[A simple example](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/registerServiceWorker.js) to use service worker for offline usage.

**Comment by ccoenen** [comment]
related to #398, the tricky part here will be what to do with conflicts if multiple people edit their respective offline files. (or the documents could at least be read only, that would be an improvement as well)

**Comment by SISheogorath** [comment]
In the current setup this will only break things. It needs a lot of re-factoring to make this possible in any way without breaking. So right now it more a duplicate.
