### ISSUE TITLE
Dropbox Import uses clientSecret instead of appKey

### ISSUE THREAD

**Issue by tiirex9** [hackmdio/hackmd#683]
I think this is a general hackmd problem.
When you click on "Dropbox import" it seems to use the "clientSecret" value as app_key instead of the "appKey" value. Therefore the opened window just contains the error message "Invalid app_key".

I had this problem with the docker version, but I think it's a general hackmd thing, since this value comes directly from the config.json file.

**Comment by SISheogorath** [comment]
This is not only a general HackMD problem it's also a security issue.

Please update to 1.0.1-ce and change your Dropbox client secret as soon as possible.
