### ISSUE TITLE
Share note to guests even if allowanonymous=false

### ISSUE THREAD

**Issue by Nebukadneza** [hackmdio/hackmd#689]
Hi,

HackMD is a great tool, and I’m hosting it for myself and a few friends. I have allowanonymous=false and allowemailregister=false so that we can manually control the userbase. Setting allowanonymous=true makes guests able to *create* notes, which i want to forbid. However, having allowanonymous=false will remove the `freely` permission from the permission menu.

I think it is a legitimate usecase that only signed-in users can create a note, but guests cannot. When a signed-in user wants to share a note for a guest to edit, that should still be possible.

Thanks for your great tool nevertheless :+1: 
-Dario

**Comment by Nebukadneza** [comment]
Looking at 5c7eb483198d0d92dc88c7a7c25cca5c23eb5cf2 I suppose i could add a patch for this. Just checking if my idea is aligned with everyones views of the project:
- allowanonymous keeps its current semantics:
- - disables the „new guest note“ function on the startpage
- - removes the `freely` option
- add option: allowanonymousedits
- - only checked if ! allowanonymous
- - keeps allowanonymous from removing the `freely` option

Does this sound somewhat reasonable?

Best & Thanks
-Dario

**Comment by SISheogorath** [comment]
Agreed. 👍 Sounds like a plan!
