### ISSUE TITLE
how to use a custom S3 endpoint?

### ISSUE THREAD

**Issue by Wander1024** [hackmdio/hackmd#696]
how to use a custom S3 endpoint?
Can I do it?

**Comment by SISheogorath** [comment]
Right now we provide no support for a custom s3 endpoint.

But shouldn't be hard to add this feature.

Some hints:

https://github.com/hackmdio/hackmd/blob/7de6e3211f797ed9e9e5ca3d52181f77abf030d0/lib/web/imageRouter.js#L41-L75

https://github.com/hackmdio/hackmd/tree/master/lib/config

Pull Requests are welcome 👍

**Comment by Wander1024** [comment]
I sloved it.
```
# vim lib/config.js

var certs = [fs.readFileSync('./ca_chatin.pem')];
//var s3enpoint =
var s3 = {
  accessKeyId: handleDockerSecret('s3_acccessKeyId') || process.env.HMD_S3_ACCESS_KEY_ID || config.s3.accessKeyId,
  secretAccessKey: handleDockerSecret('s3_secretAccessKey') || process.env.HMD_S3_SECRET_ACCESS_KEY || config.s3.secretAccessKey,
  region: process.env.HMD_S3_REGION || config.s3.region,
  endpoint: 'https://example.com',
  signatureVersion: 'v4',
  s3ForcePathStyle: true,
  httpOptions: {agent: new https.Agent({
    rejectUnauthorized: true,
    ca: certs
  })}
}
```

**Comment by SISheogorath** [comment]
Would you like to provide a Pull Request?

**Comment by Wander1024** [comment]
why use deepFreeze in `lib/config/index.js`?
This functions can't process some objects.

**Comment by SISheogorath** [comment]
Actually to prevent exactly what you did. Active code in configs.

Configs should be created once and never change until you restart the application (some applications provide a reload function, we don't). This prevents unexpected behaviour and makes the entire application more reliable.

**Comment by SISheogorath** [comment]
There seem to be no work on this anymore…

Close due inactivity
