### ISSUE TITLE
What is responsible for generating the ToC?

### ISSUE THREAD

**Issue by mikeymop** [hackmdio/hackmd#701]
I really like the Table of Contents style you use when exporting to html.
I would like to use this on a desktop markdown editor when working offline.

If this is at all possible can you help direct me to what utilities in this repo generate the ToC html?

**Comment by SISheogorath** [comment]
Sure 😄 

Here you go: https://github.com/yijian166/md-toc.js

**Comment by ccoenen** [comment]
I'll close this, it looks like the question is answered. If this is not the answer you were hoping for, please feel free to reopen the ticket :-)

**Comment by mikeymop** [comment]
No this is perfect. Than you both!

**Comment by RoyiAvital** [comment]
Any chance to customize it?

One feature which should be quite useful is choosing the header level to be included.
For instance `[TOC](2, 3, 4, 5)` means only headers of level `2, 3, 4, 5` will be included in the TOC.
