### ISSUE TITLE
Simple Cmdline User-Creation Tool

### ISSUE THREAD

**Issue by Nebukadneza** [hackmdio/hackmd#702]
Hi,

since #272 (User Administration) is a big of a bigger hunk and will need some time, I propose an intermediate step, which will already help users hosting closed instances: A simple commandline user creation/deletion script.

Currently users hosting a closed instance need to manually hash passwords using scrypt on the node commandline, and enter user-data into their respective database. AFAIK no database-commandline or frontend has scrypt-kdf functionality builtin, so this is quite labour-intensive.

A _simple_ Commandline tool that does something like:
```
node user_admin.js
    Usage: node user_admin.js <-a||-d> [-p <password>] <user email>
        -a Add User
        -d Delete User
        -p Use password from commandline (rather than prompting)
```
Would lighten the work of administrators of such a instance tremendously. At the same time, it should be quite simple and quick to implement, so that it can be available quickly.

I could try to understand your database backend and how to `argparse` in node, and implement/PR a functionality like that. Please let me know what you think about the idea.

Best,
-Dario

**Comment by SISheogorath** [comment]
Actually you should be fine with making a require on the User model.

To create such a tool you basically refactor this code by replacing all web request content with CLI and add a function to replace the password:
https://github.com/hackmdio/hackmd/blob/master/lib/web/auth/email/index.js

Feel free to file a PR :)
