### ISSUE TITLE
Disable auto-numbering within code blocks

### ISSUE THREAD

**Issue by perilstar** [hackmdio/hackmd#706]
**Description**
The editor interprets numbers at the start of lines in code blocks as lists.

**How to reproduce:**

0. Create a code block. Inside, have a line starting with a number that has a decimal place. For example:

    ```python=
    well_formatted_long_list = [
        36.4, 50.2, 64.8, 29.4,
        22.9, 90.7, 47.6, 99.4,
        41.5, 11.6, 33.9, 10.8
    ]
    ```

0. Place your cursor at the end of the last line and press return. The next line will be auto-filled with what the editor thinks is an incremented list index:

    ```python=
    well_formatted_long_list = [
        36.4, 50.2, 64.8, 29.4,
        22.9, 90.7, 47.6, 99.4,
        41.5, 11.6, 33.9, 10.8,
        42.
    ]
    ```

It doesn't matter if you add a comma like I did here.

**Comment by SISheogorath** [comment]
I see the problem but at the same time, I'm not sure how much bug it is.

I would personally leave it as it is because people may want to use the auto numeration feature in the code section. But I would like to see a discussion about it :)

**Comment by SISheogorath** [comment]
Seems like there is not enough interest in changing this behaviour.

We'll keep it the way it is.
