### ISSUE TITLE
Multi-level Checkbox List Items Misaligned Issue

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#709]
Refer the following screenshot:  
![](https://i.imgur.com/qyHKzGQ.png)

The items no longer aligned with the source layout for some reason; the syntax highlighting in the source pane is completely fine.

## Bug Reproduction Source
```markdown
* [ ] 1
* [ ] 2
* [ ] 3
	* [ ] 3-1
		* [ ] 3-1-1
	* [ ] 3-2
	* [ ] 3-3
```

Rendered as:  
![default](https://user-images.githubusercontent.com/13408130/35486437-f958a878-04a8-11e8-8840-e53c468d295f.png)

**Comment by ccoenen** [comment]
which version are you running right now? I can't reproduce this on my own setup (granted, it is still running 0.5.x)

**Comment by SISheogorath** [comment]
We have an instance on Heroku that runs the latest master. Please try to reproduce there:

https://hackmd-ce.herokuapp.com/JwDgTMYAwMwIwFoBmcBGwEBZ0GMGswFMA2BGYmAE2OAEMkSpag==#

**Comment by ccoenen** [comment]
(screenshots from @SISheogorath's link)

Firefox, Windows:
![grafik](https://user-images.githubusercontent.com/124909/35487523-b2c0f126-047c-11e8-989a-7aaf672b6efe.png)

Chrome, Windows:
![grafik](https://user-images.githubusercontent.com/124909/35487534-d4e34e5c-047c-11e8-967a-d0ec6e3ad6f0.png)

**Comment by Lin-Buo-Ren** [comment]
> which version are you running right now?

Apologies for not providing the required information.  I've reproduced this issue on the hackmd.io instance, but not on the local docker-hackmd instance.

As the master revision seems all right now the issue should be closed.

**Comment by Lin-Buo-Ren** [comment]
Also here's the original reproduced document: https://hackmd.io/KwdgRgxgHAhgTARgLQE4BsAzMSAsYCmGSMCAJisQvgMzX5iJxoRA

**Comment by SISheogorath** [comment]
@jackycute may have a look at this. Not sure why this should happen.

**Comment by jackycute** [comment]
@SISheogorath I just try on my Windows Chrome 63 and Firefox 57, still good.

**Comment by Lin-Buo-Ren** [comment]
* I noticed that the same source document can't reproduce the same issue on Google Chrome.
* I started Firefox in safe mode, still reproducing it.

**Comment by Lin-Buo-Ren** [comment]
* I cleared "Cache" and "Offline site data" in firefox, still reproducing the issue
* *I cleared "Individual site settings" in Firefox and the issue is no longer reproduced.*

Still quite confusing to me though :-/

**Comment by jackycute** [comment]
@Lin-Buo-Ren 
That maybe means you or any extension/plugin set something for the list item styles.
Or just Firefox's bug...
I couldn't tell, but seems not our code's issue.

**Comment by Lin-Buo-Ren** [comment]
Reference: https://wiki.mozilla.org/Site-Specific_Preferences
