### ISSUE TITLE
engine.io-client dependency broken, socket.io connections not working

### ISSUE THREAD

**Issue by stbuehler** [hackmdio/hackmd#715]
In a fresh install:

Right now the `socket.io-client@^2.0.4` dependency depends on `engine.io-client@~3.1.0`, ending up as `3.1.4`, and the `socket.io@~2.0.4` pulls in `engine.io@~3.1.0` (again ending up as `3.1.4`).

But `hackmd` depends on `engine.io-client@^1.8.2`, ending up as `1.8.5` - which does not work with `engine.io@3.1.4`.

I think the `engine.io-client@^1.8.2` dependency should be removed, and `modulesDirectories` should be set to only contain `node_modules`, not absolute paths (see https://github.com/webpack/webpack/issues/472#issuecomment-55609294); that way webpack should still find `engine.io-client`.

It seems webpack needs more memory and more time that way, but maybe you can figure out why (perhaps its including some modules more than once, and the dependencies should get fixed further to have only one version of those).

As a start increasing the `engine.io-client` dependency to `engine.io-client@^3.1.0` should workaround the problem, but that is NOT a longterm solution!

**Comment by SISheogorath** [comment]
Confirmed. I'll (try to) work on a solution this weekend.

**Comment by stbuehler** [comment]
It seems `path.resolve(__dirname, 'node_modules')` is also needed; without that it complains about undefined `eve` (more might be missing, I think it stopped there).

But it works without `path.resolve(__dirname, 'src')` (I don't think that directory exists anyway).
