### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by mcnesium** [hackmdio/hackmd#717]
When opening a note on a selfhosted instance, the following  messages appear in browser consoles:
Firefox:
> Firefox can’t establish a connection to the server at wss://hackmd.domain.org/socket.io/?EIO=3&transport=websocket&sid=JF-lcAQqhAPq_pCjAABY.

Chromium:
> WebSocket connection to 'wss://hackmd.domain.org/socket.io/?EIO=3&transport=websocket&sid=atehdwf3tDT5nzb4AABh' failed: Error during WebSocket handshake: Unexpected response code: 400

Epiphany adds this to the same message Chromium brings up:
> Failed to load resource: Too many redirects https://hackmd.domain.org/build/

This happens on an instance that has been built from cloning from GitHub and adding the following envvars to `docker-compose.yml`

    - HMD_DOMAIN=hackmd.domain.org
    - HMD_URL_ADDPORT=false
    - HMD_PROTOCOL_USESSL=true

as well as uncommenting ports `"127.0.0.1:3000:3000"` instead of `"3000:3000"`. To access this docker container I added the following apache config to the virtualhost:

    ProxyPreserveHost On
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPass           /  http://localhost:3000/
    ProxyPassReverse    /  http://localhost:3000/

I read and tried the `RewriteEngine` suggestions from #198 but those did not make the errors go away.

To clarify: there is not actually a malfunction I experience, I am just curious why this message is there (and in two other instances I use occasionally) but **not on hackmd.io**

**Comment by SISheogorath** [comment]
It sounds like you don't have the websocket module loaded.

On Debian:
`a2enmod proxy_wstunnel`

Otherwise:
https://httpd.apache.org/docs/2.4/en/mod/mod_proxy_wstunnel.html

Make sure you enable it and restart apache2 afterwards

**Comment by SISheogorath** [comment]
Feel free to write some docs for an apache2/httpd-based setup.

Here is a config I used for a long time before switching to [traefik](https://traefik.io) with some annotations and preparation for documentation reasons.

It would be lovely when you could write a bit more down :)

```apache
# Load https://httpd.apache.org/docs/2.4/en/mod/mod_proxy_wstunnel.html

<VirtualHost *:80>
        # -------------------------------------------#
        #                 CHANGE ME                  #
        # -------------------------------------------#
        ServerName pad.example.com
        ServerAdmin webmaster@example.com

        # Rewrite all requests to HTTPS
        RewriteEngine On
        RewriteCond %{HTTPS} !=on
        RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<IfModule mod_ssl.c>
SSLStaplingCache shmcb:/tmp/stapling_cache(128000)
<VirtualHost *:443>
        # -------------------------------------------#
        #                 CHANGE ME                  #
        # -------------------------------------------#
        ServerName pad.example.com
        ServerAdmin webmaster@example.com

        # -------------------------------------------#
        #                 CHANGE ME                  #
        # -------------------------------------------#
        # Provide DocumentRoot… Just in case
        # If you notice high load on your node process while using
        # the `filesystem` upload method it can help to let apache serve it
        DocumentRoot /path/to/DocumentRoot

        # Provide Hostname to HackMD
        ProxyPreserveHost On

        # This is not a forward proxy
        ProxyRequests off
        # For debugging reasons the way our request took is useful
        ProxyVia On

        # Don't pass .wellknown in case you want to use Let's Encrypt
        ProxyPass /.wellknown !
        # Having an own 503 page can be nice :)
        ProxyPass /503.html !

        # Rewrite secure Websocket connections to insecure ones so HackMD
        # without TLS can consume them
        RewriteEngine On
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*) ws://127.0.0.1:3000/$1 [P,L]

        # Proxy everything else that is HTTP to HackMD
        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000

        # TLS config. We only provide service using HTTPS :)
        SSLEngine On
        SSLHonorCipherOrder On

        # -------------------------------------------#
        #                 CHANGE ME                  #
        # -------------------------------------------#
        SSLCertificateFile    /path/to/fullchain.pem
        SSLCertificateKeyFile /path/to/privkey.pem

        SSLUseStapling on

        # Point out our custom error page for 503 errors
        ErrorDocument   503     /503.html
</VirtualHost>
</IfModule>

```

**Comment by mcnesium** [comment]
You were right, enabling `proxy_wstunnel` as well as adding the rewrite config to the virtual host nailed it. Thanks for the hint!
