### ISSUE TITLE
Support pasting markdown

### ISSUE THREAD

**Issue by Himura2la** [hackmdio/hackmd#722]
I used to work with HackMD as with a simple plaintext editor, I often copy-paste the markdown text to and from the hackmd window. 

The recent updates brought new behavior and now I can't paste the markdown code: all my brackets and parentheses are escaped now T_T
I guess it's related to the "smart paste of HTML" feature

I found a way to import a file by drag&dropping it into the hackmd window, but when I need to add some text from another source, I have no way.

Or maybe I have?

**Comment by SISheogorath** [comment]
First of all does it happen on [HackMD.io](https://hackmd.io) or [HackMD CE](https://hackmd-ce.herokuapp.com/)?

If it's on HackMD CE, Can you give some more details about which version you used, where it worked?

Also can you provide some steps to reproduce it?

**Comment by jackycute** [comment]
It’s new behavior in HackMD.io, not HackMD CE, I’ll change the issue link from the site soon, sorry for misdirected you here.

So you can paste the content as plaintext, and it won’t be escaped, normally there is a context menu when you right click the editor and choose one named “Paste as plaintext” then that should be good.

**Comment by Himura2la** [comment]
Actually there's no issue link on the site, I had to google this repo.

Thanks for the suggestion, but I definitely tried pasting a plain-text from AkelPad and I also think I tried Ctrl+Shift+V.

But I'll dig into these fields deeper once I had time.

**Comment by Lin-Buo-Ren** [comment]
Please allow the smart formatting conversion feature to be opted-in as it's really just making a mess in most situations.

The "paste as plaintext" feature isn't available in Mozilla Firefox for Ubuntu.

**Comment by jackycute** [comment]
For better management and avoid confusing, please report any further issue in https://github.com/hackmdio/hackmd-io-issues

Thanks!
