### ISSUE TITLE
Allow in title <br> linebreak in book mode

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#723]
In Markdown it is possible to use `<br>` raw HTML element in the heading syntax to make a line break, 

```markdown
## Like<br>this
```

### Like<br>this

However this formatting isn't preserved in the generated title in book mode:

![default](https://user-images.githubusercontent.com/13408130/36065869-acd68ee2-0edb-11e8-8b22-fd6ded5d1dd7.png)

**Comment by jackycute** [comment]
For better management and avoid confusing, please report any further issue in https://github.com/hackmdio/hackmd-io-issues

Thanks!
