### ISSUE TITLE
Postgresql SSL support

### ISSUE THREAD

**Issue by ThoreKr** [hackmdio/hackmd#731]
Good evening,
while trying to set up hackmd with a postgres database I can not find the correct options to establish a ssl connection to the database.

After some searches I found this in a sequelize issue, but had no success.
```
"db": {
            "username": "hackmd",
            "password": "secret",
            "database": "hackmd",
            "host": "somewhere.else",
            "port": "5432",
            "dialect": "postgres",
            "dialectOptions": {
                "ssl": true
            },
	    "options": ""
        },
```
Also setting `sslmode=require` in the options was not successful.

How do I enable ssl for a postgres connection?

**Comment by SISheogorath** [comment]
First of all, what error message did you get?

What kind of setup are you running? Native one? Docker? Heroku?

**Comment by ThoreKr** [comment]
Oh, I'm sorry. It's a native setup . It complains about a lacking pg_hba.conf entry with ssl off:
```
Unhandled rejection SequelizeConnectionError: no pg_hba.conf entry for host "10.1.2.3", user "hackmd", database "hackmd", SSL off
    at /usr/local/hackmd/hackmd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:20
    at Client.<anonymous> (/usr/local/hackmd/hackmd/node_modules/pg/lib/client.js:203:5)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/usr/local/hackmd/hackmd/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

**Comment by SISheogorath** [comment]
To be honest, I have no idea if sequelize 3 supports this. You can may try it with the URL way of providing it but I have really no idea and right now not the resources to reproduce it.

**Comment by SISheogorath** [comment]
Feel free to reopen when you could find any notice about support for sequelize 3
