### ISSUE TITLE
Feature request: <details> support

### ISSUE THREAD

**Issue by matthias-vogt** [hackmdio/hackmd#736]
I often need code like this
```
<details>
	<summary>Spoiler</summary>
	something happens
</details>
```
<details>
	<summary>Spoiler</summary>
	something happens
</details>
<br>
It would be cool if this was supported natively with some kind of markup.

**Comment by ccoenen** [comment]
Duplicate of #445 - but this would be a very nice first contribution! All it takes is a bit of CSS, some testing :-) (demo css also in #445)
