### ISSUE TITLE
Switch main buttons

### ISSUE THREAD

**Issue by mcnesium** [hackmdio/hackmd#737]
I would like to discuss the order of the [main buttons in the header](https://github.com/hackmdio/hackmd/blob/72011446613e9d22097879d3ec825416e46ca910/public/views/hackmd/header.ejs#L89). 

It seems odd to me that the edit-button is on the left and the view-button on the right, while in split view the order of the areas is vice versa. This should be switched to this order imho: ✏️  📖 👁 

From my point of view all that needs to be done is to just switch those two `<label>` elements. If you agree, I will file a pull request.

**Comment by ccoenen** [comment]
Thanks for your suggestion, there's already a pull request implementing that: #665
