### ISSUE TITLE
Missing shortcut to leave multiple selection mode

### ISSUE THREAD

**Issue by naeon** [hackmdio/hackmd#738]
While having some great features like the multiline / multiple selection mode of Sublime in HackMD as well is a big plus, one thing seems to be missing:

When one uses `Cmd-D` (to select multiple instances) or `Alt-Click-Drag` (for block edit mode), there seems to be no way to leave that mode and return to a single cursor – except for clicking somewhere else. From a usability perspective, this could be improved.

Sublime uses `Esc` to leave all kinds of other modes (Search, Selection, etc.) and if there's no other shortcut already implemented in HackMD, I would suggest using `Esc` as well.

**Comment by SISheogorath** [comment]
I wrote a basic fix for it. It probably needs some more work later.
