### ISSUE TITLE
hackmd.io looks like had some problems

### ISSUE THREAD

**Issue by Rwing** [hackmdio/hackmd#746]
When I open anyone note, eg https://hackmd.io/EzAMGMEMEZgdgLTgEYFNgICxwgyoBOTBAM1QGYDQBWVaAEwA5MSg
I will get an error in Chrome console :
GET https://hackmd.io/socket.io/?EIO=3&transport=polling&t=M7SscPZ 503 ()
```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by jackycute** [comment]
We're dealing with server issues, and it's a `HackMD.io` issue, not here.

**Comment by SISheogorath** [comment]
For HackMD.io issues please see: https://github.com/hackmdio/hackmd-io-issues/issues

**Comment by Rwing** [comment]
ok got it and sorry for my mistake

**Comment by Lin-Buo-Ren** [comment]
Refer <https://www.facebook.com/hackmdio/posts/1711800608877141> for more info.
