### ISSUE TITLE
Export documents while the server is offline

### ISSUE THREAD

**Issue by hunan-rostomyan** [hackmdio/hackmd#747]
I'm connected to the internet, but every document I open shows up blank and stays in offline mode.

<img width="1430" alt="screen shot 2018-02-28 at 8 46 46 am" src="https://user-images.githubusercontent.com/5122980/36800429-61c899ae-1c64-11e8-85f4-e21cbf8c9fae.png">

When I download a document, I get an empty markdown file, even though the file is supposed to be non-empty. There seems to be some issue with the server at the moment, so it's 503-ing.

**Question**. Is there any way to export all of the documents (preferably in markdown format) at once, without having to first render the documents (because rendering doesn't seem to always work).

**Comment by mlopezgva** [comment]
Same here, with and without proxy, on three browsers.
Network log:

Agreed... At least the "download as Markdown" would be a nice option for when part of the server is down (if it can access the file, of course...)

![image](https://user-images.githubusercontent.com/996070/36801371-b18470ea-1c90-11e8-9c19-cee20f3e7134.png)

**Comment by SISheogorath** [comment]
I guess you are talking about hackmd.io?

Yes, there was a problem today/yesterday which currently prevents HackMD.io from working correctly.

For details please refer to the official statements:
https://twitter.com/hackmdio/status/968837961151258624
https://twitter.com/hackmdio/status/968838053606248453

To export your notes, please refer to:
https://twitter.com/hackmdio/status/968849191077167109

Thanks for your patience.

Additional hint, for Hackmd.io issues there is an own repository now at: 
https://github.com/hackmdio/hackmd-io-issues/issues

**Comment by hunan-rostomyan** [comment]
@SISheogorath Sorry, rushed and made an issue here instead of finding the right repo. Thank you very much for the details.
