### ISSUE TITLE
Remove unused option from ldap configuration in config.json.example

### ISSUE THREAD

**Issue by thegcat** [hackmdio/hackmd#754]
From what I can tell (I am not a node nor a js dev) the `tokenSecret` key in the ldap configuration is not used anymore, is this correct? I would suggest removing it from the example configuration file and from the environment variables. 

https://github.com/hackmdio/hackmd/blob/master/config.json.example#L77

**Comment by SISheogorath** [comment]
I checked and yes, it's not passed anywhere. But I'm not sure it's by accident or intended.

Maybe the devs of the feature can tell a bit more? @alecdwm @neopostmodern

**Comment by thegcat** [comment]
It was used when it was introduced https://github.com/hackmdio/hackmd/commit/02e99277146d8bd912f2f19af1d3e94a6181d90d#diff-45ced1ab657dd3dcf5d098a56bc0f039R138

I don't see anything looking remotely like that in the current code anymore :-)

**Comment by SISheogorath** [comment]
Yes, this was changed a while back, so it should no longer be needed.

The re-factoring of the auth system solved a lot of these problems ^^

**Comment by SISheogorath** [comment]
Feel free to provide a PR :+1:

**Comment by thegcat** [comment]
Done in #755, thanks!
