### ISSUE TITLE
<M-f> opens search

### ISSUE THREAD

**Issue by felberj** [hackmdio/hackmd#759]
In emacs mode, `<M-f>` (alt + f) opens search.
I think that (at least in emacs mode) the cursor should jump one word forward.

Tested on osx with safari and chrome.

**Comment by SISheogorath** [comment]
Can't reproduce over here. Works fine on Fedora in Chromium as well as Firefox.

Where did you try it? Please check https://hackmd-ce.herokuapp.com/EYEwpg7AzADFCMBaAZseVEBYCsUCGiwAbMAEyIjLaYgCcREmeMmQA===#

**Comment by felberj** [comment]
Thank you very much, it works on your page, but not on https://hackmd.io/GmwTX9VPR2CwMV1_IgRw0w?edit

**Comment by SISheogorath** [comment]
In this case please reopen the bug on https://github.com/hackmdio/hackmd-io-issues/issues as we splitted the issue trackers. Thanks :smile:
