### ISSUE TITLE
HMD_MINIO_PORT must be converted to  Number Type

### ISSUE THREAD

**Issue by vazontang** [hackmdio/hackmd#763]
I  found a bug when I was using Minio.
If a variable which is passed from environment will be String type .
But the  **port** in Constructor of Minio client **only accepts Number type**  .

![image](https://user-images.githubusercontent.com/31801725/37400163-fa9be04a-27be-11e8-9eda-9c591e43cb67.png)

---

###  If Port is String type  , there will be an error and cause image uploading failed.
![hmd_bug](https://user-images.githubusercontent.com/31801725/37400206-2752eb06-27bf-11e8-9fb1-64ce620f5b39.PNG)

---

* As a result, please convert **port of Minio** into number type in  ```/lib/config/environment.js``` .

```javascript
 minio: {
    accessKey: process.env.HMD_MINIO_ACCESS_KEY,
    secretKey: process.env.HMD_MINIO_SECRET_KEY,
    endPoint: process.env.HMD_MINIO_ENDPOINT,
    secure: toBooleanConfig(process.env.HMD_MINIO_SECURE),
    port: parseInt(process.env.HMD_MINIO_PORT)
  },
```

**Comment by SISheogorath** [comment]
Nice you found this bug, would you like to file a PR for this?
