### ISSUE TITLE
Timeout after 30s waiting on dependencies to become available

### ISSUE THREAD

**Issue by mcnesium** [hackmdio/hackmd#774]
This is the logfile of a HackMD instance run within a Docker environment (see below). I wonder what happens here. Why is the connection to the database said to be refused, then terminated? After all the database *is being connected* and at least it looks and feels like everythink works as it should.

    $ docker logs hackmd_app_1
    2018/03/22 16:49:54 Waiting for host: database:5432
    2018/03/22 16:49:54 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:49:59 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:50:04 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:50:09 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:50:14 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:50:19 Problem with dial: dial tcp 141.76.119.143:5432: getsockopt: connection refused. Sleeping 5s
    2018/03/22 16:50:24 Timeout after 30s waiting on dependencies to become available: [tcp://database:5432]

    Sequelize [Node: 6.12.3, CLI: 2.8.0, ORM: 3.30.4]

    Parsed url postgres://hackmd:*****@database:5432/hackmd
    (node:25) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
    No migrations were executed, database schema was already up to date.
    (node:38) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
    >> WARNING: PostgreSQL does not support TEXT with options. Plain `TEXT` will be used instead.
    >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
    2018-03-22T16:50:31.815Z - info: HTTP Server listening at port 3000

`docker-compose.yml` is nearly stock, besides removed networks:

    version: '3'
    services:
      database:
        image: postgres:9.6-alpine
        environment:
          - POSTGRES_USER=hackmd
          - POSTGRES_PASSWORD=hackmdpass
          - POSTGRES_DB=hackmd
        volumes:
          - /srv/hackmd/database:/var/lib/postgresql/data
        restart: always
      app:
        image: hackmdio/hackmd:1.0.1-ce
        environment:
          - HMD_DB_URL=postgres://hackmd:*****@database:5432/hackmd
          - HMD_USECDN=false
          - HMD_DOMAIN=hackmd.domain.de
          - HMD_URL_ADDPORT=false
          - HMD_PROTOCOL_USESSL=true
          - HMD_ALLOW_FREEURL=true
          - HMD_IMAGE_UPLOAD_TYPE=filesystem
        volumes:
          - /srv/hackmd/uploads:/hackmd/public/uploads
        ports:
          - "127.0.0.1:5087:3000"
        restart: always

**Comment by SISheogorath** [comment]
Please don't mix up issue trackers. This is a docker image specific thing (and question). Feel free to talk with me about it in person using [Matrix/Riot](https://riot.im/app/#/room/#hackmd:matrix.org) or [Gitter](https://gitter.im/hackmdio/hackmd).

Otherwise I recommend to open the issue on the [right repository](https://github.com/hackmdio/docker-hackmd/issues) or simply read the [entrypoint script](https://github.com/hackmdio/docker-hackmd/blob/master/docker-entrypoint.sh).

Hope this can clear things up :)
