### ISSUE TITLE
Support WebDAV and Nextcloud as Import/Export?

### ISSUE THREAD

**Issue by poVoq** [hackmdio/hackmd#777]
Would be cool if HackMD would also support WebDAV as an import/export option. There are many services using it, maybe most importantly Nextcloud.

It seems like there is an easy to use NodeJS lib for it that should do the trick, see some explanation here:
https://nextcloud.com/blog/using-webdav-fs-to-access-files-in-nextcloud/

Thanks!

**Comment by SISheogorath** [comment]
Dublicate of #245

**Comment by SISheogorath** [comment]
To not get a wrong image of the community, we like suggestions etc. it would just be nice, when we can keep issues together and not splitted into various discussions.

Apart from that, as always, Pull Requests are welcome :heart:
