### ISSUE TITLE
Feature request: Popup Outline Title 

### ISSUE THREAD

**Issue by leo424y** [hackmdio/hackmd#781]
<img width="111" alt="screen shot 2018-03-26 at 9 01 43 am" src="https://user-images.githubusercontent.com/1384394/37882273-7806b410-30d4-11e8-8307-cb091aaf5848.png">

The right-side-outline help hackmders quick jump to the topic, I really love it!
But the long title will be cut(...). Sometimes we can't get what it means

Is it possible to pop up the full title? (maybe use "title" props)

Thanks for your effort!

**Comment by SISheogorath** [comment]
Should make it to the next (not the upcoming) release. Fix is ready for review
