### ISSUE TITLE
allowAnonymousEdits doesn't work

### ISSUE THREAD

**Issue by azyobuzin** [hackmdio/hackmd#798]
If I set `false` to `allowAnonymous` and set `true` to `allowAnonymousEdits`, the "freely" permission is not shown in the note page.

I think the cause is several typos in the source code. `allowAnonymousedits` should be `allowAnonymousEdits`.

- https://github.com/hackmdio/hackmd/blob/bdb8631a7b99771990890db20b171618ef06c6e9/lib/config/index.js#L56
- https://github.com/hackmdio/hackmd/blob/bdb8631a7b99771990890db20b171618ef06c6e9/lib/realtime.js#L791
- https://github.com/hackmdio/hackmd/blob/bdb8631a7b99771990890db20b171618ef06c6e9/lib/response.js#L62
- https://github.com/hackmdio/hackmd/blob/bdb8631a7b99771990890db20b171618ef06c6e9/lib/response.js#L97

**Comment by SISheogorath** [comment]
Oh thanks for catching that. I guess it appeared during the config migration from lower-case-only to camel case.

There will be a first bugfix release soon that will cover it.
