### ISSUE TITLE
slides: reveal.js doesnt work in non-cdn mode

### ISSUE THREAD

**Issue by MartB** [hackmdio/hackmd#800]
Hey, 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/lib/js/head.min.js></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/js/reveal.min.js</script>
```

These Scripts are not getting packed by webpack and are missing from the slides-pack file for some reason.
I cant use slides when im on non-cdn mode.

**Comment by SISheogorath** [comment]
Do you have an example about what is not working? Because before the release I used the slide example to check if it works and it seems to be fine there.

**Comment by MartB** [comment]
nvm cloudflare fucked with me!
