### ISSUE TITLE
No use of Google API Key

### ISSUE THREAD

**Issue by tiirex9** [hackmdio/hackmd#801]
In app.js in line 36 the GOOGLE_API_KEY constant gets set to config.google.clientSecret.
Shouldn't this be `config.google.apiKey`?!

Therefore another change in environment.js line 78 is necessary:
`apiKey: process.env.HMD_GOOGLE_API_KEY`

Can anyone confirm this?!

As far as I understand it the HMD_GOOGLE_API_KEY environment variable is not used at all, but should be for import/export stuff... Analogue to Dropbox stuff...

**Comment by SISheogorath** [comment]
This leads to an even bigger issue that the Google Filepicker integration in general is broken (as far as my tests go while trying to solve this problem).

And yes, we shouldn't expose this secret.

**Comment by SISheogorath** [comment]
@ccoenen As I noticed during my tests it needs an entire rewrite of the file picker…

I'm not sure if we want to do this in a minor release. Also it imports the Google API from external places which breaks with CSP in multiple ways and from Google's side I couldn't find a good way to avoid this (well, there is a googleapi package on npmjs but I would like to have to important that, and it also may doesn't completely solve the problem)

I consider to remove the feature if there is no one who states here that he needs it and/or want to maintain it.

**Comment by ccoenen** [comment]
I'm not using this feature myself. I would be OK with removal. Interestingly, there haven't been many comments that this is broken, even though it should be broken for everyone (right?). This would support removal, in my opinion.

**Comment by SISheogorath** [comment]
The secret was removed and the feature itself was hid for this release because it's completely broken.

Needs a rewrite for 1.2.0 :/

Can't help it.
