### ISSUE TITLE
hackmd support invite someone to edit together by email?

### ISSUE THREAD

**Issue by cmmei** [hackmdio/hackmd#809]
Does hackmd support to invite someone to edit together by email ?

**Comment by SISheogorath** [comment]
No, you can't invite people directly per email inside HackMD.

But of course you can simply write an email containing the link to the note. If you set the permission to `freely` they can edit the note without register or login.

For other permission settings see: https://hackmd-ce.herokuapp.com/features#Permissions

**Comment by ccoenen** [comment]
It wouldn't be too hard to add an invite link containing

```
    <a href="mailto:?subject=Your%20invitation%20to%20AWESOME%20DOCUMENT&body=URL-HERE">Invite</a>
```

Which turns into this: <a href="mailto:?subject=Your%20invitation%20to%20AWESOME%20DOCUMENT&body=URL-HERE">Invite</a> (Subject would obviously contain document title, while the body could also contain something a little more elaborate. But you get the idea.

This would depend on the email client on your computer or smartphone being correctly configured (which it probably is already).
