### ISSUE TITLE
編輯工具列

### ISSUE THREAD

**Issue by kay54068** [hackmdio/hackmd#810]
請問要如何設定開啟編輯視窗的工具列?

![image](https://user-images.githubusercontent.com/3054544/39356601-01566058-4a43-11e8-8199-c46c84b3ebbf.png)

**Comment by jackycute** [comment]
您好，如果要回報 HackMD.io 與 HackMD Enterprise Edition 的 issue，請至 https://github.com/hackmdio/hackmd-io-issues/issues
HackMD.io 上的工具列並沒有開源

另外，Community Edition 的工具列正在開發中
討論串請見：https://riot.im/app/#/room/!ybaSlrrMNLeuoQuUuR:matrix.org/$1523543719111938hLGgG:matrix.org
Repo：https://github.com/okfde/hackmd/commits/master
這裡可以試用：https://hackmd.okfn.de
