### ISSUE TITLE
Can Not connect hackmd.io directly in PRC

### ISSUE THREAD

**Issue by cmmei** [hackmdio/hackmd#815]
I can not connect https://hackmd.io directly in PRC. But if trying to connect it by VPN, it is OK. What happend ? HACKMD or Amazon service?

I have a ping test, it shows all timeout.
![selection_001](https://user-images.githubusercontent.com/11864255/39708140-eb43d224-5248-11e8-9d9b-903517119e00.png)

And, by ping hackmd.io, the result tells that it uses Amazon data center service in US and Japan.
![Selection_002.png](https://i.loli.net/2018/05/07/5af068d2d8146.png)

**Comment by jackycute** [comment]
Hi, for reporting HackMD.io issue, please visit https://github.com/hackmdio/hackmd-io-issues/issues

FYI: hackmd.io still operate normally. I think it might get banned in GFW.
