### ISSUE TITLE
Exported PDF does not include images

### ISSUE THREAD

**Issue by martinchodev** [hackmdio/hackmd#820]
Hello, I'm not sure if there is a problem with my installation of HackMD, but when I export as PDF, all the images appear as "broken image" icons. 

![captura de pantalla_2018-05-12_11-46-45](https://user-images.githubusercontent.com/7395872/39958488-31fc0346-55da-11e8-82e3-5db38c6e6f0c.png)

This happens with external images and images uploaded by me in HackMD as well.

Any ideas?

Thanks!

**Comment by SISheogorath** [comment]
Can you provide a document to reproduce it?

Seems to be working when I use our features page: https://hackmd-ce.herokuapp.com/features#

**Comment by martinchodev** [comment]
Thanks for the quick reply!

Here you go: https://pad.tttdevs.com/GGO87DrASlKPEh6Nq6kzbg#

**Comment by SISheogorath** [comment]
Okay, after a quick test, this is caused by relative links that are created on upload.

Not sure how to fix it yet, but at least we know what's wrong. This only happens when `filesystem` is used as upload method.

**Comment by martinchodev** [comment]
Allright! If you need anything else just let me know.

**Comment by jackycute** [comment]
I think maybe convert the img src starts with `/` to `file:///` might help.

**Comment by SISheogorath** [comment]
@zeigerpuppy can you check that `wget -O- https://codimd.greenant.net/tDha9czKRXm30iW-dqOHFg/download` from inside the container results in the markdown of your instance printed out to your cli?

My current guess why it fails in your case is that your container doesn't have access to the outside address of your reverse proxy.

**Comment by zeigerpuppy** [comment]
Thanks @SISheogorath, that was the issue!  

I have now set my internal DNS server to redirect to the local web proxy (internal address) and now the PDF export works.

**Comment by jgrocha** [comment]
Same problem here! I did not set the hostname in the configuration.

**Comment by littlefish0331** [comment]
@zeigerpuppy I encounter the same problem. Can you tell me how to fix this?
I try to google the keyword of your answer, but i am so new that I cannot understand how to set the network. 😢

**Comment by miyouzi** [comment]
You can add the `extra_hosts` configuration to your Compose file to map your domain name to the host machine within the container.

```yaml
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.6.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "YOUR_DOMAIN:host-gateway"
```

However, a new problem has arisen: if you resize the image using the `=50%x` syntax, the image will no longer be loaded into the PDF.

<img width="1566" height="306" alt="Image" src="https://github.com/user-attachments/assets/aef30dad-8be6-4f7e-9f8c-90c5526bec7f" />
