### ISSUE TITLE
[request]: provide API for creating notes

### ISSUE THREAD

**Issue by maddhruv** [hackmdio/hackmd#829]
This is a call on request, 
I am from Node.js Foundation

We conduct our regular meetings and save meeting notes in markdown on Google docs only because they provide API for creating the docs.

The meeting conductor uses a script to create a meeting - zoom link, Google docs link, calendar event and invitees.

If HackMD can provide us an API with which we can generate the minutes notes, we would love to use HackMD.

Please revert back on this thread, so that we can figure out a way using the same.

**Comment by SISheogorath** [comment]
You may want to look at this PR which is already in stable: https://github.com/hackmdio/hackmd/pull/673

Right now there is no official API, but it's already possible to use scripts to create these notes.

**Comment by ccoenen** [comment]
This is also relevant: It's not (yet) Part of HackMD, but as far as I know, it works. It's a bash script to import, publish or export documents:

https://github.com/hackmdio/hackmd/issues/808

**Comment by SISheogorath** [comment]
Closed to inactivity.
