### ISSUE TITLE
Support two spaces for list indentation

### ISSUE THREAD

**Issue by Nowaker** [hackmdio/hackmd#83]
Example:

1. Test 1.
  - Blah.
  - Blah.
2. Test 2.

It's formatted correctly on GitHub but not in Hackmd.

**Comment by jackycute** [comment]
Actually it support two spaces for list indentation.
The issue is it parse different list start syntax as different list, not continue one.

**Comment by jackycute** [comment]
OK, first thing to say:
Sorry, I will not support two space indentation list by myself.
It's not a technical problem, but may cause inconsistency issues.

The main reasons are:
1. It doesn't meet the CommonMark standard.
2. This might affect other nest order list and unorder list.

You might able to open an issue on markdown-it.
If they support, we support.
https://github.com/markdown-it/markdown-it/issues

**Comment by jackycute** [comment]
Let's do this
https://github.com/markdown-it/markdown-it/issues/202

**Comment by jackycute** [comment]
Unfornately, CommonMark have strong and reasonable reason why they chose 4-spaces rule instead of others.
http://spec.commonmark.org/0.24/#motivation

If we want to achieve this, we are on our own.
