### ISSUE TITLE
Larger Checkbox Size in Slide Mode

### ISSUE THREAD

**Issue by liuderchi** [hackmdio/hackmd#831]
Can we add _Custom Styles_ to enlarge the checkbox input in Slide Mode?
It looks fine in Preview Pane but perhaps too small in Slide Mode?

(LEFT: Slide Mode | RIGHT: Preview Pane)

![demo](https://user-images.githubusercontent.com/4994705/40769644-1c10eac2-64eb-11e8-8474-a461be135d7d.png)

Example: [待辦清單 in markdown](https://hackmd.io/s/ByAePIJd#%E5%BE%85%E8%BE%A6%E6%B8%85%E5%96%AE) and [how it looks in Slide Mode](https://hackmd.io/p/ByAePIJd#/6/11)

---

As of my personal preference, adding `transform: scale(1.5)` to the html input looks good.

![demo2](https://user-images.githubusercontent.com/4994705/40769866-ae432e46-64eb-11e8-8b1e-934925c185b7.png)

---

UPDATE: I am on machine of
- macOS 10.13.4 (Macbook Air 2017)
- Chrome 66.0.3359.181

**Comment by jackycute** [comment]
@liuderchi Yes, you can.
Use <style> tag to put custom CSS styles in your note.

**Comment by liuderchi** [comment]
@jackycute thanks. After reading #467 I apply it by adding 
`<style>input[type=checkbox] { transform: scale(1.5); }</style>` to the note

Would you consider to change _default size of checkbox_?
I would close this issue if it's not in your plan.

**Comment by SISheogorath** [comment]
I think larger checkboxes are a good idea :)

Can you please file a PR for this?

Should be added to this file: https://github.com/hackmdio/hackmd/blob/master/public/css/slide.css

**Comment by jackycute** [comment]
I do agree that we need larger checkbox in slide mode, but I also noticed that in other OS (Windows) the checkbox is large enough, so we might want to test those out.

**Comment by liuderchi** [comment]
@SISheogorath I would like to help with CONTRIBUTING!

I would try to make it looks like GitHub Markdown checkbox (probably as large as an `X`)

- [ ] X

---

> in other OS (Windows) the checkbox is large enough...

@jackycute I am curious of how reveal.js processes checkbox since I don't see it on [reveal.js demo page](https://revealjs.com/#/14). Would the root cause located at reveal.js itself?

I Tried to test it on [reveal.js online editor](https://slides.com/) but found it [not supporting markdown in UI](http://help.slides.com/forums/175819-general/suggestions/3173492-add-markdown-option-to-wysiwyg)

**Comment by jackycute** [comment]
@liuderchi 
So the checkbox is not related to the markdown parser or even the reveal.js.
It's just the visual styles of checkbox is different between OS (or browser).
We just give a simple `input type="checkbox"` here.

Please read more here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/The_native_form_widgets#Check_box

**Comment by liuderchi** [comment]
> checkbox is not related to the markdown parser or even the reveal.js.

@jackycute I am not sure. From the doc [those checkboxes look quite similar in size](https://developer.mozilla.org/files/4595/all-checkbox.png):

I just want to points out that _one checkbox syntax ends up with different proportion in size_ on _Preview Pane_ and _Slide Mode_. Would it happen on Windows machine?

**Comment by jackycute** [comment]
It's true that the checkbox size is smaller in slide mode, I just measure them (14px vs 7.83px)
That might from the CSS style we've given to the checkbox:
https://github.com/hackmdio/hackmd/blob/master/public/css/slide.css#L82

Since the height using `em` it might be affected by the parent node styles.
It would be nice if you could take a deeper look.

Thanks.

**Comment by liuderchi** [comment]
@jackycute thanks for your information 💯 
I will fork and read the CONTRIBUTING.md and try to launch service on locally

**Comment by SISheogorath** [comment]
If someone notices a problem feel free to open a new issue :)
