### ISSUE TITLE
HTML5-Shim ignores UseCDN: false

### ISSUE THREAD

**Issue by mrdrogdrog** [hackmdio/hackmd#841]
```
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  | <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  | <!--[if lt IE 9]>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" integrity="sha256-3Jy/GbSLrg0o9y5Z5n1uw0qxZECH7C6OQpVBgNFYa0g=" crossorigin="anonymous"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js" integrity="sha256-g6iAfvZp+nDQ2TdTR/VVKJf3bGro4ub5fvWSWVRi2NE=" crossorigin="anonymous"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.9/es5-shim.min.js" integrity="sha256-8E4Is26QH0bD52WoQpcB+R/tcWQtpzlCojrybUd7Mxo=" crossorigin="anonymous"></script>
  | <![endif]-->
```

This shouldn't be there if you deactivate the CDNs.

**Comment by SISheogorath** [comment]
Yes, it makes sense to remove them, even when all modern browsers shouldn't care anyway.

I just wonder if we just want to remove it or if we want to build the self-hosted alternative, which is probably work that is not needed as no one who uses HackMD is using IE 8 anymore.

IE 8 doesn't even support websockets… I wonder if we even want to support it in future? The only reason to Have IE8 is to run an unpatched version of Windows 7 or older, which I wouldn't recommend at all.

**Comment by ccoenen** [comment]
Strongly against IE8. IE11 (which is a whopping five years old!) can be made a case for, but anything older than that - in my opinion - can not.
