### ISSUE TITLE
"Refresh to enjoy new features." is inaccurate

### ISSUE THREAD

**Issue by Himura2la** [hackmdio/hackmd#847]
https://github.com/hackmdio/hackmd/blob/09a7bcbdef237c1443bbbfc29010e7106cffd739/public/views/shared/refresh-modal.ejs#L19

It just does not work. I refresh and this window pops up again. 

![](https://user-images.githubusercontent.com/7802808/41664125-a849c122-74ad-11e8-9907-8630b6fae76f.png)

Ctrl+F5 helps, so it should be like "Clear cache and cookies to enjoy new features."

**Comment by SISheogorath** [comment]
Are you using a reverse proxy? Maybe nginx in front? Probably there is some caching happening.

We don't store the version number in a cookie or similar so it has to come with the page, which can only explained when the page itself is cached.

**Comment by Himura2la** [comment]
No proxy, your Docker image

**Comment by SISheogorath** [comment]
mhm… I have to admit that it's us :D

Having a high cache time for static content is basically a good idea…
https://github.com/hackmdio/hackmd/blob/82c7f9d07cfecfc110af8c8fc0e47edf070596b2/app.js#L144


…until you notice that you put the important dynamic part into it.
https://github.com/hackmdio/hackmd/blob/82c7f9d07cfecfc110af8c8fc0e47edf070596b2/app.js#L29-L43

**Comment by Himura2la** [comment]
Thanks for your research! I hope it should be fixed by changes in the message or in the code.

**Comment by MelBourbon** [comment]
I deployed by docker and restored my existing database. No I get this message every time I open a note and it pops up again every time I reload. Deleting browser cache did not resolved this. Any ideas why this is now occurring again?
