### ISSUE TITLE
Export to GitHub Gist

### ISSUE THREAD

**Issue by Rplus** [hackmdio/hackmd#85]
I hope hackpad's note could be export to gist.
It'll be helpful to discuss & backup
just like [sassmeister](http://www.sassmeister.com) or [codepen](codepen.io).
![image](https://cloud.githubusercontent.com/assets/1808835/12683353/bb234c4c-c6f3-11e5-8303-ad027059268a.png)

![image](https://cloud.githubusercontent.com/assets/1808835/12683326/8c32f400-c6f3-11e5-8f19-cee117429748.png)

#feature

**Comment by jackycute** [comment]
Sure, will do.

**Comment by jackycute** [comment]
Supported in ff2fc76491c11fad33ae6c62c4d5b5c47b431597

**Comment by Rplus** [comment]
:+1:

**Comment by jackycute** [comment]
Sure, beware that dashes are not support in filename in Gist :+1:
