### ISSUE TITLE
Feature Request: Enable relative path like http://www.example.com/hackmd

### ISSUE THREAD

**Issue by adachij2002** [hackmdio/hackmd#86]
I'd like to configure apache to serve hackmd at any route like http://example.com/hackmd.

**Comment by jackycute** [comment]
I haven't tried this yet, I use nginx more.
But I think you can achieve that by reverse proxy?

https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by adachij2002** [comment]
Yes, I'm using mod_proxy_http as follows, that works fine.
``` xml
<Location />
    ProxyPass http://localhost:3000/
    ProxyPassReverse http://localhost:3000/
</Location>
```

But It's not working as follows, because static file or redirect path uses fixed path like "/", "/new", "/css" and so on.
``` xml
<Location /hackmd>
    ProxyPass http://localhost:3000/
    ProxyPassReverse http://localhost:3000/
</Location>
```

**Comment by jackycute** [comment]
OK, I will see what I can do.

**Comment by jackycute** [comment]
Supported in b2b1be3dda406312add39997ad8bd9494f20b7f8
You will need following configs for apache (I tried):

For example, your url is `www.example.com/hackmd`, hackmd run on port 3000

```
RewriteEngine On
RewriteCond %{REQUEST_URI}  ^socket.io [NC]
RewriteCond %{QUERY_STRING} transport=websocket [NC]
RewriteRule /hackmd/{.*} ws://localhost:3000/$1 [P,L]

RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteRule /hackmd/(.*) ws://localhost:3000/$1 [P,L]

ProxyRequests Off
ProxyPreserveHost On

ProxyPass        /hackmd http://localhost:3000
ProxyPassReverse /hackmd http://localhost:3000

ProxyPass        /hackmd/socket.io http://localhost:3000/socket.io
ProxyPassReverse /hackmd/socket.io http://localhost:3000/socket.io

ProxyPass        /hackmd/socket.io ws://localhost:3000/socket.io
ProxyPassReverse /hackmd/socket.io ws://localhost:3000/socket.io
```

**Comment by jackycute** [comment]
Hi @adachij2002 
Did you see this issue update?
Please tell me when you're good.

**Comment by adachij2002** [comment]
It works fine for me.Thank you!
But this apache configuration is a little bit complex.
Is it difficult to wait on the following URL by Node.js?
```
http://localhost:3000/hackmd
http://localhost:3000/hackmd/socket.io
ws://localhost:3000/hackmd/socket.io
```

**Comment by jackycute** [comment]
Seems it's ok to be like this:

```
RewriteEngine On
RewriteCond %{REQUEST_URI}  ^socket.io [NC]
RewriteCond %{QUERY_STRING} transport=websocket [NC]
RewriteRule /hackmd/{.*} ws://localhost:3000/$1 [P,L]

RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteRule /hackmd/(.*) ws://localhost:3000/$1 [P,L]

ProxyRequests Off
ProxyPreserveHost On

ProxyPass        /hackmd http://localhost:3000
ProxyPassReverse /hackmd http://localhost:3000
```

**Comment by adachij2002** [comment]
>It's not possible without proxy http://localhost:3000/hackmd

I see.

Do you Sing in via OAuth with that configuration?
I caught error as follows.
```
Not Found
The requested URL /auth/github/callback was not found on this server.
```

I configured apache like this
```
ProxyPass        /auth http://localhost:3000/auth
ProxyPassReverse /auth http://localhost:3000/auth
```

But I caught error as follows.
```
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
```

**Comment by jackycute** [comment]
Actually, you don't need to config apache like that (proxy `/auth`)

That error is caused by the OAuth provider setting's callback url not match the one you send.
So you need to modify the callback url whenever you change your server url.

For example, GitHub would like this:
<img width="725" alt="2016-02-20 9 36 48" src="https://cloud.githubusercontent.com/assets/2639151/13193565/c3c3ee4c-d7b5-11e5-884e-7da3466265ad.png">

**Comment by adachij2002** [comment]
Sorry for my miss configuration.
It works fine!
Please close this ticket.
Thanks a lot.

**Comment by jackycute** [comment]
:+1: Happy Coding!
