### ISSUE TITLE
Japanese comma(、) and period(。) aren't displayed correctly in editor mode.

### ISSUE THREAD

**Issue by taiyoslime** [hackmdio/hackmd#87]
## Overview
I noticed that Japanese comma(、) and period(。) aren't displayed correctly in editor,like this screenshot.

![hackmd1](https://cloud.githubusercontent.com/assets/11515982/13044919/002da13e-d414-11e5-90d4-c437bcf9da3a.JPG)

In viewer mode,it looks good(as this picture shows).

![h](https://cloud.githubusercontent.com/assets/11515982/13045011/75b29130-d414-11e5-88f1-2ecb00ab3893.JPG)

#### env

[OS] Windows 8.1 
[browser] Google Chrome v48
[language] Japanese

**Comment by jackycute** [comment]
Thanks for report!
I will fix this soon.

**Comment by jackycute** [comment]
Fixed in 880f6bcf0266578c4e8e16d909c18af0449943cc

**Comment by jackycute** [comment]
Suggest to add YAML lang meta to let note show correctly on all languages browsers.

Like this:
```
---
lang: ja
---
```

<img width="1110" alt="2016-02-15 7 22 25" src="https://cloud.githubusercontent.com/assets/2639151/13064554/ad4a8256-d419-11e5-9767-fdd0ac621dd8.png">

**Comment by taiyoslime** [comment]
Thanks!!
