### ISSUE TITLE
Highlighter works only top line of the list in editor

### ISSUE THREAD

**Issue by taiyoslime** [hackmdio/hackmd#88]
## overview
Using lists, only top line of the list has highlighted in editor like this.
<img width="1090" alt="ss 2016-02-17 21 33 25" src="https://cloud.githubusercontent.com/assets/11515982/13109762/aefe86be-d5be-11e5-8acc-855d5ce29dab.png">

Is this a bug, or a feature...?

#### env

[OS]Mac OS X Yosemite(10.10.2)
[browser] Google Chrome v.48

**Comment by jackycute** [comment]
Oh, this is a feature to make it more eaiser to identify the first item in the list (when there are more lists will show the adventage of this highlighting).

**Comment by jackycute** [comment]
close because this is a feature.
reopen if you need other helps.
:smile:

**Comment by jackycute** [comment]
wait a sec.
Now I feel it's kinda strange.
Let me figure out.

**Comment by jackycute** [comment]
Open issue on CodeMirror for further help
https://github.com/codemirror/CodeMirror/issues/3833

**Comment by taiyoslime** [comment]
Thanks!:thumbsup:

**Comment by jackycute** [comment]
Fixed in 921b5f46523115de9a2fcaf530148b9607b8f537
