### ISSUE TITLE
Colon confuses MathJax parsing

### ISSUE THREAD

**Issue by grafdan** [hackmdio/hackmd#89]
#56 As in [this earlier issue](https://github.com/hackmdio/hackmd/issues/56), having a colon before a mathjax formula does prevent the math formula from rendering. [See an example here.](https://hackmd.io/KYQwZgxgRgzAjABgLRwCxQCZNXYWrACsISEAbPAJwKWVhgDsAHEA)

**Comment by jackycute** [comment]
Fixed in 1da0b87714e725dcd540f389b118c581fd93ccb7
Thanks for report.
