### ISSUE TITLE
能支持mermaid解析器為新功能?

### ISSUE THREAD

**Issue by laysdra7265** [hackmdio/hackmd#91]
我本來一直在使用hackpad，不過實在是沒有安全感因為官網沉靜太久了，加上反應略慢一直在找替代的服務
HACKmd反倒是點亮了我的眼睛，不論是反應速度或是介面外觀都很合我的胃口XD
但因為共事的大都是大陸內地的網友，在本地登入功能開發出來前估計沒辦法用(大陸把大部分國外服務都牆了這對他們來說根本無門登入)
不過我想在這裡推薦一個 mermaid解析器
可以用markdawn來繪製各種圖表
這是他的官網http://knsv.github.io/mermaid/
他的github:https://github.com/knsv/mermaid
具體效果可以看看markdawn plus的 demo網站:http://mdp.tylingsoft.com/
我覺得如果這能作為插件之類的形式加入hackmd 增加markdawn的功能肯定能更上一層樓

**Comment by jackycute** [comment]
嗨！您好，謝謝您喜歡 HackMD！
這個專案確實也是被 hackpad 啟發，不過會繼續保持活躍的 :smile: 

本機登入的功能有列入 issue 了，因為現在在做其它 issue 所以會晚一點做這個
https://github.com/hackmdio/hackmd/issues/36
有 GFW 真是辛苦你們了！

mermaid 之前就有考慮過了，後來一忙就忘記了 :wink: 
我想近期之內就會支援，mermaid 確實不錯用呢！

**Comment by jackycute** [comment]
服務支援了喔！
開源的部分晚點 push 上來～
<img width="1214" alt="2016-03-04 5 44 44" src="https://cloud.githubusercontent.com/assets/2639151/13523510/d8fcf2f6-e230-11e5-86b6-abbe624eb2bf.png">

**Comment by jackycute** [comment]
Supported in b49d4e22616d7ac2a60db08dc69fdaf9b973cb04
