### ISSUE TITLE
Please add Mysql-based DB support

### ISSUE THREAD

**Issue by matunixe** [hackmdio/hackmd#92]
Hello,

I'm actually using MariaDB and I would be very happy if someone can add support for this.
Thanks in advance.

Cheers,

**Comment by jackycute** [comment]
Hi,

We already plan to use Sequelize to ORM.
But need more work to migrate previous data and schemas.

Related to #15 #19

**Comment by matunixe** [comment]
@jackycute 

Hey,
I understand, thank you very much for your answer.
I will wait!

**Comment by jackycute** [comment]
Is it ok to use PostgreSQL? I prefer that than MySQL-like DBs.

**Comment by matunixe** [comment]
That will be fine but please provide clear and detailed configuration step for setting up the PostgreSQL db (I don't know it well). :+1:

**Comment by jackycute** [comment]
Support PostgreSQL, MySQL, MariaDB, SQLite, MSSQL in version 0.4.0
