### ISSUE TITLE
Convert tabs into spaces

### ISSUE THREAD

**Issue by ETBlue** [hackmdio/hackmd#94]
hihi jacky
it would be great for debater users if tabs are converted into spaces automatically >.^

**Comment by jackycute** [comment]
Hi @ETBlue, you can change your tab behavior via click "tab size" button which below the editor, also the indent size on the side.
<img width="619" alt="2016-02-07 1 11 10" src="https://cloud.githubusercontent.com/assets/2639151/14060627/9476af06-f3a5-11e5-8539-3b517866707f.png">

**Comment by ETBlue** [comment]
!!!
didn't know this before!
thanks a lot :D :D :D

**Comment by CrashLaker** [comment]
awesome!
specially when copy/pasting Makefiles
