### ISSUE TITLE
Support for spell-check?

### ISSUE THREAD

**Issue by orschiro** [hackmdio/hackmd#95]
Dear all, 

Your tool is fantastic, thank you so much!

The only thing I am currently missing is the support for Chrome's built-in spell-check.

Is this something that you envision and that is technically possible?

Thankfully,

~Robert

**Comment by jackycute** [comment]
Hi, Robert!
Thanks for using!

It's technically possible to have the spell-check feature.
And that is a very useful feature I always want HackMD to have.
But the HTML tag we are using now for the editor doesn't support built-in spell-check.
Even though we will do more research and seek more approaches for you and everyone.
So just leave this issue here and you will see the changes in the future!

😄

**Comment by orschiro** [comment]
Dear Max,

  

Thank you for your timely and positive response!

  

Please keep me in the pipe about the developments.

  

I am happy to test any next steps that bring us closer to having support for
spell-check in your wonderful editor! :-)

  

Thankfully,

  

~Robert

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 12 2016, at 7:03 pm, Max Wu &lt;notifications@github.com&gt; wrote:  

> Hi, Robert!  
Thanks for using!

>

> It's technically possible to have the spell-check feature.  
And that is a very useful feature I always want HackMD to have.  
But the HTML tag we are using now for the editor doesn't support built-in
spell-check.  
Even though we will do more research and seek more approaches for you and
everyone.  
So just leave this issue here and you will see the changes in the future!

>

> 😄

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hackmdi
o/hackmd/issues/95#issuecomment-209008523)![](https://github.com/notifications
/beacon/AAKbwxzhb8mV7nXzP_eDkBevJEpkWDJeks5p29BGgaJpZM4IFlrU.gif)

**Comment by jackycute** [comment]
I found something interesting:

https://github.com/NextStepWebs/codemirror-spell-checker
https://src.chromium.org/viewvc/chrome/trunk/deps/third_party/hunspell_dictionaries

And I believe you already know these resources.
And I will try these out later.

**Comment by orschiro** [comment]
Dear Max,

  

Hunspell sounds good as it means that it will hopefully work flawlessly on
Linux. :-)

  

Thanks for your efforts!

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 12 2016, at 8:15 pm, Max Wu &lt;notifications@github.com&gt; wrote:  

> I found something interesting:

>

> <https://github.com/NextStepWebs/codemirror-spell-checker>  
<https://src.chromium.org/viewvc/chrome/trunk/deps/third_party/hunspell_dictio
naries>

>

> And I believe you already know these resources.  
And I will try these out later.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hackmdi
o/hackmd/issues/95#issuecomment-209038818)![](https://github.com/notifications
/beacon/AAKbwx4_9Sc8mxDQPhcAl9G3mELhuNFoks5p2-E4gaJpZM4IFlrU.gif)

**Comment by jackycute** [comment]
I've tried that plugin and use the chromium dictionaries, result pretty good.
But it will overwrite other indicators (like: mark match word).
And it also apply on code block which is not needed.
So I need to rewrite that plugin, but things are going promising.

**Comment by orschiro** [comment]
Hi Max,

  

Promising progress!

  

This is not yet publicly testable, correct?

  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 13 2016, at 5:03 am, Max Wu &lt;notifications@github.com&gt; wrote:  

> I've tried that plugin and use the chromium dictionaries, result pretty
good.  
But it will overwrite other indicators (like: mark match word).  
And it also apply on code block which is not needed.  
So I need to rewrite that plugin, but things are going promising.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hackmdi
o/hackmd/issues/95#issuecomment-209205011)![](https://github.com/notifications
/beacon/AAKbw9XZ9pYSEcA5YkdyhWlP6NPgMDqzks5p3FztgaJpZM4IFlrU.gif)

**Comment by jackycute** [comment]
Yes, it's not ready for now.
Maybe I'll make it as a experiment feature in these days.

**Comment by orschiro** [comment]
> Maybe I'll make it as a experiment feature in these days.

Alright. Please let me know if I can be of use for something in the meantime.

~Robert

**Comment by jackycute** [comment]
Hi, Robert!
I made a note for spellcheck test:
https://hackmd.io/GYRgDAxgHAbAnAVgLRQCwENVNaqBTFAExGQCMp1h0I9y9hCg
Could you try it out?

**Comment by orschiro** [comment]
Hi Max,

  

Wow, thanks for your quick implementation!

  

Underlining  is working. However, right mouse click context menu to show
correct suggestions does not work. :-(

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 15 2016, at 3:55 am, Max Wu &lt;notifications@github.com&gt; wrote:  

> Hi, Robert!  
I made a note for spellcheck test:  
<https://hackmd.io/GYRgDAxgHAbAnAVgLRQCwENVNaqBTFAExGQCMp1h0I9y9hCg>  
Could you try it out?

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hackmdi
o/hackmd/issues/95#issuecomment-210245127)![](https://github.com/notifications
/beacon/AAKbw97jjXDD21I2VToB89Fzkq2xAFJWks5p3vAKgaJpZM4IFlrU.gif)

**Comment by jackycute** [comment]
Hi, Robert,
Yeah, because it's not actually using the Chrome built spell-check function.
Because the ways to activate spell-check is limited, we have to do it by our own.
Also that's mean if we want to give the spell suggestion, we must build our own context menu.

Any advises welcomed.

**Comment by orschiro** [comment]
&gt; Also that's mean if we want to give the spell suggestion, we must build
our own context menu.

  

Interesting. I guess where are not the first ones facing this problem.

  

Maybe there are other parties we can team up with to build our own context
menu collaboratively together?

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 15 2016, at 3:39 pm, Max Wu &lt;notifications@github.com&gt; wrote:  

> Hi, Robert,  
Yeah, because it's not actually using the Chrome built spell-check function.  
Because the ways to activate spell-check is limited, we have to do it by our
own.  
Also that's mean if we want to give the spell suggestion, we must build our
own context menu.

>

> Any advises welcomed.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/hackmdi
o/hackmd/issues/95#issuecomment-210467538)![](https://github.com/notifications
/beacon/AAKbw9VX2E60HlNiEdbT5MvCJWGQ0u5jks5p35UDgaJpZM4IFlrU.gif)

**Comment by jackycute** [comment]
Maybe:
https://github.com/swisnl/jQuery-contextMenu
https://github.com/sydcanem/bootstrap-contextmenu

**Comment by orschiro** [comment]
Thanks for finding these!

The first one seems to be very actively developed.  

But maybe it also goes beyond the scope of this project to have a proper
dictionary suggestion integration.  

Red underline is already useful to easily identify misspelled word, with
manual thinking intervention followed. :-)  

~Robert

**Comment by jackycute** [comment]
Hi Robert!
I think I would like to move the spellcheck feature from YAML metadata to editor status bar.
Because it seems like a user-oriented profile.

**Comment by orschiro** [comment]
Hi Max,

Can you show a screenshot example, please?

Thankfully,

~Robert

**Comment by jackycute** [comment]
I mean at the position of the red square indicate on below pic
![1](https://cloud.githubusercontent.com/assets/2639151/14843680/dca4c25c-0c84-11e6-94f9-1462474948a2.png)

**Comment by orschiro** [comment]
Ah, cool!

So users would be able to enable the spell-check from the below statusbar?

~Robert

**Comment by jackycute** [comment]
yes, totally

**Comment by orschiro** [comment]
Like it! :)

**Comment by jackycute** [comment]
Supported in 09fb1209678b2acc18ee13ee0c407278e67d2c06

**Comment by orschiro** [comment]
Hey @jackycute,

Thanks a lot for eventually implementing it! :+1: 

Warmly,

~Robert

**Comment by RoyiAvital** [comment]
@jackycute , Is it alive?
Because I don't see it (Spell Checking) working in my session.

Thank You.

**Comment by evok3d** [comment]
Thank you so much. I love your tool and was hoping to find a solution for a spell check. Now i see you have it ready to go! :D

**Comment by banderlog** [comment]
Anyone could switch spellchecking languages or everyone stick to default english?

**Comment by Yukaii** [comment]
Hi @banderlog We use [codemirror-spell-checker](https://github.com/sparksuite/codemirror-spell-checker) and it only supports english now. Could you open a seperate issue for tracking multi-language spellcheck support?

**Comment by AlexWayfer** [comment]
@Yukaii not needed, it already exists: https://github.com/hackmdio/codimd/issues/647

**Comment by banderlog** [comment]
@Yukaii , @AlexWayfer thank you, guys
