### ISSUE TITLE
Cannot Get Latest Code Working

### ISSUE THREAD

**Issue by jimmybrancaccio** [hackmdio/hackmd#96]
Hello,

First of all, I love HackMD! Fantastic job! I've gotten it all setup and working, but I've hit an issue I've updated from the GitHub repository with the latest code available today and now HackMD has stopped functioning. I run the application using - `node app.js`, though I did try with pm2 and it's not working there either. Generally I proxy it through Nginx but for testing I am accessing port 3000 directly.

Using curl I can fetch most of the contents if not all:

`curl http://127.0.0.1:3000`

but then I get something like:

`curl: (18) transfer closed with outstanding read data remaining`

I've done some investigation and it may be something to do with the Content-Length not being set properly? I'm not so great with nodejs apps (or programming in general), but any ideas on this would be much appreciated!

**Comment by jackycute** [comment]
Hi, Jimmy. Thanks for loving HackMD!

Sorry about what make your app stop working.
But I did change a lot of the server settings and other things for incoming version.

For the message you mentioned is not enough to tell what happened.
Could you paste the logs from `pm2 logs` or logs from your console?
Also could you surf the app via your browser and show me the logs from Developer Console, too?

The next version is coming in few days and that will contain more breaking changes.
I highly recommend you wait for it :smile:

**Comment by jimmybrancaccio** [comment]
Heya @jackycute!

Apologies for the lack of logs, the only thing I could get when running it through node was:

```
2016-04-13T23:15:43.321Z - info: HTTP Server listening at port 3000
2016-04-13T23:16:18.663Z - info: ::ffff:127.0.0.1 - - [13/Apr/2016:23:16:18 +0000] "GET / HTTP/1.1" 200 - "-" "curl/7.38.0"
```

I think I had already removed the install where I tried using pm2, so no logs there, but it looks like it's just hanging waiting for the process to tell it it's done sending data. Now this all may be moot since you're going to push some new code in the new few days. I'll hold out and update from there once you do! Thanks for being so responsive, some repositories and maintainers aren't :) Keep up the great work! :+1:

**Comment by jackycute** [comment]
Could you please try version 0.4.0?
Or maybe try docker-hackmd will be easier?

**Comment by jimmybrancaccio** [comment]
Hey @jackycute, apologies for the non-update yesterday. It was a long day! That said, I did get 0.4.0 up and running. I did try using the migration tool, but it just sat there at the 'found stuff in MongoDB, importing to PostgreSQL' message and wasn't doing anything. Being that it was around 8pm and it having been a long day already, I didn't have the time, patience or attention span to further debug and troubleshoot it. I ended up manually copying the 7-8 notes I had into a local Notes app, dropping the PostgreSQL database, recreating it and starting fresh. All is working well in 0.4.0 from what I've noted. Thank you much for locking the Features note by default now, that was bugging me haha Great, awesome work! I think we can consider this one closed. 👍

**Comment by jackycute** [comment]
Wow, glad that you've passed that long day.
Now you can use either PostgreSQL, MySQL, MariaDB, SQLite or MSSL as your only need DB (no more MongoDB).
And sorry about the migration tool because it only test on my local machine and the official server.

Sounds like a magic, I thought it few days ago that the features and docs should be locked by default.
Thanks for giving feedback and using HackMD :smile:
