### ISSUE TITLE
Cheat sheet needed

### ISSUE THREAD

**Issue by chihaoyo** [hackmdio/hackmd#98]
As more and more extra functions are added in addition to the “standard” markdown, a cheat sheet is needed. While https://hackmd.io/features is available, a graphic-designified cheat sheet would be quicker.

**Comment by jackycute** [comment]
Add in 4aa4e3eacc36ae54c49ac94cf40594f33c4d9b1d

<img width="933" alt="2016-05-11 2 29 03" src="https://cloud.githubusercontent.com/assets/2639151/15172112/506043f4-1786-11e6-82f3-d4734225cd11.png">

**Comment by PaulGWebster** [comment]
Appears to be missing for if you want to link to something internal to the document say for instance '### some header' an anchor link
